# Welcome to my cleaning phase of analysing data.

## Collection of the data:

After I collected/scraped real-world data from the web, we completed the first step of Collecting the Data.

The next step/phase is to Clean and Transform the Data so we can actually use it to make some insights.

## As always, Import the libraries.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("wc_data_jobs_20260613_1418.csv")
df

,search_role,site,title,company,location,job_type,is_remote,date_posted,min_amount,max_amount,currency,interval,description,job_url,scraped_at
0,Data Analyst,indeed,Claims Risk Analyst,Momentum Health,"Bellville, WC, ZA",NaN,False,2026-06-12,NaN,NaN,NaN,NaN,**Introduction**\nThrough our client\-facing b...,https://za.indeed.com/viewjob?jk=1c27bef7a3d49dc1,2026-06-13 14:18:21
1,Data Analyst,indeed,Senior Application Support Analyst (SQL-focused),MRI Software,"Cape Town, WC, ZA",fulltime,False,2026-06-12,NaN,NaN,NaN,NaN,MRI Software is seeking a Senior Application S...,https://za.indeed.com/viewjob?jk=8fa3139aef3495e3,2026-06-13 14:18:21
2,Data Analyst,indeed,SOC Analyst,Zappi,"Cape Town, WC, ZA",fulltime,False,2026-06-12,NaN,NaN,NaN,NaN,### **Description**\n\n \n\nWe believe in hir...,https://za.indeed.com/viewjob?jk=80aeb6ac4d43e5d3,2026-06-13 14:18:21
3,Data Analyst,indeed,Chief Delivery Officer (CDO),NJ Placement Consulting,"Rosebank, WC, ZA",fulltime,False,2026-06-12,NaN,NaN,NaN,NaN,##### **Overview**\n\n\nAmazing chance to join...,https://za.indeed.com/viewjob?jk=7077c05a2c616941,2026-06-13 14:18:21
4,Data Analyst,indeed,Business Intelligence Analyst,LekkeSlaap,"Cape Town, WC, ZA",fulltime,True,2026-06-12,NaN,NaN,NaN,NaN,Bring 3\+ years of proven experience in busine...,https://za.indeed.com/viewjob?jk=dd0f358d23d62da8,2026-06-13 14:18:21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284,Data Architect,linkedin,Lead Data Scientist,Network Recruitment,"City of Cape Town, Western Cape, South Africa",NaN,False,2026-06-02,NaN,NaN,NaN,NaN,NaN,https://www.linkedin.com/jobs/view/4419260216,2026-06-13 14:18:21
285,Data Architect,linkedin,Associate SAP Human Capital Solutions Architec...,Sanlam,"Cape Town, Western Cape, South Africa",NaN,False,2026-06-01,NaN,NaN,NaN,NaN,NaN,https://www.linkedin.com/jobs/view/4418761846,2026-06-13 14:18:21
286,Data Architect,linkedin,Modeller - OLAP/Automation,Circana,"Cape Town, Western Cape, South Africa",NaN,False,2026-06-01,NaN,NaN,NaN,NaN,NaN,https://www.linkedin.com/jobs/view/4309510396,2026-06-13 14:18:21
287,Data Architect,linkedin,Senior Data Analyst,impact.com,"Cape Town, Western Cape, South Africa",NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,https://www.linkedin.com/jobs/view/4385026286,2026-06-13 14:18:21
288,Data Architect,linkedin,Product Manager - Group Data Platform,Sanlam,"Cape Town, Western Cape, South Africa",NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,https://www.linkedin.com/jobs/view/4387336441,2026-06-13 14:18:21

# Changing 'date_posted' data type to date-time format.

In [3]:
df['date_posted'] = pd.to_datetime(df['date_posted']).dt.date
df['date_posted']

0      2026-06-12
1      2026-06-12
2      2026-06-12
3      2026-06-12
4      2026-06-12
          ...
284    2026-06-02
285    2026-06-01
286    2026-06-01
287           NaT
288           NaT
Name: date_posted, Length: 289, dtype: object

# Replacing NaN values with 'Unknown'.

In [4]:
df = df.fillna('Unknown')
df

,search_role,site,title,company,location,job_type,is_remote,date_posted,min_amount,max_amount,currency,interval,description,job_url,scraped_at
0,Data Analyst,indeed,Claims Risk Analyst,Momentum Health,"Bellville, WC, ZA",Unknown,False,2026-06-12,Unknown,Unknown,Unknown,Unknown,**Introduction**\nThrough our client\-facing b...,https://za.indeed.com/viewjob?jk=1c27bef7a3d49dc1,2026-06-13 14:18:21
1,Data Analyst,indeed,Senior Application Support Analyst (SQL-focused),MRI Software,"Cape Town, WC, ZA",fulltime,False,2026-06-12,Unknown,Unknown,Unknown,Unknown,MRI Software is seeking a Senior Application S...,https://za.indeed.com/viewjob?jk=8fa3139aef3495e3,2026-06-13 14:18:21
2,Data Analyst,indeed,SOC Analyst,Zappi,"Cape Town, WC, ZA",fulltime,False,2026-06-12,Unknown,Unknown,Unknown,Unknown,### **Description**\n\n \n\nWe believe in hir...,https://za.indeed.com/viewjob?jk=80aeb6ac4d43e5d3,2026-06-13 14:18:21
3,Data Analyst,indeed,Chief Delivery Officer (CDO),NJ Placement Consulting,"Rosebank, WC, ZA",fulltime,False,2026-06-12,Unknown,Unknown,Unknown,Unknown,##### **Overview**\n\n\nAmazing chance to join...,https://za.indeed.com/viewjob?jk=7077c05a2c616941,2026-06-13 14:18:21
4,Data Analyst,indeed,Business Intelligence Analyst,LekkeSlaap,"Cape Town, WC, ZA",fulltime,True,2026-06-12,Unknown,Unknown,Unknown,Unknown,Bring 3\+ years of proven experience in busine...,https://za.indeed.com/viewjob?jk=dd0f358d23d62da8,2026-06-13 14:18:21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284,Data Architect,linkedin,Lead Data Scientist,Network Recruitment,"City of Cape Town, Western Cape, South Africa",Unknown,False,2026-06-02,Unknown,Unknown,Unknown,Unknown,Unknown,https://www.linkedin.com/jobs/view/4419260216,2026-06-13 14:18:21
285,Data Architect,linkedin,Associate SAP Human Capital Solutions Architec...,Sanlam,"Cape Town, Western Cape, South Africa",Unknown,False,2026-06-01,Unknown,Unknown,Unknown,Unknown,Unknown,https://www.linkedin.com/jobs/view/4418761846,2026-06-13 14:18:21
286,Data Architect,linkedin,Modeller - OLAP/Automation,Circana,"Cape Town, Western Cape, South Africa",Unknown,False,2026-06-01,Unknown,Unknown,Unknown,Unknown,Unknown,https://www.linkedin.com/jobs/view/4309510396,2026-06-13 14:18:21
287,Data Architect,linkedin,Senior Data Analyst,impact.com,"Cape Town, Western Cape, South Africa",Unknown,False,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,https://www.linkedin.com/jobs/view/4385026286,2026-06-13 14:18:21
288,Data Architect,linkedin,Product Manager - Group Data Platform,Sanlam,"Cape Town, Western Cape, South Africa",Unknown,False,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,https://www.linkedin.com/jobs/view/4387336441,2026-06-13 14:18:21

# Dropping columns with no values.

In [5]:
df = df.drop(columns=['min_amount' ,'max_amount','currency','interval', 'job_url', 'scraped_at'])
df

,search_role,site,title,company,location,job_type,is_remote,date_posted,description
0,Data Analyst,indeed,Claims Risk Analyst,Momentum Health,"Bellville, WC, ZA",Unknown,False,2026-06-12,**Introduction**\nThrough our client\-facing b...
1,Data Analyst,indeed,Senior Application Support Analyst (SQL-focused),MRI Software,"Cape Town, WC, ZA",fulltime,False,2026-06-12,MRI Software is seeking a Senior Application S...
2,Data Analyst,indeed,SOC Analyst,Zappi,"Cape Town, WC, ZA",fulltime,False,2026-06-12,### **Description**\n\n \n\nWe believe in hir...
3,Data Analyst,indeed,Chief Delivery Officer (CDO),NJ Placement Consulting,"Rosebank, WC, ZA",fulltime,False,2026-06-12,##### **Overview**\n\n\nAmazing chance to join...
4,Data Analyst,indeed,Business Intelligence Analyst,LekkeSlaap,"Cape Town, WC, ZA",fulltime,True,2026-06-12,Bring 3\+ years of proven experience in busine...
...,...,...,...,...,...,...,...,...,...
284,Data Architect,linkedin,Lead Data Scientist,Network Recruitment,"City of Cape Town, Western Cape, South Africa",Unknown,False,2026-06-02,Unknown
285,Data Architect,linkedin,Associate SAP Human Capital Solutions Architec...,Sanlam,"Cape Town, Western Cape, South Africa",Unknown,False,2026-06-01,Unknown
286,Data Architect,linkedin,Modeller - OLAP/Automation,Circana,"Cape Town, Western Cape, South Africa",Unknown,False,2026-06-01,Unknown
287,Data Architect,linkedin,Senior Data Analyst,impact.com,"Cape Town, Western Cape, South Africa",Unknown,False,Unknown,Unknown
288,Data Architect,linkedin,Product Manager - Group Data Platform,Sanlam,"Cape Town, Western Cape, South Africa",Unknown,False,Unknown,Unknown

# Cleaning Locations.

### I notice there is location inconsistencies. For e.g. 3 different ways of telling it's in 'Cape Town'.

In [6]:
df.location.value_counts()

location
Cape Town, Western Cape, South Africa            115
Cape Town, WC, ZA                                 80
City of Cape Town, Western Cape, South Africa     38
Stellenbosch, Western Cape, South Africa          12
Bellville, WC, ZA                                  4
Stellenbosch, WC, ZA                               4
Somerset West, WC, ZA                              3
Milnerton, WC, ZA                                  3
Brackenfell, WC, ZA                                3
Bellville, Western Cape, South Africa              3
Century City, WC, ZA                               3
Pinelands, Western Cape, South Africa              2
Claremont, WC, ZA                                  2
Rosebank, WC, ZA                                   1
Nuweland, WC, ZA                                   1
Wynberg, WC, ZA                                    1
Southern Suburbs, WC, ZA                           1
Goodwood, WC, ZA                                   1
Sea Point, WC, ZA                                  1
Durbanville, Western Cape, South Africa            1
Blackheath, WC, ZA                                 1
Rondebosch, WC, ZA                                 1
Somerset West, Western Cape, South Africa          1
Paarl, WC, ZA                                      1
Darling, Western Cape, South Africa                1
Brackenfell, Western Cape, South Africa            1
Durbanville, WC, ZA                                1
Kenilworth, WC, ZA                                 1
Northern Suburbs, WC, ZA                           1
Tygervalley, WC, ZA                                1
Name: count, dtype: int64

### First, I'm splitting and selecting the first values as this is the only data we need. (Everything is based already in WC/Western Cape ZA)

In [7]:
df['Location'] = df['location'].apply(lambda x: x.split(',')[0])
df['Location'].value_counts()

Location
Cape Town            195
City of Cape Town     38
Stellenbosch          16
Bellville              7
Somerset West          4
Brackenfell            4
Milnerton              3
Century City           3
Durbanville            2
Pinelands              2
Claremont              2
Rosebank               1
Nuweland               1
Wynberg                1
Southern Suburbs       1
Goodwood               1
Sea Point              1
Blackheath             1
Rondebosch             1
Paarl                  1
Darling                1
Kenilworth             1
Northern Suburbs       1
Tygervalley            1
Name: count, dtype: int64

### Some locations are suburbs of Cape Town.

In [8]:
suburbs_ct = {'Bellville': 'Cape Town', 'Somerset West': 'Cape Town', 'Brackenfell': 'Cape Town',
    'Milnerton': 'Cape Town', 'Century City': 'Cape Town', 'Durbanville': 'Cape Town',
    'Pinelands': 'Cape Town', 'Claremont': 'Cape Town', 'Rosebank': 'Cape Town',
    'Nuweland': 'Cape Town', 'Wynberg': 'Cape Town', 'Southern Suburbs': 'Cape Town',
    'Goodwood': 'Cape Town', 'Sea Point': 'Cape Town', 'Blackheath': 'Cape Town',
    'Rondebosch': 'Cape Town', 'Kenilworth': 'Cape Town', 'Northern Suburbs': 'Cape Town',
    'Tygervalley': 'Cape Town', 'City of Cape Town': 'Cape Town'}
df['City'] = df['Location'].replace(suburbs_ct).sort_index()
df.City.value_counts()

City
Cape Town       271
Stellenbosch     16
Paarl             1
Darling           1
Name: count, dtype: int64

In [9]:
pd.set_option('display.max_rows', None) # I want to view the FULL dataframe.
df

,search_role,site,title,company,location,job_type,is_remote,date_posted,description,Location,City
0,Data Analyst,indeed,Claims Risk Analyst,Momentum Health,"Bellville, WC, ZA",Unknown,False,2026-06-12,**Introduction**\nThrough our client\-facing b...,Bellville,Cape Town
1,Data Analyst,indeed,Senior Application Support Analyst (SQL-focused),MRI Software,"Cape Town, WC, ZA",fulltime,False,2026-06-12,MRI Software is seeking a Senior Application S...,Cape Town,Cape Town
2,Data Analyst,indeed,SOC Analyst,Zappi,"Cape Town, WC, ZA",fulltime,False,2026-06-12,### **Description**\n\n \n\nWe believe in hir...,Cape Town,Cape Town
3,Data Analyst,indeed,Chief Delivery Officer (CDO),NJ Placement Consulting,"Rosebank, WC, ZA",fulltime,False,2026-06-12,##### **Overview**\n\n\nAmazing chance to join...,Rosebank,Cape Town
4,Data Analyst,indeed,Business Intelligence Analyst,LekkeSlaap,"Cape Town, WC, ZA",fulltime,True,2026-06-12,Bring 3\+ years of proven experience in busine...,Cape Town,Cape Town
5,Data Analyst,indeed,Technical Product Analyst,Sanlam,"Bellville, WC, ZA",Unknown,False,2026-06-12,**Who are we?**\n\nSanlam Life and Savings (SL...,Bellville,Cape Town
6,Data Analyst,indeed,Utilities Analyst,FPG Property Management,"Cape Town, WC, ZA",fulltime,False,2026-06-12,**PURPOSE OF JOB**\n\nThe Utilities Analyst is...,Cape Town,Cape Town
7,Data Analyst,indeed,Data Integrations Specialist - Client Focus,Healix Group of Companies,"Cape Town, WC, ZA",fulltime,False,2026-06-12,### **About the role**\n\n\nWe’re looking for ...,Cape Town,Cape Town
8,Data Analyst,indeed,Senior BI Analyst - Team Leader,Auto Trader South Africa,"Nuweland, WC, ZA",Unknown,True,2026-06-12,**Senior BI Analyst \- Team Leader**\n========...,Nuweland,Cape Town
9,Data Analyst,indeed,Domain / Product owner - HR systems,Unifi,"Stellenbosch, WC, ZA",Unknown,False,2026-06-12,**About Unifi**\n\n***Boldly different. Fierce...,Stellenbosch,Stellenbosch
10,Data Analyst,indeed,Data Analyst,Crisis24,"Cape Town, WC, ZA",fulltime,False,2026-06-11,Who We Are Looking For\n \n \n\nThe Data Ana...,Cape Town,Cape Town
11,Data Analyst,indeed,Customer Success Reporting Analyst,Mama Money,"Cape Town, WC, ZA",fulltime,False,2026-06-11,**Who we are:**\n\n\n\nMama Money is a growth\...,Cape Town,Cape Town
12,Data Analyst,indeed,Legal Content Analyst,RELX Group,"Cape Town, WC, ZA",fulltime,False,2026-06-11,"**Are you passionate about shaping accurate, t...",Cape Town,Cape Town
13,Data Analyst,indeed,Legal Content Analyst,LexisNexis Legal & Professional,"Cape Town, WC, ZA",fulltime,False,2026-06-11,"**Are you passionate about shaping accurate, t...",Cape Town,Cape Town
14,Data Analyst,indeed,Business Intelligence Analyst,Queenspark Pty Ltd,"Wynberg, WC, ZA",fulltime,False,2026-06-11,**Title:** Business Intelligence Analyst\n\n**...,Wynberg,Cape Town
15,Data Analyst,indeed,Conflict Analyst,Frontline Managed Services,"Cape Town, WC, ZA",Unknown,False,2026-06-10,Welcome to Frontline Managed Services® – where...,Cape Town,Cape Town
16,Data Analyst,indeed,Paid Media Analyst,Clever Profits,"Cape Town, WC, ZA",fulltime,True,2026-06-10,**Description** \n\nCleverProfits is a financ...,Cape Town,Cape Town
17,Data Analyst,indeed,Supply Chain Process Analyst,woolworths,"Cape Town, WC, ZA",Unknown,False,2026-06-10,### **Job Advert Summary**\n\n\nJoin Woolworth...,Cape Town,Cape Town
18,Data Analyst,indeed,BUSINESS ANALYST (INDUSTRIAL ENGINEER),Cartrack SA,"Cape Town, WC, ZA",Unknown,False,2026-06-10,**Listing reference:** cartr\_000815\n**Listin...,Cape Town,Cape Town
19,Data Analyst,indeed,"Manager, Grade 1: Spatial Analyst",South African National Biodiversity Institute,"Cape Town, WC, ZA",Unknown,False,2026-06-10,"**Manager, Grade 1: Spatial Analyst**\n\n**Sal...",Cape Town,Cape Town
20,Data Analyst,indeed,Integration Engineer/Developer,Cape Union Mart,"Cape Town, WC, ZA",Unknown,False,2026-06-10,**Why Join Cape Union Mart?**\n\n\nCape Union ...,Cape Town,Cape Town
21,Data Analyst,indeed,"Insight Analyst (Professional, BI Specialist (...",Concentrix,"Cape Town, WC, ZA",fulltime,False,2026-06-09,**JOB PURPOSE**\n\nTo support the development ...,Cape Town,Cape Town
22,Data Analyst,indeed,Investment Guidelines Analyst (Contractor),Futuregrowth,"Southern Suburbs, WC, ZA",parttime,False,2026-06-09,**Purpose of the position**\n\n\n\nA vacancy h...,Southern Suburbs,Cape Town
23,Data Analyst,indeed,FinOps Analyst,Yoco,"Cape Town, WC, ZA",Unknown,False,2026-06-09,### **Who we are**\n\n\nYoco was founded in 20...,Cape Town,Cape Town
24,Data Analyst,indeed,Databricks Data Engineer,Confluent,"Cape Town, WC, ZA",Unknown,False,2026-06-09,**Position: Data Engineer \- Intermediate** \...,Cape Town,Cape Town
25,Data Analyst,indeed,FinOps Analyst,Yoco Technologies,"Cape Town, WC, ZA",fulltime,False,2026-06-09,### **Who we are**\n\n\nYoco was founded in 20...,Cape Town,Cape Town
26,Data Analyst,indeed,Commercial Finance Business Analyst,Avery Dennison,"Somerset West, WC, ZA",fulltime,False,2026-06-09,**Company Description** **ABOUT AVERY DENNISON...,Somerset West,Cape Town
27,Data Analyst,indeed,Quality Analyst,Stowe Holdings (Pty) Ltd.,"Goodwood, WC, ZA",fulltime,False,2026-06-09,"**Please note, this is a non\-technical role i...",Goodwood,Cape Town
28,Data Analyst,indeed,"WIM Investigator II, AmSec Workplace Incident ...",Amazon.com,"Cape Town, WC, ZA",fulltime,False,2026-06-08,**DESCRIPTION**\n---------------\n\n\nThe Work...,Cape Town,Cape Town
29,Data Analyst,indeed,Supply Chain Analyst,The HEINEKEN Company,"Stellenbosch, WC, ZA",fulltime,False,2026-06-08,* Purpose of the job\n\n\n\n\|\n\n\nBe a first...,Stellenbosch,Stellenbosch
30,Data Analyst,indeed,Data Management Analyst,MRI Software,"Cape Town, WC, ZA",fulltime,False,2026-06-08,**Position Overview:**\n\n\nWe are looking for...,Cape Town,Cape Town
31,Data Analyst,indeed,Junior Credit Risk Analyst,Weaver Fintech Ltd,"Cape Town, WC, ZA",Unknown,False,2026-06-08,Weaver FinTech Group is a leading digital fina...,Cape Town,Cape Town
32,Data Analyst,indeed,Sales Analyst (6 Month Contract),Kenvue,"Cape Town, WC, ZA",Unknown,False,2026-06-08,Kenvue is currently recruiting for a:\n\n\nSal...,Cape Town,Cape Town
33,Data Analyst,indeed,CRM & Data Analyst,Networking Mania,"Sea Point, WC, ZA",Unknown,False,2026-06-08,Job Title: CRM \& Data Analyst\n\nLocation: Ca...,Sea Point,Cape Town
34,Data Analyst,indeed,Realtime Analyst,WNS Global Services,"Milnerton, WC, ZA",fulltime,False,2026-06-08,"**Company Description** \n\nWNS, part of Capg...",Milnerton,Cape Town
35,Data Analyst,indeed,Yield Analyst,LE BOAT,"Cape Town, WC, ZA",fulltime,False,2026-06-05,"**Le Boat, part of the Travelopia group**, is ...",Cape Town,Cape Town
36,Data Analyst,indeed,Quality Analyst - Financial Services - Onsite ...,Concentrix,"Cape Town, WC, ZA",fulltime,False,2026-06-04,"**Quality Analyst – On\-site, Cape Town** \n\...",Cape Town,Cape Town
37,Data Analyst,indeed,Senior Retail Media Insights Analyst,ShopriteX,"Brackenfell, WC, ZA",fulltime,False,2026-06-01,**Senior Retail Media Insights Analyst**\n\n\n...,Brackenfell,Cape Town
38,Data Analyst,indeed,Digital Data Analyst (Rainmaker Media),ShopriteX,"Brackenfell, WC, ZA",fulltime,False,2026-06-01,**Value Proposition**\n\n\nPowered by Africa's...,Brackenfell,Cape Town
39,Data Analyst,indeed,Business Process Analyst,Lula,"Cape Town, WC, ZA",fulltime,False,2026-06-01,We are looking for a collaborative mid\-level ...,Cape Town,Cape Town
40,Data Analyst,linkedin,Data Analyst,ExecutivePlacements.com,"Cape Town, Western Cape, South Africa",Unknown,False,2026-06-12,Unknown,Cape Town,Cape Town
41,Data Analyst,linkedin,Business Intelligence Analyst (Retail) - Corpo...,Trending Talent Solutions,"City of Cape Town, Western Cape, South Africa",Unknown,False,2026-06-12,Unknown,City of Cape Town,Cape Town
42,Data Analyst,linkedin,Data Engineer (Senior),Parvana,"Bellville, Western Cape, South Africa",Unknown,False,2026-06-12,Unknown,Bellville,Cape Town
43,Data Analyst,linkedin,Applied Research Engineer,Duku AI,"Cape Town, Western Cape, South Africa",Unknown,False,2026-06-12,Unknown,Cape Town,Cape Town
44,Data Analyst,linkedin,Senior Data Analyst,Capitec,"Stellenbosch, Western Cape, South Africa",Unknown,False,2026-06-11,Unknown,Stellenbosch,Stellenbosch
45,Data Analyst,linkedin,BI Analyst,ExecutivePlacements.com,"Cape Town, Western Cape, South Africa",Unknown,False,2026-06-11,Unknown,Cape Town,Cape Town
46,Data Analyst,linkedin,Collections and Payments Analytics Specialist ...,Black Pen Recruitment,"City of Cape Town, Western Cape, South Africa",Unknown,False,2026-06-11,Unknown,City of Cape Town,Cape Town
47,Data Analyst,linkedin,Data Analyst,Network Recruitment,"Stellenbosch, Western Cape, South Africa",Unknown,False,2026-06-10,Unknown,Stellenbosch,Stellenbosch
48,Data Analyst,linkedin,Business Intelligence Analyst,Communicate Recruitment,"City of Cape Town, Western Cape, South Africa",Unknown,False,2026-06-10,Unknown,City of Cape Town,Cape Town
49,Data Analyst,linkedin,Business Intelligence Analyst,Network Recruitment,"City of Cape Town, Western Cape, South Africa",Unknown,False,2026-06-10,Unknown,City of Cape Town,Cape Town
50,Data Analyst,linkedin,Senior Space Analyst,Woolworths,"Cape Town, Western Cape, South Africa",Unknown,False,2026-06-10,Unknown,Cape Town,Cape Town
51,Data Analyst,linkedin,Data Analyst,Network International,"Cape Town, Western Cape, South Africa",Unknown,False,2026-06-09,Unknown,Cape Town,Cape Town
52,Data Analyst,linkedin,Market Research Data Analyst,Potentiam Ltd,"City of Cape Town, Western Cape, South Africa",Unknown,False,2026-06-09,Unknown,City of Cape Town,Cape Town
53,Data Analyst,linkedin,"Data Analyst (Marketing Analytics, Bangkok Bas...",Agoda,"Cape Town, Western Cape, South Africa",Unknown,False,2026-06-09,Unknown,Cape Town,Cape Town
54,Data Analyst,linkedin,Data Engineer - Databricks - July Start,Embelo,"City of Cape Town, Western Cape, South Africa",Unknown,False,2026-06-08,Unknown,City of Cape Town,Cape Town
55,Data Analyst,linkedin,Fundraising Systems and Data Specialist (m/f/d),FOUR PAWS,"City of Cape Town, Western Cape, South Africa",Unknown,False,2026-06-08,Unknown,City of Cape Town,Cape Town
56,Data Analyst,linkedin,Data Analyst,DigiOutsource,"Cape Town, Western Cape, South Africa",Unknown,False,2026-06-07,Unknown,Cape Town,Cape Town
57,Data Analyst,linkedin,Junior Data Engineer,ExecutivePlacements.com,"Cape Town, Western Cape, South Africa",Unknown,False,2026-06-07,Unknown,Cape Town,Cape Town
58,Data Analyst,linkedin,Business Data Analyst,ExecutivePlacements.com,"Cape Town, Western Cape, South Africa",Unknown,False,2026-06-06,Unknown,Cape Town,Cape Town
59,Data Analyst,linkedin,Data & Insights Analyst,Vivo Energy,"Cape Town, Western Cape, South Africa",Unknown,False,2026-06-05,Unknown,Cape Town,Cape Town
60,Data Analyst,linkedin,Yield Analyst,Le Boat,"Cape Town, Western Cape, South Africa",Unknown,False,2026-06-05,Unknown,Cape Town,Cape Town
61,Data Analyst,linkedin,Dashboard & Reporting Specialist,Hunterlodge Advertising,"City of Cape Town, Western Cape, South Africa",Unknown,False,2026-06-05,Unknown,City of Cape Town,Cape Town
62,Data Analyst,linkedin,Director: Provincial Spatial Information (Ref ...,Western Cape Government,"Cape Town, Western Cape, South Africa",Unknown,False,2026-06-05,Unknown,Cape Town,Cape Town
63,Data Analyst,linkedin,Senior Insights Manager,Mr D,"City of Cape Town, Western Cape, South Africa",Unknown,False,2026-06-05,Unknown,City of Cape Town,Cape Town
64,Data Analyst,linkedin,Data Engineer,Communicate Recruitment,"City of Cape Town, Western Cape, South Africa",Unknown,False,2026-06-04,Unknown,City of Cape Town,Cape Town
65,Data Analyst,linkedin,Business Intelligence Developer,DigiOutsource,"Cape Town, Western Cape, South Africa",Unknown,False,2026-06-03,Unknown,Cape Town,Cape Town
66,Data Analyst,linkedin,Quantitative Analyst,Capitec,"Stellenbosch, Western Cape, South Africa",Unknown,False,2026-06-03,Unknown,Stellenbosch,Stellenbosch
67,Data Analyst,linkedin,Senior Data Engineer,KingMakers,"Cape Town, Western Cape, South Africa",Unknown,False,2026-06-03,Unknown,Cape Town,Cape Town
68,Data Analyst,linkedin,Client Reporting Analyst (12-month contract) –...,ExecutivePlacements.com,"Cape Town, Western Cape, South Africa",Unknown,False,2026-06-03,Unknown,Cape Town,Cape Town
69,Data Analyst,linkedin,Remote Data/Image Collector (No Experience Nee...,TransPerfect,"City of Cape Town, Western Cape, South Africa",Unknown,True,2026-06-02,Unknown,City of Cape Town,Cape Town
70,Data Analyst,linkedin,Revenue Analysis & Performance Leader,Apex Group Ltd,"Cape Town, Western Cape, South Africa",Unknown,False,2026-06-02,Unknown,Cape Town,Cape Town
71,Data Analyst,linkedin,Data Analyst II_Pipeline,Capitec,"Stellenbosch, Western Cape, South Africa",Unknown,False,2026-06-01,Unknown,Stellenbosch,Stellenbosch
72,Data Analyst,linkedin,SAf Software Developer,SMEC (an SJ Group company),"Cape Town, Western Cape, South Africa",Unknown,False,Unknown,Unknown,Cape Town,Cape Town
73,Data Analyst,linkedin,Senior Collections Specialist (Business Intell...,Network Recruitment International,"City of Cape Town, Western Cape, South Africa",Unknown,False,Unknown,Unknown,City of Cape Town,Cape Town
74,Data Analyst,linkedin,Senior Onboarding Analyst,BVNK,"Cape Town, Western Cape, South Africa",Unknown,False,Unknown,Unknown,Cape Town,Cape Town
75,Data Scientist,indeed,CapeNature – SANCCOB Marine Field Ranger,SANCCOB,"Cape Town, WC, ZA","parttime, fulltime",False,2026-06-12,The Southern African Foundation for the Conser...,Cape Town,Cape Town
76,Data Scientist,indeed,SANCCOB Coastal Field Ranger,SANCCOB,"Cape Town, WC, ZA","parttime, fulltime",False,2026-06-05,SANCCOB seeks to employ a full\-time Coastal F...,Cape Town,Cape Town
77,Data Scientist,indeed,Platform Data Engineer,Confluent,"Cape Town, WC, ZA",Unknown,False,2026-06-02,Platform Data Engineer \n\n \n\n(**Hybrid/Pi...,Cape Town,Cape Town
78,Data Scientist,indeed,Data Scientist,PBT Group,"Stellenbosch, WC, ZA",Unknown,False,2026-06-01,##### **Employment Type**\n\n\nContract\n#####...,Stellenbosch,Stellenbosch
79,Data Scientist,linkedin,Machine Learning Engineer,Duku AI,"Cape Town, Western Cape, South Africa",Unknown,False,2026-06-12,Unknown,Cape Town,Cape Town
80,Data Scientist,linkedin,AI Engineer,GVW Group,"Durbanville, Western Cape, South Africa",Unknown,False,2026-06-12,Unknown,Durbanville,Cape Town
81,Data Scientist,linkedin,Software Engineer (Front-End),DigiOutsource,"Cape Town, Western Cape, South Africa",Unknown,False,2026-06-12,Unknown,Cape Town,Cape Town
82,Data Scientist,linkedin,Software Engineer (Full Stack),DigiOutsource,"Cape Town, Western Cape, South Africa",Unknown,False,2026-06-12,Unknown,Cape Town,Cape Town
83,Data Scientist,linkedin,Junior Planning Analytics (TM1) Developer,DigiOutsource,"Cape Town, Western Cape, South Africa",Unknown,False,2026-06-12,Unknown,Cape Town,Cape Town
84,Data Scientist,linkedin,"Intermediate Data Scientist - Cape Town, Hybrid",Ada Meher,"City of Cape Town, Western Cape, South Africa",Unknown,False,2026-06-11,Unknown,City of Cape Town,Cape Town
85,Data Scientist,linkedin,Senior Data Engineer,Keyrock,"Cape Town, Western Cape, South Africa",Unknown,False,2026-06-11,Unknown,Cape Town,Cape Town
86,Data Scientist,linkedin,Analytics Engineer,Pargo,"Cape Town, Western Cape, South Africa",Unknown,False,2026-06-10,Unknown,Cape Town,Cape Town
87,Data Scientist,linkedin,Actuarial Specialist,Outsized,"City of Cape Town, Western Cape, South Africa",Unknown,False,2026-06-10,Unknown,City of Cape Town,Cape Town
88,Data Scientist,linkedin,Data Scientist (Pipeline),Capita,"Cape Town, Western Cape, South Africa",Unknown,False,2026-06-09,Unknown,Cape Town,Cape Town
89,Data Scientist,linkedin,Specialist Data Scientist,Old Mutual South Africa,"Pinelands, Western Cape, South Africa",Unknown,False,2026-06-09,Unknown,Pinelands,Cape Town
90,Data Scientist,linkedin,Senior Credit Risk Data Scientist,Oze,"City of Cape Town, Western Cape, South Africa",Unknown,False,2026-06-09,Unknown,City of Cape Town,Cape Town
91,Data Scientist,linkedin,Manager: Data and Analytics,Capitec,"Cape Town, Western Cape, South Africa",Unknown,False,2026-06-09,Unknown,Cape Town,Cape Town
92,Data Scientist,linkedin,Senior Test Engineer,Ozow,"Cape Town, Western Cape, South Africa",Unknown,False,2026-06-09,Unknown,Cape Town,Cape Town
93,Data Scientist,linkedin,Xperts: Senior Java Engineer (Data Engineering),Inspired Testing,"Cape Town, Western Cape, South Africa",Unknown,False,2026-06-08,Unknown,Cape Town,Cape Town
94,Data Scientist,linkedin,DevSecOps Engineer - Cape Town,Morae,"City of Cape Town, Western Cape, South Africa",Unknown,False,2026-06-08,Unknown,City of Cape Town,Cape Town
95,Data Scientist,linkedin,Principal Engineer,takealot.com,"Cape Town, Western Cape, South Africa",Unknown,False,2026-06-08,Unknown,Cape Town,Cape Town
96,Data Scientist,linkedin,Senior Data / ML Engineer,Powerfleet,"Cape Town, Western Cape, South Africa",Unknown,False,2026-06-07,Unknown,Cape Town,Cape Town
97,Data Scientist,linkedin,AI Data Platform Engineer,Storyteq,"Cape Town, Western Cape, South Africa",Unknown,False,2026-06-07,Unknown,Cape Town,Cape Town
98,Data Scientist,linkedin,QA Engineer,ExecutivePlacements.com,"Cape Town, Western Cape, South Africa",Unknown,False,2026-06-06,Unknown,Cape Town,Cape Town
99,Data Scientist,linkedin,BI Engineer: Takealot Group,takealot.com,"Cape Town, Western Cape, South Africa",Unknown,False,2026-06-04,Unknown,Cape Town,Cape Town
100,Data Scientist,linkedin,Software Engineer,ExecutivePlacements.com,"Cape Town, Western Cape, South Africa",Unknown,False,2026-06-04,Unknown,Cape Town,Cape Town
101,Data Scientist,linkedin,Data Scientist,ExecutivePlacements.com,"Stellenbosch, Western Cape, South Africa",Unknown,False,2026-06-02,Unknown,Stellenbosch,Stellenbosch
102,Data Scientist,linkedin,Research Development Engineer: Innovation (Int...,Clickatell,"Cape Town, Western Cape, South Africa",Unknown,False,2026-06-02,Unknown,Cape Town,Cape Town
103,Data Scientist,linkedin,AI ENGINEER – REMOTE (CAPE TOWN),SASSO CONSULTING,"Cape Town, Western Cape, South Africa",Unknown,True,2026-06-02,Unknown,Cape Town,Cape Town
104,Data Scientist,linkedin,Senior Engineer,Salt,"City of Cape Town, Western Cape, South Africa",Unknown,False,2026-06-02,Unknown,City of Cape Town,Cape Town
105,Data Scientist,linkedin,Machine Learning Engineer,Sanlam,"Cape Town, Western Cape, South Africa",Unknown,False,2026-06-01,Unknown,Cape Town,Cape Town
106,Data Scientist,linkedin,Quantitative Analyst,Communicate Recruitment,"City of Cape Town, Western Cape, South Africa",Unknown,False,2026-06-01,Unknown,City of Cape Town,Cape Town
107,Data Scientist,linkedin,Data Engineer - L3,Advania UK,"Cape Town, Western Cape, South Africa",Unknown,False,Unknown,Unknown,Cape Town,Cape Town
108,Data Engineer,indeed,Technical Support Engineer,Root Platform,"Cape Town, WC, ZA",Unknown,False,2026-06-12,**Mission**\n-----------\n\n**As a Technical S...,Cape Town,Cape Town
109,Data Engineer,indeed,Senior Software Engineer (Full-Stack),Betway Group,"Cape Town, WC, ZA",fulltime,False,2026-06-12,Kick\-start your career in the online gaming w...,Cape Town,Cape Town
110,Data Engineer,indeed,Software Development Engineer – 2026,Amazon.com,"Cape Town, WC, ZA",fulltime,False,2026-06-12,**DESCRIPTION**\n---------------\n\n\nDo you w...,Cape Town,Cape Town
111,Data Engineer,indeed,"Chief Engineer, DCEO",Amazon.com,"Cape Town, WC, ZA",fulltime,False,2026-06-12,**DESCRIPTION**\n---------------\n\n\nAWS Data...,Cape Town,Cape Town
112,Data Engineer,indeed,Data Engineer,COLLINSON,"Cape Town, WC, ZA",Unknown,False,2026-06-11,"Collinson is the global, privately\-owned comp...",Cape Town,Cape Town
113,Data Engineer,indeed,Handyman - Protea Hotel by Marriott Breakwater...,Marriott International,"Cape Town, WC, ZA",fulltime,True,2026-06-11,**Additional Information** \n\n**Job Number**...,Cape Town,Cape Town

### After confirming the locations, I drop the unformatted 'location' column.

In [10]:
df = df.drop(columns='location')
df

,search_role,site,title,company,job_type,is_remote,date_posted,description,Location,City
0,Data Analyst,indeed,Claims Risk Analyst,Momentum Health,Unknown,False,2026-06-12,**Introduction**\nThrough our client\-facing b...,Bellville,Cape Town
1,Data Analyst,indeed,Senior Application Support Analyst (SQL-focused),MRI Software,fulltime,False,2026-06-12,MRI Software is seeking a Senior Application S...,Cape Town,Cape Town
2,Data Analyst,indeed,SOC Analyst,Zappi,fulltime,False,2026-06-12,### **Description**\n\n \n\nWe believe in hir...,Cape Town,Cape Town
3,Data Analyst,indeed,Chief Delivery Officer (CDO),NJ Placement Consulting,fulltime,False,2026-06-12,##### **Overview**\n\n\nAmazing chance to join...,Rosebank,Cape Town
4,Data Analyst,indeed,Business Intelligence Analyst,LekkeSlaap,fulltime,True,2026-06-12,Bring 3\+ years of proven experience in busine...,Cape Town,Cape Town
5,Data Analyst,indeed,Technical Product Analyst,Sanlam,Unknown,False,2026-06-12,**Who are we?**\n\nSanlam Life and Savings (SL...,Bellville,Cape Town
6,Data Analyst,indeed,Utilities Analyst,FPG Property Management,fulltime,False,2026-06-12,**PURPOSE OF JOB**\n\nThe Utilities Analyst is...,Cape Town,Cape Town
7,Data Analyst,indeed,Data Integrations Specialist - Client Focus,Healix Group of Companies,fulltime,False,2026-06-12,### **About the role**\n\n\nWe’re looking for ...,Cape Town,Cape Town
8,Data Analyst,indeed,Senior BI Analyst - Team Leader,Auto Trader South Africa,Unknown,True,2026-06-12,**Senior BI Analyst \- Team Leader**\n========...,Nuweland,Cape Town
9,Data Analyst,indeed,Domain / Product owner - HR systems,Unifi,Unknown,False,2026-06-12,**About Unifi**\n\n***Boldly different. Fierce...,Stellenbosch,Stellenbosch
10,Data Analyst,indeed,Data Analyst,Crisis24,fulltime,False,2026-06-11,Who We Are Looking For\n \n \n\nThe Data Ana...,Cape Town,Cape Town
11,Data Analyst,indeed,Customer Success Reporting Analyst,Mama Money,fulltime,False,2026-06-11,**Who we are:**\n\n\n\nMama Money is a growth\...,Cape Town,Cape Town
12,Data Analyst,indeed,Legal Content Analyst,RELX Group,fulltime,False,2026-06-11,"**Are you passionate about shaping accurate, t...",Cape Town,Cape Town
13,Data Analyst,indeed,Legal Content Analyst,LexisNexis Legal & Professional,fulltime,False,2026-06-11,"**Are you passionate about shaping accurate, t...",Cape Town,Cape Town
14,Data Analyst,indeed,Business Intelligence Analyst,Queenspark Pty Ltd,fulltime,False,2026-06-11,**Title:** Business Intelligence Analyst\n\n**...,Wynberg,Cape Town
15,Data Analyst,indeed,Conflict Analyst,Frontline Managed Services,Unknown,False,2026-06-10,Welcome to Frontline Managed Services® – where...,Cape Town,Cape Town
16,Data Analyst,indeed,Paid Media Analyst,Clever Profits,fulltime,True,2026-06-10,**Description** \n\nCleverProfits is a financ...,Cape Town,Cape Town
17,Data Analyst,indeed,Supply Chain Process Analyst,woolworths,Unknown,False,2026-06-10,### **Job Advert Summary**\n\n\nJoin Woolworth...,Cape Town,Cape Town
18,Data Analyst,indeed,BUSINESS ANALYST (INDUSTRIAL ENGINEER),Cartrack SA,Unknown,False,2026-06-10,**Listing reference:** cartr\_000815\n**Listin...,Cape Town,Cape Town
19,Data Analyst,indeed,"Manager, Grade 1: Spatial Analyst",South African National Biodiversity Institute,Unknown,False,2026-06-10,"**Manager, Grade 1: Spatial Analyst**\n\n**Sal...",Cape Town,Cape Town
20,Data Analyst,indeed,Integration Engineer/Developer,Cape Union Mart,Unknown,False,2026-06-10,**Why Join Cape Union Mart?**\n\n\nCape Union ...,Cape Town,Cape Town
21,Data Analyst,indeed,"Insight Analyst (Professional, BI Specialist (...",Concentrix,fulltime,False,2026-06-09,**JOB PURPOSE**\n\nTo support the development ...,Cape Town,Cape Town
22,Data Analyst,indeed,Investment Guidelines Analyst (Contractor),Futuregrowth,parttime,False,2026-06-09,**Purpose of the position**\n\n\n\nA vacancy h...,Southern Suburbs,Cape Town
23,Data Analyst,indeed,FinOps Analyst,Yoco,Unknown,False,2026-06-09,### **Who we are**\n\n\nYoco was founded in 20...,Cape Town,Cape Town
24,Data Analyst,indeed,Databricks Data Engineer,Confluent,Unknown,False,2026-06-09,**Position: Data Engineer \- Intermediate** \...,Cape Town,Cape Town
25,Data Analyst,indeed,FinOps Analyst,Yoco Technologies,fulltime,False,2026-06-09,### **Who we are**\n\n\nYoco was founded in 20...,Cape Town,Cape Town
26,Data Analyst,indeed,Commercial Finance Business Analyst,Avery Dennison,fulltime,False,2026-06-09,**Company Description** **ABOUT AVERY DENNISON...,Somerset West,Cape Town
27,Data Analyst,indeed,Quality Analyst,Stowe Holdings (Pty) Ltd.,fulltime,False,2026-06-09,"**Please note, this is a non\-technical role i...",Goodwood,Cape Town
28,Data Analyst,indeed,"WIM Investigator II, AmSec Workplace Incident ...",Amazon.com,fulltime,False,2026-06-08,**DESCRIPTION**\n---------------\n\n\nThe Work...,Cape Town,Cape Town
29,Data Analyst,indeed,Supply Chain Analyst,The HEINEKEN Company,fulltime,False,2026-06-08,* Purpose of the job\n\n\n\n\|\n\n\nBe a first...,Stellenbosch,Stellenbosch
30,Data Analyst,indeed,Data Management Analyst,MRI Software,fulltime,False,2026-06-08,**Position Overview:**\n\n\nWe are looking for...,Cape Town,Cape Town
31,Data Analyst,indeed,Junior Credit Risk Analyst,Weaver Fintech Ltd,Unknown,False,2026-06-08,Weaver FinTech Group is a leading digital fina...,Cape Town,Cape Town
32,Data Analyst,indeed,Sales Analyst (6 Month Contract),Kenvue,Unknown,False,2026-06-08,Kenvue is currently recruiting for a:\n\n\nSal...,Cape Town,Cape Town
33,Data Analyst,indeed,CRM & Data Analyst,Networking Mania,Unknown,False,2026-06-08,Job Title: CRM \& Data Analyst\n\nLocation: Ca...,Sea Point,Cape Town
34,Data Analyst,indeed,Realtime Analyst,WNS Global Services,fulltime,False,2026-06-08,"**Company Description** \n\nWNS, part of Capg...",Milnerton,Cape Town
35,Data Analyst,indeed,Yield Analyst,LE BOAT,fulltime,False,2026-06-05,"**Le Boat, part of the Travelopia group**, is ...",Cape Town,Cape Town
36,Data Analyst,indeed,Quality Analyst - Financial Services - Onsite ...,Concentrix,fulltime,False,2026-06-04,"**Quality Analyst – On\-site, Cape Town** \n\...",Cape Town,Cape Town
37,Data Analyst,indeed,Senior Retail Media Insights Analyst,ShopriteX,fulltime,False,2026-06-01,**Senior Retail Media Insights Analyst**\n\n\n...,Brackenfell,Cape Town
38,Data Analyst,indeed,Digital Data Analyst (Rainmaker Media),ShopriteX,fulltime,False,2026-06-01,**Value Proposition**\n\n\nPowered by Africa's...,Brackenfell,Cape Town
39,Data Analyst,indeed,Business Process Analyst,Lula,fulltime,False,2026-06-01,We are looking for a collaborative mid\-level ...,Cape Town,Cape Town
40,Data Analyst,linkedin,Data Analyst,ExecutivePlacements.com,Unknown,False,2026-06-12,Unknown,Cape Town,Cape Town
41,Data Analyst,linkedin,Business Intelligence Analyst (Retail) - Corpo...,Trending Talent Solutions,Unknown,False,2026-06-12,Unknown,City of Cape Town,Cape Town
42,Data Analyst,linkedin,Data Engineer (Senior),Parvana,Unknown,False,2026-06-12,Unknown,Bellville,Cape Town
43,Data Analyst,linkedin,Applied Research Engineer,Duku AI,Unknown,False,2026-06-12,Unknown,Cape Town,Cape Town
44,Data Analyst,linkedin,Senior Data Analyst,Capitec,Unknown,False,2026-06-11,Unknown,Stellenbosch,Stellenbosch
45,Data Analyst,linkedin,BI Analyst,ExecutivePlacements.com,Unknown,False,2026-06-11,Unknown,Cape Town,Cape Town
46,Data Analyst,linkedin,Collections and Payments Analytics Specialist ...,Black Pen Recruitment,Unknown,False,2026-06-11,Unknown,City of Cape Town,Cape Town
47,Data Analyst,linkedin,Data Analyst,Network Recruitment,Unknown,False,2026-06-10,Unknown,Stellenbosch,Stellenbosch
48,Data Analyst,linkedin,Business Intelligence Analyst,Communicate Recruitment,Unknown,False,2026-06-10,Unknown,City of Cape Town,Cape Town
49,Data Analyst,linkedin,Business Intelligence Analyst,Network Recruitment,Unknown,False,2026-06-10,Unknown,City of Cape Town,Cape Town
50,Data Analyst,linkedin,Senior Space Analyst,Woolworths,Unknown,False,2026-06-10,Unknown,Cape Town,Cape Town
51,Data Analyst,linkedin,Data Analyst,Network International,Unknown,False,2026-06-09,Unknown,Cape Town,Cape Town
52,Data Analyst,linkedin,Market Research Data Analyst,Potentiam Ltd,Unknown,False,2026-06-09,Unknown,City of Cape Town,Cape Town
53,Data Analyst,linkedin,"Data Analyst (Marketing Analytics, Bangkok Bas...",Agoda,Unknown,False,2026-06-09,Unknown,Cape Town,Cape Town
54,Data Analyst,linkedin,Data Engineer - Databricks - July Start,Embelo,Unknown,False,2026-06-08,Unknown,City of Cape Town,Cape Town
55,Data Analyst,linkedin,Fundraising Systems and Data Specialist (m/f/d),FOUR PAWS,Unknown,False,2026-06-08,Unknown,City of Cape Town,Cape Town
56,Data Analyst,linkedin,Data Analyst,DigiOutsource,Unknown,False,2026-06-07,Unknown,Cape Town,Cape Town
57,Data Analyst,linkedin,Junior Data Engineer,ExecutivePlacements.com,Unknown,False,2026-06-07,Unknown,Cape Town,Cape Town
58,Data Analyst,linkedin,Business Data Analyst,ExecutivePlacements.com,Unknown,False,2026-06-06,Unknown,Cape Town,Cape Town
59,Data Analyst,linkedin,Data & Insights Analyst,Vivo Energy,Unknown,False,2026-06-05,Unknown,Cape Town,Cape Town
60,Data Analyst,linkedin,Yield Analyst,Le Boat,Unknown,False,2026-06-05,Unknown,Cape Town,Cape Town
61,Data Analyst,linkedin,Dashboard & Reporting Specialist,Hunterlodge Advertising,Unknown,False,2026-06-05,Unknown,City of Cape Town,Cape Town
62,Data Analyst,linkedin,Director: Provincial Spatial Information (Ref ...,Western Cape Government,Unknown,False,2026-06-05,Unknown,Cape Town,Cape Town
63,Data Analyst,linkedin,Senior Insights Manager,Mr D,Unknown,False,2026-06-05,Unknown,City of Cape Town,Cape Town
64,Data Analyst,linkedin,Data Engineer,Communicate Recruitment,Unknown,False,2026-06-04,Unknown,City of Cape Town,Cape Town
65,Data Analyst,linkedin,Business Intelligence Developer,DigiOutsource,Unknown,False,2026-06-03,Unknown,Cape Town,Cape Town
66,Data Analyst,linkedin,Quantitative Analyst,Capitec,Unknown,False,2026-06-03,Unknown,Stellenbosch,Stellenbosch
67,Data Analyst,linkedin,Senior Data Engineer,KingMakers,Unknown,False,2026-06-03,Unknown,Cape Town,Cape Town
68,Data Analyst,linkedin,Client Reporting Analyst (12-month contract) –...,ExecutivePlacements.com,Unknown,False,2026-06-03,Unknown,Cape Town,Cape Town
69,Data Analyst,linkedin,Remote Data/Image Collector (No Experience Nee...,TransPerfect,Unknown,True,2026-06-02,Unknown,City of Cape Town,Cape Town
70,Data Analyst,linkedin,Revenue Analysis & Performance Leader,Apex Group Ltd,Unknown,False,2026-06-02,Unknown,Cape Town,Cape Town
71,Data Analyst,linkedin,Data Analyst II_Pipeline,Capitec,Unknown,False,2026-06-01,Unknown,Stellenbosch,Stellenbosch
72,Data Analyst,linkedin,SAf Software Developer,SMEC (an SJ Group company),Unknown,False,Unknown,Unknown,Cape Town,Cape Town
73,Data Analyst,linkedin,Senior Collections Specialist (Business Intell...,Network Recruitment International,Unknown,False,Unknown,Unknown,City of Cape Town,Cape Town
74,Data Analyst,linkedin,Senior Onboarding Analyst,BVNK,Unknown,False,Unknown,Unknown,Cape Town,Cape Town
75,Data Scientist,indeed,CapeNature – SANCCOB Marine Field Ranger,SANCCOB,"parttime, fulltime",False,2026-06-12,The Southern African Foundation for the Conser...,Cape Town,Cape Town
76,Data Scientist,indeed,SANCCOB Coastal Field Ranger,SANCCOB,"parttime, fulltime",False,2026-06-05,SANCCOB seeks to employ a full\-time Coastal F...,Cape Town,Cape Town
77,Data Scientist,indeed,Platform Data Engineer,Confluent,Unknown,False,2026-06-02,Platform Data Engineer \n\n \n\n(**Hybrid/Pi...,Cape Town,Cape Town
78,Data Scientist,indeed,Data Scientist,PBT Group,Unknown,False,2026-06-01,##### **Employment Type**\n\n\nContract\n#####...,Stellenbosch,Stellenbosch
79,Data Scientist,linkedin,Machine Learning Engineer,Duku AI,Unknown,False,2026-06-12,Unknown,Cape Town,Cape Town
80,Data Scientist,linkedin,AI Engineer,GVW Group,Unknown,False,2026-06-12,Unknown,Durbanville,Cape Town
81,Data Scientist,linkedin,Software Engineer (Front-End),DigiOutsource,Unknown,False,2026-06-12,Unknown,Cape Town,Cape Town
82,Data Scientist,linkedin,Software Engineer (Full Stack),DigiOutsource,Unknown,False,2026-06-12,Unknown,Cape Town,Cape Town
83,Data Scientist,linkedin,Junior Planning Analytics (TM1) Developer,DigiOutsource,Unknown,False,2026-06-12,Unknown,Cape Town,Cape Town
84,Data Scientist,linkedin,"Intermediate Data Scientist - Cape Town, Hybrid",Ada Meher,Unknown,False,2026-06-11,Unknown,City of Cape Town,Cape Town
85,Data Scientist,linkedin,Senior Data Engineer,Keyrock,Unknown,False,2026-06-11,Unknown,Cape Town,Cape Town
86,Data Scientist,linkedin,Analytics Engineer,Pargo,Unknown,False,2026-06-10,Unknown,Cape Town,Cape Town
87,Data Scientist,linkedin,Actuarial Specialist,Outsized,Unknown,False,2026-06-10,Unknown,City of Cape Town,Cape Town
88,Data Scientist,linkedin,Data Scientist (Pipeline),Capita,Unknown,False,2026-06-09,Unknown,Cape Town,Cape Town
89,Data Scientist,linkedin,Specialist Data Scientist,Old Mutual South Africa,Unknown,False,2026-06-09,Unknown,Pinelands,Cape Town
90,Data Scientist,linkedin,Senior Credit Risk Data Scientist,Oze,Unknown,False,2026-06-09,Unknown,City of Cape Town,Cape Town
91,Data Scientist,linkedin,Manager: Data and Analytics,Capitec,Unknown,False,2026-06-09,Unknown,Cape Town,Cape Town
92,Data Scientist,linkedin,Senior Test Engineer,Ozow,Unknown,False,2026-06-09,Unknown,Cape Town,Cape Town
93,Data Scientist,linkedin,Xperts: Senior Java Engineer (Data Engineering),Inspired Testing,Unknown,False,2026-06-08,Unknown,Cape Town,Cape Town
94,Data Scientist,linkedin,DevSecOps Engineer - Cape Town,Morae,Unknown,False,2026-06-08,Unknown,City of Cape Town,Cape Town
95,Data Scientist,linkedin,Principal Engineer,takealot.com,Unknown,False,2026-06-08,Unknown,Cape Town,Cape Town
96,Data Scientist,linkedin,Senior Data / ML Engineer,Powerfleet,Unknown,False,2026-06-07,Unknown,Cape Town,Cape Town
97,Data Scientist,linkedin,AI Data Platform Engineer,Storyteq,Unknown,False,2026-06-07,Unknown,Cape Town,Cape Town
98,Data Scientist,linkedin,QA Engineer,ExecutivePlacements.com,Unknown,False,2026-06-06,Unknown,Cape Town,Cape Town
99,Data Scientist,linkedin,BI Engineer: Takealot Group,takealot.com,Unknown,False,2026-06-04,Unknown,Cape Town,Cape Town
100,Data Scientist,linkedin,Software Engineer,ExecutivePlacements.com,Unknown,False,2026-06-04,Unknown,Cape Town,Cape Town
101,Data Scientist,linkedin,Data Scientist,ExecutivePlacements.com,Unknown,False,2026-06-02,Unknown,Stellenbosch,Stellenbosch
102,Data Scientist,linkedin,Research Development Engineer: Innovation (Int...,Clickatell,Unknown,False,2026-06-02,Unknown,Cape Town,Cape Town
103,Data Scientist,linkedin,AI ENGINEER – REMOTE (CAPE TOWN),SASSO CONSULTING,Unknown,True,2026-06-02,Unknown,Cape Town,Cape Town
104,Data Scientist,linkedin,Senior Engineer,Salt,Unknown,False,2026-06-02,Unknown,City of Cape Town,Cape Town
105,Data Scientist,linkedin,Machine Learning Engineer,Sanlam,Unknown,False,2026-06-01,Unknown,Cape Town,Cape Town
106,Data Scientist,linkedin,Quantitative Analyst,Communicate Recruitment,Unknown,False,2026-06-01,Unknown,City of Cape Town,Cape Town
107,Data Scientist,linkedin,Data Engineer - L3,Advania UK,Unknown,False,Unknown,Unknown,Cape Town,Cape Town
108,Data Engineer,indeed,Technical Support Engineer,Root Platform,Unknown,False,2026-06-12,**Mission**\n-----------\n\n**As a Technical S...,Cape Town,Cape Town
109,Data Engineer,indeed,Senior Software Engineer (Full-Stack),Betway Group,fulltime,False,2026-06-12,Kick\-start your career in the online gaming w...,Cape Town,Cape Town
110,Data Engineer,indeed,Software Development Engineer – 2026,Amazon.com,fulltime,False,2026-06-12,**DESCRIPTION**\n---------------\n\n\nDo you w...,Cape Town,Cape Town
111,Data Engineer,indeed,"Chief Engineer, DCEO",Amazon.com,fulltime,False,2026-06-12,**DESCRIPTION**\n---------------\n\n\nAWS Data...,Cape Town,Cape Town
112,Data Engineer,indeed,Data Engineer,COLLINSON,Unknown,False,2026-06-11,"Collinson is the global, privately\-owned comp...",Cape Town,Cape Town
113,Data Engineer,indeed,Handyman - Protea Hotel by Marriott Breakwater...,Marriott International,fulltime,True,2026-06-11,**Additional Information** \n\n**Job Number**...,Cape Town,Cape Town
114,Data Engineer,indeed,Software Engineering Manager,SkyeBiz,fulltime,False,2026-06-11,Location: Cape Town\n\n\nSalary: 80k\-135k per...,Cape Town,Cape Town
115,Data Engineer,indeed,DevOps Engineer,Unknown,fulltime,True,2026-06-11,About GLI\n\nAt GLI our software development t...,Century City,Cape Town
116,Data Engineer,indeed,Systems Operations Engineer,Unknown,fulltime,True,2026-06-11,About GLI\n\nAt GLI our software development t...,Century City,Cape Town
117,Data Engineer,indeed,Junior Sales Manager / Engineer,Exactocraft,Unknown,False,2026-06-11,**Position Overview**\n\nWe are seeking a dyna...,Blackheath,Cape Town
118,Data Engineer,indeed,Principal AWS Cloud Architect,NTT DATA,fulltime,False,2026-06-11,Make an impact with NTT DATA\n \nJoin a compa...,Cape Town,Cape Town
119,Data Engineer,indeed,Mechanical Engineer (Public Health/ Wet Services),WSP,Unknown,False,2026-06-10,WSP is one of Africa’s most diverse consulting...,Cape Town,Cape Town
120,Data Engineer,indeed,Technical Lead,Stowe Holdings (Pty) Ltd.,fulltime,False,2026-06-10,**Job Profile**\n\nThe purpose of the job is t...,Cape Town,Cape Town
121,Data Engineer,indeed,Network Engineer,Hungry Lion Fast Foods,fulltime,True,2026-06-10,**Purpose of the Role** \n\n \n\nThe **Netwo...,Stellenbosch,Stellenbosch
122,Data Engineer,indeed,Project Engineer,Pragma,Unknown,False,2026-06-10,"### **Job Advert Summary**\n\n\nAt Pragma, we ...",Cape Town,Cape Town
123,Data Engineer,indeed,Junior Business Optimisation Engineer,OneNebula,Unknown,True,2026-06-09,Do you want to be part of a dynamic team const...,Milnerton,Cape Town
124,Data Engineer,indeed,Legal Operations Manager,BVNK,Unknown,True,2026-06-09,**About us:**\n\n \n\n\n\nWe believe the next...,Cape Town,Cape Town
125,Data Engineer,indeed,Principal Professional Officer - Business Impr...,City of Cape Town,Unknown,False,2026-06-09,ELIGIBILITY\n \n \n\nAll suitable applicants...,Cape Town,Cape Town
126,Data Engineer,indeed,1.5 Line Engineer (24-hour rotational shift),Scale Shore Consulting,fulltime,False,2026-06-09,**About the Role:** \nWe are seeking a motiva...,Cape Town,Cape Town
127,Data Engineer,indeed,Product Manager,Rank Group,Unknown,False,2026-06-08,Just us at Rank Interactive\n \n \n\nRank In...,Cape Town,Cape Town
128,Data Engineer,indeed,Engineering Manager,2U,fulltime,False,2026-06-08,"At 2U, we are all in on purpose. We are motiva...",Cape Town,Cape Town
129,Data Engineer,indeed,Senior Software Engineer,Kurtosys,fulltime,True,2026-06-08,**About the Role**\n\n \n\nKurtosys builds th...,Claremont,Cape Town
130,Data Engineer,indeed,Technical Support Engineer,Ozow,Unknown,True,2026-06-08,**Meet Ozow:**\n\n\n\nOzow is a leading fintec...,Cape Town,Cape Town
131,Data Engineer,indeed,Senior Frontend Engineer,Weaver Fintech Ltd,Unknown,False,2026-06-08,Weaver FinTech Group is a leading digital fina...,Cape Town,Cape Town
132,Data Engineer,indeed,AUTOMATION ENGINEER (Cape Town - Office Based),Media24,Unknown,False,2026-06-08,**AUTOMATION ENGINEER (CAPE TOWN \- OFFICE BAS...,Cape Town,Cape Town
133,Data Engineer,indeed,"Senior Frontend Engineer, Accounting - 100% Re...",Hostaway,fulltime,True,2026-06-08,"**NOTE: This is a FULLY remote role, but the c...",Cape Town,Cape Town
134,Data Engineer,indeed,Customer Success Associate,Heidi,fulltime,True,2026-06-06,**Who We Are**\n--------------\n\n\nHealthcare...,Cape Town,Cape Town
135,Data Engineer,indeed,Azure / AWS Cloud Engineer for Data Science,DVT,fulltime,False,2026-06-05,DVT is one of the top software development com...,Cape Town,Cape Town
136,Data Engineer,indeed,Senior Customer Success Manager (Enterprise & ...,OpenNetworks,Unknown,True,2026-06-05,"At Opennetworks, the Senior Customer Success M...",Claremont,Cape Town

# Assigning Seniority of Job Positions to Level Column.

In [11]:
def get_level(title):
    title = str(title).lower()
    if 'senior' in title or 'snr' in title:
        return 'Senior'
    elif 'junior' in title or 'jnr' in title or 'graduate' in title:
        return 'Junior'
    elif 'associate' in title:
        return 'Associate/Entry'
    else:
        return 'Mid-Level'

df['Level'] = df['title'].apply(get_level)

In [12]:
df['Level'].value_counts()

Level
Mid-Level          213
Senior              65
Junior               9
Associate/Entry      2
Name: count, dtype: int64

# Formatting Job Type Column.

## Seperating job_type by Full-Time, Part-Time & Internship.

In [13]:
df.job_type.value_counts()

job_type
Unknown               222
fulltime               63
parttime, fulltime      2
parttime                1
internship              1
Name: count, dtype: int64

### First in removing the confusion 'parttime, fulltime' by converting them to full-time.

In [14]:
df.job_type = df.job_type.replace({"parttime, fulltime":"fulltime"})
df.job_type.value_counts()

job_type
Unknown       222
fulltime       65
parttime        1
internship      1
Name: count, dtype: int64

### Then I format the strings/title to make it easier to read.

In [15]:
def get_job_type(job_type):
    job_type = str(job_type).lower().strip()
    if 'fulltime' in job_type:
        return "Full-Time"
    elif 'parttime' in job_type:
        return "Part-Time"
    elif 'internship' in job_type:
        return "Internship"
    elif 'unknown' in job_type:
        return "Unknown"
df['Job Type'] = df['job_type'].apply(get_job_type)
df['Job Type'].value_counts()

Job Type
Unknown       222
Full-Time      65
Part-Time       1
Internship      1
Name: count, dtype: int64

In [16]:
df

,search_role,site,title,company,job_type,is_remote,date_posted,description,Location,City,Level,Job Type
0,Data Analyst,indeed,Claims Risk Analyst,Momentum Health,Unknown,False,2026-06-12,**Introduction**\nThrough our client\-facing b...,Bellville,Cape Town,Mid-Level,Unknown
1,Data Analyst,indeed,Senior Application Support Analyst (SQL-focused),MRI Software,fulltime,False,2026-06-12,MRI Software is seeking a Senior Application S...,Cape Town,Cape Town,Senior,Full-Time
2,Data Analyst,indeed,SOC Analyst,Zappi,fulltime,False,2026-06-12,### **Description**\n\n \n\nWe believe in hir...,Cape Town,Cape Town,Mid-Level,Full-Time
3,Data Analyst,indeed,Chief Delivery Officer (CDO),NJ Placement Consulting,fulltime,False,2026-06-12,##### **Overview**\n\n\nAmazing chance to join...,Rosebank,Cape Town,Mid-Level,Full-Time
4,Data Analyst,indeed,Business Intelligence Analyst,LekkeSlaap,fulltime,True,2026-06-12,Bring 3\+ years of proven experience in busine...,Cape Town,Cape Town,Mid-Level,Full-Time
5,Data Analyst,indeed,Technical Product Analyst,Sanlam,Unknown,False,2026-06-12,**Who are we?**\n\nSanlam Life and Savings (SL...,Bellville,Cape Town,Mid-Level,Unknown
6,Data Analyst,indeed,Utilities Analyst,FPG Property Management,fulltime,False,2026-06-12,**PURPOSE OF JOB**\n\nThe Utilities Analyst is...,Cape Town,Cape Town,Mid-Level,Full-Time
7,Data Analyst,indeed,Data Integrations Specialist - Client Focus,Healix Group of Companies,fulltime,False,2026-06-12,### **About the role**\n\n\nWe’re looking for ...,Cape Town,Cape Town,Mid-Level,Full-Time
8,Data Analyst,indeed,Senior BI Analyst - Team Leader,Auto Trader South Africa,Unknown,True,2026-06-12,**Senior BI Analyst \- Team Leader**\n========...,Nuweland,Cape Town,Senior,Unknown
9,Data Analyst,indeed,Domain / Product owner - HR systems,Unifi,Unknown,False,2026-06-12,**About Unifi**\n\n***Boldly different. Fierce...,Stellenbosch,Stellenbosch,Mid-Level,Unknown
10,Data Analyst,indeed,Data Analyst,Crisis24,fulltime,False,2026-06-11,Who We Are Looking For\n \n \n\nThe Data Ana...,Cape Town,Cape Town,Mid-Level,Full-Time
11,Data Analyst,indeed,Customer Success Reporting Analyst,Mama Money,fulltime,False,2026-06-11,**Who we are:**\n\n\n\nMama Money is a growth\...,Cape Town,Cape Town,Mid-Level,Full-Time
12,Data Analyst,indeed,Legal Content Analyst,RELX Group,fulltime,False,2026-06-11,"**Are you passionate about shaping accurate, t...",Cape Town,Cape Town,Mid-Level,Full-Time
13,Data Analyst,indeed,Legal Content Analyst,LexisNexis Legal & Professional,fulltime,False,2026-06-11,"**Are you passionate about shaping accurate, t...",Cape Town,Cape Town,Mid-Level,Full-Time
14,Data Analyst,indeed,Business Intelligence Analyst,Queenspark Pty Ltd,fulltime,False,2026-06-11,**Title:** Business Intelligence Analyst\n\n**...,Wynberg,Cape Town,Mid-Level,Full-Time
15,Data Analyst,indeed,Conflict Analyst,Frontline Managed Services,Unknown,False,2026-06-10,Welcome to Frontline Managed Services® – where...,Cape Town,Cape Town,Mid-Level,Unknown
16,Data Analyst,indeed,Paid Media Analyst,Clever Profits,fulltime,True,2026-06-10,**Description** \n\nCleverProfits is a financ...,Cape Town,Cape Town,Mid-Level,Full-Time
17,Data Analyst,indeed,Supply Chain Process Analyst,woolworths,Unknown,False,2026-06-10,### **Job Advert Summary**\n\n\nJoin Woolworth...,Cape Town,Cape Town,Mid-Level,Unknown
18,Data Analyst,indeed,BUSINESS ANALYST (INDUSTRIAL ENGINEER),Cartrack SA,Unknown,False,2026-06-10,**Listing reference:** cartr\_000815\n**Listin...,Cape Town,Cape Town,Mid-Level,Unknown
19,Data Analyst,indeed,"Manager, Grade 1: Spatial Analyst",South African National Biodiversity Institute,Unknown,False,2026-06-10,"**Manager, Grade 1: Spatial Analyst**\n\n**Sal...",Cape Town,Cape Town,Mid-Level,Unknown
20,Data Analyst,indeed,Integration Engineer/Developer,Cape Union Mart,Unknown,False,2026-06-10,**Why Join Cape Union Mart?**\n\n\nCape Union ...,Cape Town,Cape Town,Mid-Level,Unknown
21,Data Analyst,indeed,"Insight Analyst (Professional, BI Specialist (...",Concentrix,fulltime,False,2026-06-09,**JOB PURPOSE**\n\nTo support the development ...,Cape Town,Cape Town,Mid-Level,Full-Time
22,Data Analyst,indeed,Investment Guidelines Analyst (Contractor),Futuregrowth,parttime,False,2026-06-09,**Purpose of the position**\n\n\n\nA vacancy h...,Southern Suburbs,Cape Town,Mid-Level,Part-Time
23,Data Analyst,indeed,FinOps Analyst,Yoco,Unknown,False,2026-06-09,### **Who we are**\n\n\nYoco was founded in 20...,Cape Town,Cape Town,Mid-Level,Unknown
24,Data Analyst,indeed,Databricks Data Engineer,Confluent,Unknown,False,2026-06-09,**Position: Data Engineer \- Intermediate** \...,Cape Town,Cape Town,Mid-Level,Unknown
25,Data Analyst,indeed,FinOps Analyst,Yoco Technologies,fulltime,False,2026-06-09,### **Who we are**\n\n\nYoco was founded in 20...,Cape Town,Cape Town,Mid-Level,Full-Time
26,Data Analyst,indeed,Commercial Finance Business Analyst,Avery Dennison,fulltime,False,2026-06-09,**Company Description** **ABOUT AVERY DENNISON...,Somerset West,Cape Town,Mid-Level,Full-Time
27,Data Analyst,indeed,Quality Analyst,Stowe Holdings (Pty) Ltd.,fulltime,False,2026-06-09,"**Please note, this is a non\-technical role i...",Goodwood,Cape Town,Mid-Level,Full-Time
28,Data Analyst,indeed,"WIM Investigator II, AmSec Workplace Incident ...",Amazon.com,fulltime,False,2026-06-08,**DESCRIPTION**\n---------------\n\n\nThe Work...,Cape Town,Cape Town,Mid-Level,Full-Time
29,Data Analyst,indeed,Supply Chain Analyst,The HEINEKEN Company,fulltime,False,2026-06-08,* Purpose of the job\n\n\n\n\|\n\n\nBe a first...,Stellenbosch,Stellenbosch,Mid-Level,Full-Time
30,Data Analyst,indeed,Data Management Analyst,MRI Software,fulltime,False,2026-06-08,**Position Overview:**\n\n\nWe are looking for...,Cape Town,Cape Town,Mid-Level,Full-Time
31,Data Analyst,indeed,Junior Credit Risk Analyst,Weaver Fintech Ltd,Unknown,False,2026-06-08,Weaver FinTech Group is a leading digital fina...,Cape Town,Cape Town,Junior,Unknown
32,Data Analyst,indeed,Sales Analyst (6 Month Contract),Kenvue,Unknown,False,2026-06-08,Kenvue is currently recruiting for a:\n\n\nSal...,Cape Town,Cape Town,Mid-Level,Unknown
33,Data Analyst,indeed,CRM & Data Analyst,Networking Mania,Unknown,False,2026-06-08,Job Title: CRM \& Data Analyst\n\nLocation: Ca...,Sea Point,Cape Town,Mid-Level,Unknown
34,Data Analyst,indeed,Realtime Analyst,WNS Global Services,fulltime,False,2026-06-08,"**Company Description** \n\nWNS, part of Capg...",Milnerton,Cape Town,Mid-Level,Full-Time
35,Data Analyst,indeed,Yield Analyst,LE BOAT,fulltime,False,2026-06-05,"**Le Boat, part of the Travelopia group**, is ...",Cape Town,Cape Town,Mid-Level,Full-Time
36,Data Analyst,indeed,Quality Analyst - Financial Services - Onsite ...,Concentrix,fulltime,False,2026-06-04,"**Quality Analyst – On\-site, Cape Town** \n\...",Cape Town,Cape Town,Mid-Level,Full-Time
37,Data Analyst,indeed,Senior Retail Media Insights Analyst,ShopriteX,fulltime,False,2026-06-01,**Senior Retail Media Insights Analyst**\n\n\n...,Brackenfell,Cape Town,Senior,Full-Time
38,Data Analyst,indeed,Digital Data Analyst (Rainmaker Media),ShopriteX,fulltime,False,2026-06-01,**Value Proposition**\n\n\nPowered by Africa's...,Brackenfell,Cape Town,Mid-Level,Full-Time
39,Data Analyst,indeed,Business Process Analyst,Lula,fulltime,False,2026-06-01,We are looking for a collaborative mid\-level ...,Cape Town,Cape Town,Mid-Level,Full-Time
40,Data Analyst,linkedin,Data Analyst,ExecutivePlacements.com,Unknown,False,2026-06-12,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
41,Data Analyst,linkedin,Business Intelligence Analyst (Retail) - Corpo...,Trending Talent Solutions,Unknown,False,2026-06-12,Unknown,City of Cape Town,Cape Town,Mid-Level,Unknown
42,Data Analyst,linkedin,Data Engineer (Senior),Parvana,Unknown,False,2026-06-12,Unknown,Bellville,Cape Town,Senior,Unknown
43,Data Analyst,linkedin,Applied Research Engineer,Duku AI,Unknown,False,2026-06-12,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
44,Data Analyst,linkedin,Senior Data Analyst,Capitec,Unknown,False,2026-06-11,Unknown,Stellenbosch,Stellenbosch,Senior,Unknown
45,Data Analyst,linkedin,BI Analyst,ExecutivePlacements.com,Unknown,False,2026-06-11,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
46,Data Analyst,linkedin,Collections and Payments Analytics Specialist ...,Black Pen Recruitment,Unknown,False,2026-06-11,Unknown,City of Cape Town,Cape Town,Mid-Level,Unknown
47,Data Analyst,linkedin,Data Analyst,Network Recruitment,Unknown,False,2026-06-10,Unknown,Stellenbosch,Stellenbosch,Mid-Level,Unknown
48,Data Analyst,linkedin,Business Intelligence Analyst,Communicate Recruitment,Unknown,False,2026-06-10,Unknown,City of Cape Town,Cape Town,Mid-Level,Unknown
49,Data Analyst,linkedin,Business Intelligence Analyst,Network Recruitment,Unknown,False,2026-06-10,Unknown,City of Cape Town,Cape Town,Mid-Level,Unknown
50,Data Analyst,linkedin,Senior Space Analyst,Woolworths,Unknown,False,2026-06-10,Unknown,Cape Town,Cape Town,Senior,Unknown
51,Data Analyst,linkedin,Data Analyst,Network International,Unknown,False,2026-06-09,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
52,Data Analyst,linkedin,Market Research Data Analyst,Potentiam Ltd,Unknown,False,2026-06-09,Unknown,City of Cape Town,Cape Town,Mid-Level,Unknown
53,Data Analyst,linkedin,"Data Analyst (Marketing Analytics, Bangkok Bas...",Agoda,Unknown,False,2026-06-09,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
54,Data Analyst,linkedin,Data Engineer - Databricks - July Start,Embelo,Unknown,False,2026-06-08,Unknown,City of Cape Town,Cape Town,Mid-Level,Unknown
55,Data Analyst,linkedin,Fundraising Systems and Data Specialist (m/f/d),FOUR PAWS,Unknown,False,2026-06-08,Unknown,City of Cape Town,Cape Town,Mid-Level,Unknown
56,Data Analyst,linkedin,Data Analyst,DigiOutsource,Unknown,False,2026-06-07,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
57,Data Analyst,linkedin,Junior Data Engineer,ExecutivePlacements.com,Unknown,False,2026-06-07,Unknown,Cape Town,Cape Town,Junior,Unknown
58,Data Analyst,linkedin,Business Data Analyst,ExecutivePlacements.com,Unknown,False,2026-06-06,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
59,Data Analyst,linkedin,Data & Insights Analyst,Vivo Energy,Unknown,False,2026-06-05,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
60,Data Analyst,linkedin,Yield Analyst,Le Boat,Unknown,False,2026-06-05,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
61,Data Analyst,linkedin,Dashboard & Reporting Specialist,Hunterlodge Advertising,Unknown,False,2026-06-05,Unknown,City of Cape Town,Cape Town,Mid-Level,Unknown
62,Data Analyst,linkedin,Director: Provincial Spatial Information (Ref ...,Western Cape Government,Unknown,False,2026-06-05,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
63,Data Analyst,linkedin,Senior Insights Manager,Mr D,Unknown,False,2026-06-05,Unknown,City of Cape Town,Cape Town,Senior,Unknown
64,Data Analyst,linkedin,Data Engineer,Communicate Recruitment,Unknown,False,2026-06-04,Unknown,City of Cape Town,Cape Town,Mid-Level,Unknown
65,Data Analyst,linkedin,Business Intelligence Developer,DigiOutsource,Unknown,False,2026-06-03,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
66,Data Analyst,linkedin,Quantitative Analyst,Capitec,Unknown,False,2026-06-03,Unknown,Stellenbosch,Stellenbosch,Mid-Level,Unknown
67,Data Analyst,linkedin,Senior Data Engineer,KingMakers,Unknown,False,2026-06-03,Unknown,Cape Town,Cape Town,Senior,Unknown
68,Data Analyst,linkedin,Client Reporting Analyst (12-month contract) –...,ExecutivePlacements.com,Unknown,False,2026-06-03,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
69,Data Analyst,linkedin,Remote Data/Image Collector (No Experience Nee...,TransPerfect,Unknown,True,2026-06-02,Unknown,City of Cape Town,Cape Town,Mid-Level,Unknown
70,Data Analyst,linkedin,Revenue Analysis & Performance Leader,Apex Group Ltd,Unknown,False,2026-06-02,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
71,Data Analyst,linkedin,Data Analyst II_Pipeline,Capitec,Unknown,False,2026-06-01,Unknown,Stellenbosch,Stellenbosch,Mid-Level,Unknown
72,Data Analyst,linkedin,SAf Software Developer,SMEC (an SJ Group company),Unknown,False,Unknown,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
73,Data Analyst,linkedin,Senior Collections Specialist (Business Intell...,Network Recruitment International,Unknown,False,Unknown,Unknown,City of Cape Town,Cape Town,Senior,Unknown
74,Data Analyst,linkedin,Senior Onboarding Analyst,BVNK,Unknown,False,Unknown,Unknown,Cape Town,Cape Town,Senior,Unknown
75,Data Scientist,indeed,CapeNature – SANCCOB Marine Field Ranger,SANCCOB,fulltime,False,2026-06-12,The Southern African Foundation for the Conser...,Cape Town,Cape Town,Mid-Level,Full-Time
76,Data Scientist,indeed,SANCCOB Coastal Field Ranger,SANCCOB,fulltime,False,2026-06-05,SANCCOB seeks to employ a full\-time Coastal F...,Cape Town,Cape Town,Mid-Level,Full-Time
77,Data Scientist,indeed,Platform Data Engineer,Confluent,Unknown,False,2026-06-02,Platform Data Engineer \n\n \n\n(**Hybrid/Pi...,Cape Town,Cape Town,Mid-Level,Unknown
78,Data Scientist,indeed,Data Scientist,PBT Group,Unknown,False,2026-06-01,##### **Employment Type**\n\n\nContract\n#####...,Stellenbosch,Stellenbosch,Mid-Level,Unknown
79,Data Scientist,linkedin,Machine Learning Engineer,Duku AI,Unknown,False,2026-06-12,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
80,Data Scientist,linkedin,AI Engineer,GVW Group,Unknown,False,2026-06-12,Unknown,Durbanville,Cape Town,Mid-Level,Unknown
81,Data Scientist,linkedin,Software Engineer (Front-End),DigiOutsource,Unknown,False,2026-06-12,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
82,Data Scientist,linkedin,Software Engineer (Full Stack),DigiOutsource,Unknown,False,2026-06-12,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
83,Data Scientist,linkedin,Junior Planning Analytics (TM1) Developer,DigiOutsource,Unknown,False,2026-06-12,Unknown,Cape Town,Cape Town,Junior,Unknown
84,Data Scientist,linkedin,"Intermediate Data Scientist - Cape Town, Hybrid",Ada Meher,Unknown,False,2026-06-11,Unknown,City of Cape Town,Cape Town,Mid-Level,Unknown
85,Data Scientist,linkedin,Senior Data Engineer,Keyrock,Unknown,False,2026-06-11,Unknown,Cape Town,Cape Town,Senior,Unknown
86,Data Scientist,linkedin,Analytics Engineer,Pargo,Unknown,False,2026-06-10,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
87,Data Scientist,linkedin,Actuarial Specialist,Outsized,Unknown,False,2026-06-10,Unknown,City of Cape Town,Cape Town,Mid-Level,Unknown
88,Data Scientist,linkedin,Data Scientist (Pipeline),Capita,Unknown,False,2026-06-09,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
89,Data Scientist,linkedin,Specialist Data Scientist,Old Mutual South Africa,Unknown,False,2026-06-09,Unknown,Pinelands,Cape Town,Mid-Level,Unknown
90,Data Scientist,linkedin,Senior Credit Risk Data Scientist,Oze,Unknown,False,2026-06-09,Unknown,City of Cape Town,Cape Town,Senior,Unknown
91,Data Scientist,linkedin,Manager: Data and Analytics,Capitec,Unknown,False,2026-06-09,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
92,Data Scientist,linkedin,Senior Test Engineer,Ozow,Unknown,False,2026-06-09,Unknown,Cape Town,Cape Town,Senior,Unknown
93,Data Scientist,linkedin,Xperts: Senior Java Engineer (Data Engineering),Inspired Testing,Unknown,False,2026-06-08,Unknown,Cape Town,Cape Town,Senior,Unknown
94,Data Scientist,linkedin,DevSecOps Engineer - Cape Town,Morae,Unknown,False,2026-06-08,Unknown,City of Cape Town,Cape Town,Mid-Level,Unknown
95,Data Scientist,linkedin,Principal Engineer,takealot.com,Unknown,False,2026-06-08,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
96,Data Scientist,linkedin,Senior Data / ML Engineer,Powerfleet,Unknown,False,2026-06-07,Unknown,Cape Town,Cape Town,Senior,Unknown
97,Data Scientist,linkedin,AI Data Platform Engineer,Storyteq,Unknown,False,2026-06-07,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
98,Data Scientist,linkedin,QA Engineer,ExecutivePlacements.com,Unknown,False,2026-06-06,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
99,Data Scientist,linkedin,BI Engineer: Takealot Group,takealot.com,Unknown,False,2026-06-04,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
100,Data Scientist,linkedin,Software Engineer,ExecutivePlacements.com,Unknown,False,2026-06-04,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
101,Data Scientist,linkedin,Data Scientist,ExecutivePlacements.com,Unknown,False,2026-06-02,Unknown,Stellenbosch,Stellenbosch,Mid-Level,Unknown
102,Data Scientist,linkedin,Research Development Engineer: Innovation (Int...,Clickatell,Unknown,False,2026-06-02,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
103,Data Scientist,linkedin,AI ENGINEER – REMOTE (CAPE TOWN),SASSO CONSULTING,Unknown,True,2026-06-02,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
104,Data Scientist,linkedin,Senior Engineer,Salt,Unknown,False,2026-06-02,Unknown,City of Cape Town,Cape Town,Senior,Unknown
105,Data Scientist,linkedin,Machine Learning Engineer,Sanlam,Unknown,False,2026-06-01,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
106,Data Scientist,linkedin,Quantitative Analyst,Communicate Recruitment,Unknown,False,2026-06-01,Unknown,City of Cape Town,Cape Town,Mid-Level,Unknown
107,Data Scientist,linkedin,Data Engineer - L3,Advania UK,Unknown,False,Unknown,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
108,Data Engineer,indeed,Technical Support Engineer,Root Platform,Unknown,False,2026-06-12,**Mission**\n-----------\n\n**As a Technical S...,Cape Town,Cape Town,Mid-Level,Unknown
109,Data Engineer,indeed,Senior Software Engineer (Full-Stack),Betway Group,fulltime,False,2026-06-12,Kick\-start your career in the online gaming w...,Cape Town,Cape Town,Senior,Full-Time
110,Data Engineer,indeed,Software Development Engineer – 2026,Amazon.com,fulltime,False,2026-06-12,**DESCRIPTION**\n---------------\n\n\nDo you w...,Cape Town,Cape Town,Mid-Level,Full-Time
111,Data Engineer,indeed,"Chief Engineer, DCEO",Amazon.com,fulltime,False,2026-06-12,**DESCRIPTION**\n---------------\n\n\nAWS Data...,Cape Town,Cape Town,Mid-Level,Full-Time
112,Data Engineer,indeed,Data Engineer,COLLINSON,Unknown,False,2026-06-11,"Collinson is the global, privately\-owned comp...",Cape Town,Cape Town,Mid-Level,Unknown
113,Data Engineer,indeed,Handyman - Protea Hotel by Marriott Breakwater...,Marriott International,fulltime,True,2026-06-11,**Additional Information** \n\n**Job Number**...,Cape Town,Cape Town,Mid-Level,Full-Time
114,Data Engineer,indeed,Software Engineering Manager,SkyeBiz,fulltime,False,2026-06-11,Location: Cape Town\n\n\nSalary: 80k\-135k per...,Cape Town,Cape Town,Mid-Level,Full-Time
115,Data Engineer,indeed,DevOps Engineer,Unknown,fulltime,True,2026-06-11,About GLI\n\nAt GLI our software development t...,Century City,Cape Town,Mid-Level,Full-Time
116,Data Engineer,indeed,Systems Operations Engineer,Unknown,fulltime,True,2026-06-11,About GLI\n\nAt GLI our software development t...,Century City,Cape Town,Mid-Level,Full-Time
117,Data Engineer,indeed,Junior Sales Manager / Engineer,Exactocraft,Unknown,False,2026-06-11,**Position Overview**\n\nWe are seeking a dyna...,Blackheath,Cape Town,Junior,Unknown
118,Data Engineer,indeed,Principal AWS Cloud Architect,NTT DATA,fulltime,False,2026-06-11,Make an impact with NTT DATA\n \nJoin a compa...,Cape Town,Cape Town,Mid-Level,Full-Time
119,Data Engineer,indeed,Mechanical Engineer (Public Health/ Wet Services),WSP,Unknown,False,2026-06-10,WSP is one of Africa’s most diverse consulting...,Cape Town,Cape Town,Mid-Level,Unknown
120,Data Engineer,indeed,Technical Lead,Stowe Holdings (Pty) Ltd.,fulltime,False,2026-06-10,**Job Profile**\n\nThe purpose of the job is t...,Cape Town,Cape Town,Mid-Level,Full-Time
121,Data Engineer,indeed,Network Engineer,Hungry Lion Fast Foods,fulltime,True,2026-06-10,**Purpose of the Role** \n\n \n\nThe **Netwo...,Stellenbosch,Stellenbosch,Mid-Level,Full-Time
122,Data Engineer,indeed,Project Engineer,Pragma,Unknown,False,2026-06-10,"### **Job Advert Summary**\n\n\nAt Pragma, we ...",Cape Town,Cape Town,Mid-Level,Unknown

### Now I'll drop job_type column as it's no longer needed.

In [17]:
df = df.drop(columns='job_type')
df

,search_role,site,title,company,is_remote,date_posted,description,Location,City,Level,Job Type
0,Data Analyst,indeed,Claims Risk Analyst,Momentum Health,False,2026-06-12,**Introduction**\nThrough our client\-facing b...,Bellville,Cape Town,Mid-Level,Unknown
1,Data Analyst,indeed,Senior Application Support Analyst (SQL-focused),MRI Software,False,2026-06-12,MRI Software is seeking a Senior Application S...,Cape Town,Cape Town,Senior,Full-Time
2,Data Analyst,indeed,SOC Analyst,Zappi,False,2026-06-12,### **Description**\n\n \n\nWe believe in hir...,Cape Town,Cape Town,Mid-Level,Full-Time
3,Data Analyst,indeed,Chief Delivery Officer (CDO),NJ Placement Consulting,False,2026-06-12,##### **Overview**\n\n\nAmazing chance to join...,Rosebank,Cape Town,Mid-Level,Full-Time
4,Data Analyst,indeed,Business Intelligence Analyst,LekkeSlaap,True,2026-06-12,Bring 3\+ years of proven experience in busine...,Cape Town,Cape Town,Mid-Level,Full-Time
5,Data Analyst,indeed,Technical Product Analyst,Sanlam,False,2026-06-12,**Who are we?**\n\nSanlam Life and Savings (SL...,Bellville,Cape Town,Mid-Level,Unknown
6,Data Analyst,indeed,Utilities Analyst,FPG Property Management,False,2026-06-12,**PURPOSE OF JOB**\n\nThe Utilities Analyst is...,Cape Town,Cape Town,Mid-Level,Full-Time
7,Data Analyst,indeed,Data Integrations Specialist - Client Focus,Healix Group of Companies,False,2026-06-12,### **About the role**\n\n\nWe’re looking for ...,Cape Town,Cape Town,Mid-Level,Full-Time
8,Data Analyst,indeed,Senior BI Analyst - Team Leader,Auto Trader South Africa,True,2026-06-12,**Senior BI Analyst \- Team Leader**\n========...,Nuweland,Cape Town,Senior,Unknown
9,Data Analyst,indeed,Domain / Product owner - HR systems,Unifi,False,2026-06-12,**About Unifi**\n\n***Boldly different. Fierce...,Stellenbosch,Stellenbosch,Mid-Level,Unknown
10,Data Analyst,indeed,Data Analyst,Crisis24,False,2026-06-11,Who We Are Looking For\n \n \n\nThe Data Ana...,Cape Town,Cape Town,Mid-Level,Full-Time
11,Data Analyst,indeed,Customer Success Reporting Analyst,Mama Money,False,2026-06-11,**Who we are:**\n\n\n\nMama Money is a growth\...,Cape Town,Cape Town,Mid-Level,Full-Time
12,Data Analyst,indeed,Legal Content Analyst,RELX Group,False,2026-06-11,"**Are you passionate about shaping accurate, t...",Cape Town,Cape Town,Mid-Level,Full-Time
13,Data Analyst,indeed,Legal Content Analyst,LexisNexis Legal & Professional,False,2026-06-11,"**Are you passionate about shaping accurate, t...",Cape Town,Cape Town,Mid-Level,Full-Time
14,Data Analyst,indeed,Business Intelligence Analyst,Queenspark Pty Ltd,False,2026-06-11,**Title:** Business Intelligence Analyst\n\n**...,Wynberg,Cape Town,Mid-Level,Full-Time
15,Data Analyst,indeed,Conflict Analyst,Frontline Managed Services,False,2026-06-10,Welcome to Frontline Managed Services® – where...,Cape Town,Cape Town,Mid-Level,Unknown
16,Data Analyst,indeed,Paid Media Analyst,Clever Profits,True,2026-06-10,**Description** \n\nCleverProfits is a financ...,Cape Town,Cape Town,Mid-Level,Full-Time
17,Data Analyst,indeed,Supply Chain Process Analyst,woolworths,False,2026-06-10,### **Job Advert Summary**\n\n\nJoin Woolworth...,Cape Town,Cape Town,Mid-Level,Unknown
18,Data Analyst,indeed,BUSINESS ANALYST (INDUSTRIAL ENGINEER),Cartrack SA,False,2026-06-10,**Listing reference:** cartr\_000815\n**Listin...,Cape Town,Cape Town,Mid-Level,Unknown
19,Data Analyst,indeed,"Manager, Grade 1: Spatial Analyst",South African National Biodiversity Institute,False,2026-06-10,"**Manager, Grade 1: Spatial Analyst**\n\n**Sal...",Cape Town,Cape Town,Mid-Level,Unknown
20,Data Analyst,indeed,Integration Engineer/Developer,Cape Union Mart,False,2026-06-10,**Why Join Cape Union Mart?**\n\n\nCape Union ...,Cape Town,Cape Town,Mid-Level,Unknown
21,Data Analyst,indeed,"Insight Analyst (Professional, BI Specialist (...",Concentrix,False,2026-06-09,**JOB PURPOSE**\n\nTo support the development ...,Cape Town,Cape Town,Mid-Level,Full-Time
22,Data Analyst,indeed,Investment Guidelines Analyst (Contractor),Futuregrowth,False,2026-06-09,**Purpose of the position**\n\n\n\nA vacancy h...,Southern Suburbs,Cape Town,Mid-Level,Part-Time
23,Data Analyst,indeed,FinOps Analyst,Yoco,False,2026-06-09,### **Who we are**\n\n\nYoco was founded in 20...,Cape Town,Cape Town,Mid-Level,Unknown
24,Data Analyst,indeed,Databricks Data Engineer,Confluent,False,2026-06-09,**Position: Data Engineer \- Intermediate** \...,Cape Town,Cape Town,Mid-Level,Unknown
25,Data Analyst,indeed,FinOps Analyst,Yoco Technologies,False,2026-06-09,### **Who we are**\n\n\nYoco was founded in 20...,Cape Town,Cape Town,Mid-Level,Full-Time
26,Data Analyst,indeed,Commercial Finance Business Analyst,Avery Dennison,False,2026-06-09,**Company Description** **ABOUT AVERY DENNISON...,Somerset West,Cape Town,Mid-Level,Full-Time
27,Data Analyst,indeed,Quality Analyst,Stowe Holdings (Pty) Ltd.,False,2026-06-09,"**Please note, this is a non\-technical role i...",Goodwood,Cape Town,Mid-Level,Full-Time
28,Data Analyst,indeed,"WIM Investigator II, AmSec Workplace Incident ...",Amazon.com,False,2026-06-08,**DESCRIPTION**\n---------------\n\n\nThe Work...,Cape Town,Cape Town,Mid-Level,Full-Time
29,Data Analyst,indeed,Supply Chain Analyst,The HEINEKEN Company,False,2026-06-08,* Purpose of the job\n\n\n\n\|\n\n\nBe a first...,Stellenbosch,Stellenbosch,Mid-Level,Full-Time
30,Data Analyst,indeed,Data Management Analyst,MRI Software,False,2026-06-08,**Position Overview:**\n\n\nWe are looking for...,Cape Town,Cape Town,Mid-Level,Full-Time
31,Data Analyst,indeed,Junior Credit Risk Analyst,Weaver Fintech Ltd,False,2026-06-08,Weaver FinTech Group is a leading digital fina...,Cape Town,Cape Town,Junior,Unknown
32,Data Analyst,indeed,Sales Analyst (6 Month Contract),Kenvue,False,2026-06-08,Kenvue is currently recruiting for a:\n\n\nSal...,Cape Town,Cape Town,Mid-Level,Unknown
33,Data Analyst,indeed,CRM & Data Analyst,Networking Mania,False,2026-06-08,Job Title: CRM \& Data Analyst\n\nLocation: Ca...,Sea Point,Cape Town,Mid-Level,Unknown
34,Data Analyst,indeed,Realtime Analyst,WNS Global Services,False,2026-06-08,"**Company Description** \n\nWNS, part of Capg...",Milnerton,Cape Town,Mid-Level,Full-Time
35,Data Analyst,indeed,Yield Analyst,LE BOAT,False,2026-06-05,"**Le Boat, part of the Travelopia group**, is ...",Cape Town,Cape Town,Mid-Level,Full-Time
36,Data Analyst,indeed,Quality Analyst - Financial Services - Onsite ...,Concentrix,False,2026-06-04,"**Quality Analyst – On\-site, Cape Town** \n\...",Cape Town,Cape Town,Mid-Level,Full-Time
37,Data Analyst,indeed,Senior Retail Media Insights Analyst,ShopriteX,False,2026-06-01,**Senior Retail Media Insights Analyst**\n\n\n...,Brackenfell,Cape Town,Senior,Full-Time
38,Data Analyst,indeed,Digital Data Analyst (Rainmaker Media),ShopriteX,False,2026-06-01,**Value Proposition**\n\n\nPowered by Africa's...,Brackenfell,Cape Town,Mid-Level,Full-Time
39,Data Analyst,indeed,Business Process Analyst,Lula,False,2026-06-01,We are looking for a collaborative mid\-level ...,Cape Town,Cape Town,Mid-Level,Full-Time
40,Data Analyst,linkedin,Data Analyst,ExecutivePlacements.com,False,2026-06-12,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
41,Data Analyst,linkedin,Business Intelligence Analyst (Retail) - Corpo...,Trending Talent Solutions,False,2026-06-12,Unknown,City of Cape Town,Cape Town,Mid-Level,Unknown
42,Data Analyst,linkedin,Data Engineer (Senior),Parvana,False,2026-06-12,Unknown,Bellville,Cape Town,Senior,Unknown
43,Data Analyst,linkedin,Applied Research Engineer,Duku AI,False,2026-06-12,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
44,Data Analyst,linkedin,Senior Data Analyst,Capitec,False,2026-06-11,Unknown,Stellenbosch,Stellenbosch,Senior,Unknown
45,Data Analyst,linkedin,BI Analyst,ExecutivePlacements.com,False,2026-06-11,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
46,Data Analyst,linkedin,Collections and Payments Analytics Specialist ...,Black Pen Recruitment,False,2026-06-11,Unknown,City of Cape Town,Cape Town,Mid-Level,Unknown
47,Data Analyst,linkedin,Data Analyst,Network Recruitment,False,2026-06-10,Unknown,Stellenbosch,Stellenbosch,Mid-Level,Unknown
48,Data Analyst,linkedin,Business Intelligence Analyst,Communicate Recruitment,False,2026-06-10,Unknown,City of Cape Town,Cape Town,Mid-Level,Unknown
49,Data Analyst,linkedin,Business Intelligence Analyst,Network Recruitment,False,2026-06-10,Unknown,City of Cape Town,Cape Town,Mid-Level,Unknown
50,Data Analyst,linkedin,Senior Space Analyst,Woolworths,False,2026-06-10,Unknown,Cape Town,Cape Town,Senior,Unknown
51,Data Analyst,linkedin,Data Analyst,Network International,False,2026-06-09,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
52,Data Analyst,linkedin,Market Research Data Analyst,Potentiam Ltd,False,2026-06-09,Unknown,City of Cape Town,Cape Town,Mid-Level,Unknown
53,Data Analyst,linkedin,"Data Analyst (Marketing Analytics, Bangkok Bas...",Agoda,False,2026-06-09,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
54,Data Analyst,linkedin,Data Engineer - Databricks - July Start,Embelo,False,2026-06-08,Unknown,City of Cape Town,Cape Town,Mid-Level,Unknown
55,Data Analyst,linkedin,Fundraising Systems and Data Specialist (m/f/d),FOUR PAWS,False,2026-06-08,Unknown,City of Cape Town,Cape Town,Mid-Level,Unknown
56,Data Analyst,linkedin,Data Analyst,DigiOutsource,False,2026-06-07,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
57,Data Analyst,linkedin,Junior Data Engineer,ExecutivePlacements.com,False,2026-06-07,Unknown,Cape Town,Cape Town,Junior,Unknown
58,Data Analyst,linkedin,Business Data Analyst,ExecutivePlacements.com,False,2026-06-06,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
59,Data Analyst,linkedin,Data & Insights Analyst,Vivo Energy,False,2026-06-05,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
60,Data Analyst,linkedin,Yield Analyst,Le Boat,False,2026-06-05,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
61,Data Analyst,linkedin,Dashboard & Reporting Specialist,Hunterlodge Advertising,False,2026-06-05,Unknown,City of Cape Town,Cape Town,Mid-Level,Unknown
62,Data Analyst,linkedin,Director: Provincial Spatial Information (Ref ...,Western Cape Government,False,2026-06-05,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
63,Data Analyst,linkedin,Senior Insights Manager,Mr D,False,2026-06-05,Unknown,City of Cape Town,Cape Town,Senior,Unknown
64,Data Analyst,linkedin,Data Engineer,Communicate Recruitment,False,2026-06-04,Unknown,City of Cape Town,Cape Town,Mid-Level,Unknown
65,Data Analyst,linkedin,Business Intelligence Developer,DigiOutsource,False,2026-06-03,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
66,Data Analyst,linkedin,Quantitative Analyst,Capitec,False,2026-06-03,Unknown,Stellenbosch,Stellenbosch,Mid-Level,Unknown
67,Data Analyst,linkedin,Senior Data Engineer,KingMakers,False,2026-06-03,Unknown,Cape Town,Cape Town,Senior,Unknown
68,Data Analyst,linkedin,Client Reporting Analyst (12-month contract) –...,ExecutivePlacements.com,False,2026-06-03,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
69,Data Analyst,linkedin,Remote Data/Image Collector (No Experience Nee...,TransPerfect,True,2026-06-02,Unknown,City of Cape Town,Cape Town,Mid-Level,Unknown
70,Data Analyst,linkedin,Revenue Analysis & Performance Leader,Apex Group Ltd,False,2026-06-02,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
71,Data Analyst,linkedin,Data Analyst II_Pipeline,Capitec,False,2026-06-01,Unknown,Stellenbosch,Stellenbosch,Mid-Level,Unknown
72,Data Analyst,linkedin,SAf Software Developer,SMEC (an SJ Group company),False,Unknown,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
73,Data Analyst,linkedin,Senior Collections Specialist (Business Intell...,Network Recruitment International,False,Unknown,Unknown,City of Cape Town,Cape Town,Senior,Unknown
74,Data Analyst,linkedin,Senior Onboarding Analyst,BVNK,False,Unknown,Unknown,Cape Town,Cape Town,Senior,Unknown
75,Data Scientist,indeed,CapeNature – SANCCOB Marine Field Ranger,SANCCOB,False,2026-06-12,The Southern African Foundation for the Conser...,Cape Town,Cape Town,Mid-Level,Full-Time
76,Data Scientist,indeed,SANCCOB Coastal Field Ranger,SANCCOB,False,2026-06-05,SANCCOB seeks to employ a full\-time Coastal F...,Cape Town,Cape Town,Mid-Level,Full-Time
77,Data Scientist,indeed,Platform Data Engineer,Confluent,False,2026-06-02,Platform Data Engineer \n\n \n\n(**Hybrid/Pi...,Cape Town,Cape Town,Mid-Level,Unknown
78,Data Scientist,indeed,Data Scientist,PBT Group,False,2026-06-01,##### **Employment Type**\n\n\nContract\n#####...,Stellenbosch,Stellenbosch,Mid-Level,Unknown
79,Data Scientist,linkedin,Machine Learning Engineer,Duku AI,False,2026-06-12,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
80,Data Scientist,linkedin,AI Engineer,GVW Group,False,2026-06-12,Unknown,Durbanville,Cape Town,Mid-Level,Unknown
81,Data Scientist,linkedin,Software Engineer (Front-End),DigiOutsource,False,2026-06-12,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
82,Data Scientist,linkedin,Software Engineer (Full Stack),DigiOutsource,False,2026-06-12,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
83,Data Scientist,linkedin,Junior Planning Analytics (TM1) Developer,DigiOutsource,False,2026-06-12,Unknown,Cape Town,Cape Town,Junior,Unknown
84,Data Scientist,linkedin,"Intermediate Data Scientist - Cape Town, Hybrid",Ada Meher,False,2026-06-11,Unknown,City of Cape Town,Cape Town,Mid-Level,Unknown
85,Data Scientist,linkedin,Senior Data Engineer,Keyrock,False,2026-06-11,Unknown,Cape Town,Cape Town,Senior,Unknown
86,Data Scientist,linkedin,Analytics Engineer,Pargo,False,2026-06-10,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
87,Data Scientist,linkedin,Actuarial Specialist,Outsized,False,2026-06-10,Unknown,City of Cape Town,Cape Town,Mid-Level,Unknown
88,Data Scientist,linkedin,Data Scientist (Pipeline),Capita,False,2026-06-09,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
89,Data Scientist,linkedin,Specialist Data Scientist,Old Mutual South Africa,False,2026-06-09,Unknown,Pinelands,Cape Town,Mid-Level,Unknown
90,Data Scientist,linkedin,Senior Credit Risk Data Scientist,Oze,False,2026-06-09,Unknown,City of Cape Town,Cape Town,Senior,Unknown
91,Data Scientist,linkedin,Manager: Data and Analytics,Capitec,False,2026-06-09,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
92,Data Scientist,linkedin,Senior Test Engineer,Ozow,False,2026-06-09,Unknown,Cape Town,Cape Town,Senior,Unknown
93,Data Scientist,linkedin,Xperts: Senior Java Engineer (Data Engineering),Inspired Testing,False,2026-06-08,Unknown,Cape Town,Cape Town,Senior,Unknown
94,Data Scientist,linkedin,DevSecOps Engineer - Cape Town,Morae,False,2026-06-08,Unknown,City of Cape Town,Cape Town,Mid-Level,Unknown
95,Data Scientist,linkedin,Principal Engineer,takealot.com,False,2026-06-08,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
96,Data Scientist,linkedin,Senior Data / ML Engineer,Powerfleet,False,2026-06-07,Unknown,Cape Town,Cape Town,Senior,Unknown
97,Data Scientist,linkedin,AI Data Platform Engineer,Storyteq,False,2026-06-07,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
98,Data Scientist,linkedin,QA Engineer,ExecutivePlacements.com,False,2026-06-06,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
99,Data Scientist,linkedin,BI Engineer: Takealot Group,takealot.com,False,2026-06-04,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
100,Data Scientist,linkedin,Software Engineer,ExecutivePlacements.com,False,2026-06-04,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
101,Data Scientist,linkedin,Data Scientist,ExecutivePlacements.com,False,2026-06-02,Unknown,Stellenbosch,Stellenbosch,Mid-Level,Unknown
102,Data Scientist,linkedin,Research Development Engineer: Innovation (Int...,Clickatell,False,2026-06-02,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
103,Data Scientist,linkedin,AI ENGINEER – REMOTE (CAPE TOWN),SASSO CONSULTING,True,2026-06-02,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
104,Data Scientist,linkedin,Senior Engineer,Salt,False,2026-06-02,Unknown,City of Cape Town,Cape Town,Senior,Unknown
105,Data Scientist,linkedin,Machine Learning Engineer,Sanlam,False,2026-06-01,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
106,Data Scientist,linkedin,Quantitative Analyst,Communicate Recruitment,False,2026-06-01,Unknown,City of Cape Town,Cape Town,Mid-Level,Unknown
107,Data Scientist,linkedin,Data Engineer - L3,Advania UK,False,Unknown,Unknown,Cape Town,Cape Town,Mid-Level,Unknown
108,Data Engineer,indeed,Technical Support Engineer,Root Platform,False,2026-06-12,**Mission**\n-----------\n\n**As a Technical S...,Cape Town,Cape Town,Mid-Level,Unknown
109,Data Engineer,indeed,Senior Software Engineer (Full-Stack),Betway Group,False,2026-06-12,Kick\-start your career in the online gaming w...,Cape Town,Cape Town,Senior,Full-Time
110,Data Engineer,indeed,Software Development Engineer – 2026,Amazon.com,False,2026-06-12,**DESCRIPTION**\n---------------\n\n\nDo you w...,Cape Town,Cape Town,Mid-Level,Full-Time
111,Data Engineer,indeed,"Chief Engineer, DCEO",Amazon.com,False,2026-06-12,**DESCRIPTION**\n---------------\n\n\nAWS Data...,Cape Town,Cape Town,Mid-Level,Full-Time
112,Data Engineer,indeed,Data Engineer,COLLINSON,False,2026-06-11,"Collinson is the global, privately\-owned comp...",Cape Town,Cape Town,Mid-Level,Unknown
113,Data Engineer,indeed,Handyman - Protea Hotel by Marriott Breakwater...,Marriott International,True,2026-06-11,**Additional Information** \n\n**Job Number**...,Cape Town,Cape Town,Mid-Level,Full-Time
114,Data Engineer,indeed,Software Engineering Manager,SkyeBiz,False,2026-06-11,Location: Cape Town\n\n\nSalary: 80k\-135k per...,Cape Town,Cape Town,Mid-Level,Full-Time
115,Data Engineer,indeed,DevOps Engineer,Unknown,True,2026-06-11,About GLI\n\nAt GLI our software development t...,Century City,Cape Town,Mid-Level,Full-Time
116,Data Engineer,indeed,Systems Operations Engineer,Unknown,True,2026-06-11,About GLI\n\nAt GLI our software development t...,Century City,Cape Town,Mid-Level,Full-Time
117,Data Engineer,indeed,Junior Sales Manager / Engineer,Exactocraft,False,2026-06-11,**Position Overview**\n\nWe are seeking a dyna...,Blackheath,Cape Town,Junior,Unknown
118,Data Engineer,indeed,Principal AWS Cloud Architect,NTT DATA,False,2026-06-11,Make an impact with NTT DATA\n \nJoin a compa...,Cape Town,Cape Town,Mid-Level,Full-Time
119,Data Engineer,indeed,Mechanical Engineer (Public Health/ Wet Services),WSP,False,2026-06-10,WSP is one of Africa’s most diverse consulting...,Cape Town,Cape Town,Mid-Level,Unknown
120,Data Engineer,indeed,Technical Lead,Stowe Holdings (Pty) Ltd.,False,2026-06-10,**Job Profile**\n\nThe purpose of the job is t...,Cape Town,Cape Town,Mid-Level,Full-Time
121,Data Engineer,indeed,Network Engineer,Hungry Lion Fast Foods,True,2026-06-10,**Purpose of the Role** \n\n \n\nThe **Netwo...,Stellenbosch,Stellenbosch,Mid-Level,Full-Time
122,Data Engineer,indeed,Project Engineer,Pragma,False,2026-06-10,"### **Job Advert Summary**\n\n\nAt Pragma, we ...",Cape Town,Cape Town,Mid-Level,Unknown
123,Data Engineer,indeed,Junior Business Optimisation Engineer,OneNebula,True,2026-06-09,Do you want to be part of a dynamic team const...,Milnerton,Cape Town,Junior,Unknown
124,Data Engineer,indeed,Legal Operations Manager,BVNK,True,2026-06-09,**About us:**\n\n \n\n\n\nWe believe the next...,Cape Town,Cape Town,Mid-Level,Unknown
125,Data Engineer,indeed,Principal Professional Officer - Business Impr...,City of Cape Town,False,2026-06-09,ELIGIBILITY\n \n \n\nAll suitable applicants...,Cape Town,Cape Town,Mid-Level,Unknown
126,Data Engineer,indeed,1.5 Line Engineer (24-hour rotational shift),Scale Shore Consulting,False,2026-06-09,**About the Role:** \nWe are seeking a motiva...,Cape Town,Cape Town,Mid-Level,Full-Time
127,Data Engineer,indeed,Product Manager,Rank Group,False,2026-06-08,Just us at Rank Interactive\n \n \n\nRank In...,Cape Town,Cape Town,Mid-Level,Unknown
128,Data Engineer,indeed,Engineering Manager,2U,False,2026-06-08,"At 2U, we are all in on purpose. We are motiva...",Cape Town,Cape Town,Mid-Level,Full-Time

# Cleaning Description Column.

### Next I want clean the description column by removing characters and strange syntax.

In [18]:
df['description']

0      **Introduction**\nThrough our client\-facing b...
1      MRI Software is seeking a Senior Application S...
2      ### **Description**\n\n  \n\nWe believe in hir...
3      ##### **Overview**\n\n\nAmazing chance to join...
4      Bring 3\+ years of proven experience in busine...
5      **Who are we?**\n\nSanlam Life and Savings (SL...
6      **PURPOSE OF JOB**\n\nThe Utilities Analyst is...
7      ### **About the role**\n\n\nWe’re looking for ...
8      **Senior BI Analyst \- Team Leader**\n========...
9      **About Unifi**\n\n***Boldly different. Fierce...
10     Who We Are Looking For\n  \n  \n\nThe Data Ana...
11     **Who we are:**\n\n\n\nMama Money is a growth\...
12     **Are you passionate about shaping accurate, t...
13     **Are you passionate about shaping accurate, t...
14     **Title:** Business Intelligence Analyst\n\n**...
15     Welcome to Frontline Managed Services® – where...
16     **Description**  \n\nCleverProfits is a financ...
17     ### **Job Advert Summary**\n\n\nJoin Woolworth...
18     **Listing reference:** cartr\_000815\n**Listin...
19     **Manager, Grade 1: Spatial Analyst**\n\n**Sal...
20     **Why Join Cape Union Mart?**\n\n\nCape Union ...
21     **JOB PURPOSE**\n\nTo support the development ...
22     **Purpose of the position**\n\n\n\nA vacancy h...
23     ### **Who we are**\n\n\nYoco was founded in 20...
24     **Position: Data Engineer \- Intermediate**  \...
25     ### **Who we are**\n\n\nYoco was founded in 20...
26     **Company Description** **ABOUT AVERY DENNISON...
27     **Please note, this is a non\-technical role i...
28     **DESCRIPTION**\n---------------\n\n\nThe Work...
29     * Purpose of the job\n\n\n\n\|\n\n\nBe a first...
30     **Position Overview:**\n\n\nWe are looking for...
31     Weaver FinTech Group is a leading digital fina...
32     Kenvue is currently recruiting for a:\n\n\nSal...
33     Job Title: CRM \& Data Analyst\n\nLocation: Ca...
34     **Company Description**  \n\nWNS, part of Capg...
35     **Le Boat, part of the Travelopia group**, is ...
36     **Quality Analyst – On\-site, Cape Town**  \n\...
37     **Senior Retail Media Insights Analyst**\n\n\n...
38     **Value Proposition**\n\n\nPowered by Africa's...
39     We are looking for a collaborative mid\-level ...
40                                               Unknown
41                                               Unknown
42                                               Unknown
43                                               Unknown
44                                               Unknown
45                                               Unknown
46                                               Unknown
47                                               Unknown
48                                               Unknown
49                                               Unknown
50                                               Unknown
51                                               Unknown
52                                               Unknown
53                                               Unknown
54                                               Unknown
55                                               Unknown
56                                               Unknown
57                                               Unknown
58                                               Unknown
59                                               Unknown
60                                               Unknown
61                                               Unknown
62                                               Unknown
63                                               Unknown
64                                               Unknown
65                                               Unknown
66                                               Unknown
67                                               Unknown
68                                               Unknown
69                                               Unknown
70                                               Unknown
71                                               Unknown
72                                               Unknown
73                                               Unknown
74                                               Unknown
75     The Southern African Foundation for the Conser...
76     SANCCOB seeks to employ a full\-time Coastal F...
77     Platform Data Engineer  \n\n  \n\n(**Hybrid/Pi...
78     ##### **Employment Type**\n\n\nContract\n#####...
79                                               Unknown
80                                               Unknown
81                                               Unknown
82                                               Unknown
83                                               Unknown
84                                               Unknown
85                                               Unknown
86                                               Unknown
87                                               Unknown
88                                               Unknown
89                                               Unknown
90                                               Unknown
91                                               Unknown
92                                               Unknown
93                                               Unknown
94                                               Unknown
95                                               Unknown
96                                               Unknown
97                                               Unknown
98                                               Unknown
99                                               Unknown
100                                              Unknown
101                                              Unknown
102                                              Unknown
103                                              Unknown
104                                              Unknown
105                                              Unknown
106                                              Unknown
107                                              Unknown
108    **Mission**\n-----------\n\n**As a Technical S...
109    Kick\-start your career in the online gaming w...
110    **DESCRIPTION**\n---------------\n\n\nDo you w...
111    **DESCRIPTION**\n---------------\n\n\nAWS Data...
112    Collinson is the global, privately\-owned comp...
113    **Additional Information**  \n\n**Job Number**...
114    Location: Cape Town\n\n\nSalary: 80k\-135k per...
115    About GLI\n\nAt GLI our software development t...
116    About GLI\n\nAt GLI our software development t...
117    **Position Overview**\n\nWe are seeking a dyna...
118    Make an impact with NTT DATA\n  \nJoin a compa...
119    WSP is one of Africa’s most diverse consulting...
120    **Job Profile**\n\nThe purpose of the job is t...
121    **Purpose of the Role**  \n\n  \n\nThe **Netwo...
122    ### **Job Advert Summary**\n\n\nAt Pragma, we ...
123    Do you want to be part of a dynamic team const...
124    **About us:**\n\n  \n\n\n\nWe believe the next...
125    ELIGIBILITY\n  \n  \n\nAll suitable applicants...
126    **About the Role:**  \nWe are seeking a motiva...
127    Just us at Rank Interactive\n  \n  \n\nRank In...
128    At 2U, we are all in on purpose. We are motiva...
129    **About the Role**\n\n  \n\nKurtosys builds th...
130    **Meet Ozow:**\n\n\n\nOzow is a leading fintec...
131    Weaver FinTech Group is a leading digital fina...
132    **AUTOMATION ENGINEER (CAPE TOWN \- OFFICE BAS...
133    **NOTE: This is a FULLY remote role, but the c...
134    **Who We Are**\n--------------\n\n\nHealthcare...
135    DVT is one of the top software development com...
136    At Opennetworks, the Senior Customer Success M...
137    We're hiring\n\nSQL Developer\n\nMid\-level · ...
138    DVT is one of the top software engineering com...
139    **Project Engineer – Engineering Services**\n\...
140    **DESCRIPTION**\n---------------\n\n\nBe a par...
141                                              Unknown
142                                              Unknown
143                                              Unknown
144                                              Unknown
145                                              Unknown
146                                              Unknown
147                                              Unknown
148                                              Unknown
149                                              Unknown
150                                              Unknown
151                                              Unknown
152                                              Unknown
153    **DESCRIPTION**\n---------------\n\n\nAmazon W...
154                                              Unknown
155                                              Unknown
156                                              Unknown
157                                              Unknown
158                                              Unknown
159                                              Unknown
160                                              Unknown
161                                              Unknown
162                                              Unknown
163                                              Unknown
164                                              Unknown
165                                              Unknown
166                                              Unknown
167                                              Unknown
168                                              Unknown
169                                              Unknown
170                                              Unknown
171                                              Unknown
172                                              Unknown
173                                              Unknown
174                                              Unknown
175                                              Unknown
176                                              Unknown
177    **Who we are**\n\n\n\nDigiCert is a global lea...
178    Clio is the global leader in legal AI technolo...
179    We’re building the next generation of TN Trade...
180    **Head of Power Platforms — AI \& Business Pro...
181    **Who We Are**\n--------------\n\n\nHealthcare...
182    Make an impact with NTT DATA\n  \nJoin a compa...
183    ### **Job Advert Summary**\n\n\nYou will lead ...
184    Collinson is the global, privately\-owned comp...
185                                              Unknown
186                                              Unknown
187                                              Unknown
188                                              Unknown
189                                              Unknown
190                                              Unknown
191                                              Unknown
192                                              Unknown
193                                              Unknown
194                                              Unknown
195                                              Unknown
196                                              Unknown
197                                              Unknown
198                                              Unknown
199                                              Unknown
200                                              Unknown
201                                              Unknown
202                                              Unknown
203                                              Unknown
204                                              Unknown
205    **About Us**\n\n\n\nLancia Insights helps busi...
206    At Incanda, data drives our decisions, support...
207    **About Us**\n\nLancia Insights helps business...
208    **Dialler Optimisations Specialist**\n\n  \n\n...
209                                              Unknown
210                                              Unknown
211                                              Unknown
212                                              Unknown
213                                              Unknown
214                                              Unknown
215                                              Unknown
216                                              Unknown
217                                              Unknown
218                                              Unknown
219                                              Unknown
220                                              Unknown
221                                              Unknown
222                                              Unknown
223                                              Unknown
224                                              Unknown
225                                              Unknown
226    The Focus Group Cape Town, South Africa 03 Jun...
227                                              Unknown
228                                              Unknown
229                                              Unknown
230                                              Unknown
231                                              Unknown
232                                              Unknown
233                                              Unknown
234                                              Unknown
235    *IMA is a creative agency that builds brands p...
236    Do you want to be part of a dynamic team const...
237    Job Purpose\n\nThe Intermediate Java Developer...
238    **Job Title:**Senior Manager, Finance – FP\&A ...
239                                              Unknown
240                                              Unknown
241                                              Unknown
242                                              Unknown
243                                              Unknown
244                                              Unknown
245                                              Unknown
246                                              Unknown
247                                              Unknown
248                                              Unknown
249                                              Unknown
250                                              Unknown
251                                              Unknown
252                                              Unknown
253                                              Unknown
254                                              Unknown
255    We are seeking a Senior Enterprise Architect (...
256    The Apex Group was established in Bermuda in 2...
257    Make an impact with NTT DATA\n  \nJoin a compa...
258    An exciting new design\-led furniture \& joine...
259    **About the company****Utopia** is an ultra\-l...
260    What being part of the Sigma Family means for ...
261    **We’re building something big.**\n\nSUPA is r...
262    Are you an architectural expert ready to build...
263    ### **Job Information**\n\n\nDate Opened\n\n\n...
264    **Business Systems Analyst**\n\n\nWe are seeki...
265    ### **Who We Are**\n\n\n\nVML, part of WPP, is...
266    **About the company****Utopia** is an ultra\-l...
267    ### **Purpose of the Job**\n\n\nThe role is re...
268    ### **Job Information**\n\n\nDate Opened\n\n\n...
269    **WHAT WE DO**  \n\n We build innovative finte...
270    **About Us**\n------------\n\n\nStep into the ...
271    **About the company****Utopia** is an ultra\-l...
272    **About the role**\n\n\nRubicon's Sustainable ...
273    **Who are we?**\nGlacier by Sanlam brings toge...
274    **Who are we?**\n\nSanlam Life and Savings (SL...
275                                              Unknown
276                                              Unknown
277                                              Unknown
278                                              Unknown
279                                              Unknown
280                                              Unknown
281                                              Unknown
282                                              Unknown
283                                              Unknown
284                                              Unknown
285                                              Unknown
286                                              Unknown
287                                              Unknown
288                                              Unknown
Name: description, dtype: str

### Using Python Regex for specifying patterns.

In [19]:
patterns = r'\\n|\n|\*{1,3}|=+|#{1,6}\s*|---+|/'

df['Description'] = (
    df['description']
    .str.replace(patterns, ' ', regex=True)
    .str.replace(r'\\-', '-', regex=True)
    .str.replace(r'\\&', '&', regex=True)    # \& → &
    .str.replace(r'\\|', '', regex=True)     # \| → remove
    .str.replace(r'\s{2,}', ' ', regex=True)
    .str.strip()
    .replace('Unknown', None)
)

### Seems like every weird characters are removed ;)

In [20]:
print(df['Description'].iloc[0])

Introduction Through our client-facing brands Metropolitan and Momentum, with Multiply (wellness and rewards programme), and our other specialist brands, including Guardrisk and Eris Property Group, the group enables business and people from all walks of life to achieve their financial goals and life aspirations. We help people grow their savings, protect what matters to them and invest for the future. We help companies and organisations care for and reward their employees and members. Through our own network of advisers or via independent brokers and utilising new platforms Momentum Metropolitan provides practical financial solutions for people, communities, and businesses. Disclaimer As an applicant, please verify the legitimacy of this job advert on our company career page. Role Purpose To conduct desktop based forensic investigations into potential instances of fraud, waste and or abuse across Momentum Health admisitered schemes and to collect documentory evidence, engage with all relevant parties i.e., service providers, members etc. drafting letters and investigation reports, perform data analytics and assit in the recovery of irregular paid claims. Requirements Qualification Valid Matric certificate. A relevant tertiary qualification such as, Clinical Healthcare related, Law, including Compliance, Business Operations e.g., auditing, accounting & operations. Knowledge Medical Scheme knowledge would be advantages. Years of experience Three years of forensic experience. Duties & Responsibilities Internal Process Conducting desktop forensic investigation in order to identify potential instances of fraud, waste and or abuse across MH administered schemes. Reporting on investigations conducted by submitting an investigation report to management for review and submission to the relevant scheme. Engage with relevant stakeholders (internal & external) to collect documentary evidence on instances of fraud, waste and or abuse identified. Draft letters providers members to raise concerns with regards to irregularities identified Perform data analytics to identify concerning trends on each investigation using the analytical tool available. Client Build and maintain relationships with internal and external stakeholders. Deliver on service level agreements applicable to clients, internal and external stakeholders in order to ensure that client expectations are managed. Make recommendations to improve claims processes controls where deficiencies in these areas are highlighted through investigations. Participate and contribute to a culture which builds rewarding relationships, facilitates feedback and provides exceptional client service. Continuously monitor turnaround times and quality standards and resolve issues speedily to enhance client service delivery. Drive client service delivery goal achievement in line with predefined standards in order to ensure that clients receive appropriate advice and after sales service. Manage the assigned investigation to ensure that fraud waste and abuse risks are mitigated through identification and investigation of potential fraud waste and or abuse. People Build strong relationships with peers and managers to ensure successful investigation outcomes. Continuously develop own expertise in terms of industry and subject matter development and application thereof in an area of specialisation. Contribute to continuous innovation through the development, sharing and or implementation of new ideas and involvement of colleagues and staff. Participate and contribute to a culture of work centric thinking, productivity, service delivery and quality management. Take ownership for driving own career development. Finance Assist in the recovery of irregular paid claims through engagement with providers and obtaining provider agreement on the repayment of irregular claims. Identify solutions to enhance cost effectiveness and increase operational efficiency. Competencies Analytical thinking Healthcare industry knowledge (advantageous) Time management Attention to detail Problem-solving Communication Confidentiality Adherence to regulations Maturity: Display a high level of emotional maturity, professionalism, and soundjudgment in handling sensitive cases and maintaining confi dentiality as well asinterpersonal offi ce relationships. Hardworking: Demonstrate a strong work ethic, dedication, and a commitment tomeeting deadlines and delivering quality results. Professionalism: Uphold the highest standards of professionalism, ethics, andintegrity, with a focus on the job's core responsibilities rather than engaging indisruptive, insubordinate, or disrespectful practices.

### Dropping the old description column.

In [21]:
df = df.drop(columns='description')
df

,search_role,site,title,company,is_remote,date_posted,Location,City,Level,Job Type,Description
0,Data Analyst,indeed,Claims Risk Analyst,Momentum Health,False,2026-06-12,Bellville,Cape Town,Mid-Level,Unknown,Introduction Through our client-facing brands ...
1,Data Analyst,indeed,Senior Application Support Analyst (SQL-focused),MRI Software,False,2026-06-12,Cape Town,Cape Town,Senior,Full-Time,MRI Software is seeking a Senior Application S...
2,Data Analyst,indeed,SOC Analyst,Zappi,False,2026-06-12,Cape Town,Cape Town,Mid-Level,Full-Time,Description We believe in hiring analysts who ...
3,Data Analyst,indeed,Chief Delivery Officer (CDO),NJ Placement Consulting,False,2026-06-12,Rosebank,Cape Town,Mid-Level,Full-Time,Overview Amazing chance to join a Software Dev...
4,Data Analyst,indeed,Business Intelligence Analyst,LekkeSlaap,True,2026-06-12,Cape Town,Cape Town,Mid-Level,Full-Time,Bring 3+ years of proven experience in busines...
5,Data Analyst,indeed,Technical Product Analyst,Sanlam,False,2026-06-12,Bellville,Cape Town,Mid-Level,Unknown,Who are we? Sanlam Life and Savings (SLS) is f...
6,Data Analyst,indeed,Utilities Analyst,FPG Property Management,False,2026-06-12,Cape Town,Cape Town,Mid-Level,Full-Time,PURPOSE OF JOB The Utilities Analyst is respon...
7,Data Analyst,indeed,Data Integrations Specialist - Client Focus,Healix Group of Companies,False,2026-06-12,Cape Town,Cape Town,Mid-Level,Full-Time,About the role We’re looking for a Data Integr...
8,Data Analyst,indeed,Senior BI Analyst - Team Leader,Auto Trader South Africa,True,2026-06-12,Nuweland,Cape Town,Senior,Unknown,Senior BI Analyst - Team Leader Remote We're l...
9,Data Analyst,indeed,Domain / Product owner - HR systems,Unifi,False,2026-06-12,Stellenbosch,Stellenbosch,Mid-Level,Unknown,About Unifi Boldly different. Fiercely human. ...
10,Data Analyst,indeed,Data Analyst,Crisis24,False,2026-06-11,Cape Town,Cape Town,Mid-Level,Full-Time,Who We Are Looking For The Data Analyst resear...
11,Data Analyst,indeed,Customer Success Reporting Analyst,Mama Money,False,2026-06-11,Cape Town,Cape Town,Mid-Level,Full-Time,Who we are: Mama Money is a growth-stage finte...
12,Data Analyst,indeed,Legal Content Analyst,RELX Group,False,2026-06-11,Cape Town,Cape Town,Mid-Level,Full-Time,"Are you passionate about shaping accurate, tim..."
13,Data Analyst,indeed,Legal Content Analyst,LexisNexis Legal & Professional,False,2026-06-11,Cape Town,Cape Town,Mid-Level,Full-Time,"Are you passionate about shaping accurate, tim..."
14,Data Analyst,indeed,Business Intelligence Analyst,Queenspark Pty Ltd,False,2026-06-11,Wynberg,Cape Town,Mid-Level,Full-Time,Title: Business Intelligence Analyst Location:...
15,Data Analyst,indeed,Conflict Analyst,Frontline Managed Services,False,2026-06-10,Cape Town,Cape Town,Mid-Level,Unknown,Welcome to Frontline Managed Services® – where...
16,Data Analyst,indeed,Paid Media Analyst,Clever Profits,True,2026-06-10,Cape Town,Cape Town,Mid-Level,Full-Time,Description CleverProfits is a financial servi...
17,Data Analyst,indeed,Supply Chain Process Analyst,woolworths,False,2026-06-10,Cape Town,Cape Town,Mid-Level,Unknown,Job Advert Summary Join Woolworths as a Supply...
18,Data Analyst,indeed,BUSINESS ANALYST (INDUSTRIAL ENGINEER),Cartrack SA,False,2026-06-10,Cape Town,Cape Town,Mid-Level,Unknown,Listing reference: cartr_000815 Listing status...
19,Data Analyst,indeed,"Manager, Grade 1: Spatial Analyst",South African National Biodiversity Institute,False,2026-06-10,Cape Town,Cape Town,Mid-Level,Unknown,"Manager, Grade 1: Spatial Analyst Salary Level..."
20,Data Analyst,indeed,Integration Engineer/Developer,Cape Union Mart,False,2026-06-10,Cape Town,Cape Town,Mid-Level,Unknown,Why Join Cape Union Mart? Cape Union Mart is S...
21,Data Analyst,indeed,"Insight Analyst (Professional, BI Specialist (...",Concentrix,False,2026-06-09,Cape Town,Cape Town,Mid-Level,Full-Time,JOB PURPOSE To support the development and imp...
22,Data Analyst,indeed,Investment Guidelines Analyst (Contractor),Futuregrowth,False,2026-06-09,Southern Suburbs,Cape Town,Mid-Level,Part-Time,Purpose of the position A vacancy has arisen f...
23,Data Analyst,indeed,FinOps Analyst,Yoco,False,2026-06-09,Cape Town,Cape Town,Mid-Level,Unknown,"Who we are Yoco was founded in 2015, and we’ve..."
24,Data Analyst,indeed,Databricks Data Engineer,Confluent,False,2026-06-09,Cape Town,Cape Town,Mid-Level,Unknown,Position: Data Engineer - Intermediate (Hybrid...
25,Data Analyst,indeed,FinOps Analyst,Yoco Technologies,False,2026-06-09,Cape Town,Cape Town,Mid-Level,Full-Time,"Who we are Yoco was founded in 2015, and we’ve..."
26,Data Analyst,indeed,Commercial Finance Business Analyst,Avery Dennison,False,2026-06-09,Somerset West,Cape Town,Mid-Level,Full-Time,Company Description ABOUT AVERY DENNISON CORPO...
27,Data Analyst,indeed,Quality Analyst,Stowe Holdings (Pty) Ltd.,False,2026-06-09,Goodwood,Cape Town,Mid-Level,Full-Time,"Please note, this is a non-technical role in a..."
28,Data Analyst,indeed,"WIM Investigator II, AmSec Workplace Incident ...",Amazon.com,False,2026-06-08,Cape Town,Cape Town,Mid-Level,Full-Time,DESCRIPTION The Workplace Incident Management ...
29,Data Analyst,indeed,Supply Chain Analyst,The HEINEKEN Company,False,2026-06-08,Stellenbosch,Stellenbosch,Mid-Level,Full-Time,Purpose of the job | Be a first-class business...
30,Data Analyst,indeed,Data Management Analyst,MRI Software,False,2026-06-08,Cape Town,Cape Town,Mid-Level,Full-Time,Position Overview: We are looking for an entry...
31,Data Analyst,indeed,Junior Credit Risk Analyst,Weaver Fintech Ltd,False,2026-06-08,Cape Town,Cape Town,Junior,Unknown,Weaver FinTech Group is a leading digital fina...
32,Data Analyst,indeed,Sales Analyst (6 Month Contract),Kenvue,False,2026-06-08,Cape Town,Cape Town,Mid-Level,Unknown,Kenvue is currently recruiting for a: Sales An...
33,Data Analyst,indeed,CRM & Data Analyst,Networking Mania,False,2026-06-08,Sea Point,Cape Town,Mid-Level,Unknown,Job Title: CRM & Data Analyst Location: Cape T...
34,Data Analyst,indeed,Realtime Analyst,WNS Global Services,False,2026-06-08,Milnerton,Cape Town,Mid-Level,Full-Time,"Company Description WNS, part of Capgemini, is..."
35,Data Analyst,indeed,Yield Analyst,LE BOAT,False,2026-06-05,Cape Town,Cape Town,Mid-Level,Full-Time,"Le Boat, part of the Travelopia group , is the..."
36,Data Analyst,indeed,Quality Analyst - Financial Services - Onsite ...,Concentrix,False,2026-06-04,Cape Town,Cape Town,Mid-Level,Full-Time,"Quality Analyst – On-site, Cape Town At Concen..."
37,Data Analyst,indeed,Senior Retail Media Insights Analyst,ShopriteX,False,2026-06-01,Brackenfell,Cape Town,Senior,Full-Time,Senior Retail Media Insights Analyst Role Purp...
38,Data Analyst,indeed,Digital Data Analyst (Rainmaker Media),ShopriteX,False,2026-06-01,Brackenfell,Cape Town,Mid-Level,Full-Time,Value Proposition Powered by Africa's largest ...
39,Data Analyst,indeed,Business Process Analyst,Lula,False,2026-06-01,Cape Town,Cape Town,Mid-Level,Full-Time,We are looking for a collaborative mid-level B...
40,Data Analyst,linkedin,Data Analyst,ExecutivePlacements.com,False,2026-06-12,Cape Town,Cape Town,Mid-Level,Unknown,NaN
41,Data Analyst,linkedin,Business Intelligence Analyst (Retail) - Corpo...,Trending Talent Solutions,False,2026-06-12,City of Cape Town,Cape Town,Mid-Level,Unknown,NaN
42,Data Analyst,linkedin,Data Engineer (Senior),Parvana,False,2026-06-12,Bellville,Cape Town,Senior,Unknown,NaN
43,Data Analyst,linkedin,Applied Research Engineer,Duku AI,False,2026-06-12,Cape Town,Cape Town,Mid-Level,Unknown,NaN
44,Data Analyst,linkedin,Senior Data Analyst,Capitec,False,2026-06-11,Stellenbosch,Stellenbosch,Senior,Unknown,NaN
45,Data Analyst,linkedin,BI Analyst,ExecutivePlacements.com,False,2026-06-11,Cape Town,Cape Town,Mid-Level,Unknown,NaN
46,Data Analyst,linkedin,Collections and Payments Analytics Specialist ...,Black Pen Recruitment,False,2026-06-11,City of Cape Town,Cape Town,Mid-Level,Unknown,NaN
47,Data Analyst,linkedin,Data Analyst,Network Recruitment,False,2026-06-10,Stellenbosch,Stellenbosch,Mid-Level,Unknown,NaN
48,Data Analyst,linkedin,Business Intelligence Analyst,Communicate Recruitment,False,2026-06-10,City of Cape Town,Cape Town,Mid-Level,Unknown,NaN
49,Data Analyst,linkedin,Business Intelligence Analyst,Network Recruitment,False,2026-06-10,City of Cape Town,Cape Town,Mid-Level,Unknown,NaN
50,Data Analyst,linkedin,Senior Space Analyst,Woolworths,False,2026-06-10,Cape Town,Cape Town,Senior,Unknown,NaN
51,Data Analyst,linkedin,Data Analyst,Network International,False,2026-06-09,Cape Town,Cape Town,Mid-Level,Unknown,NaN
52,Data Analyst,linkedin,Market Research Data Analyst,Potentiam Ltd,False,2026-06-09,City of Cape Town,Cape Town,Mid-Level,Unknown,NaN
53,Data Analyst,linkedin,"Data Analyst (Marketing Analytics, Bangkok Bas...",Agoda,False,2026-06-09,Cape Town,Cape Town,Mid-Level,Unknown,NaN
54,Data Analyst,linkedin,Data Engineer - Databricks - July Start,Embelo,False,2026-06-08,City of Cape Town,Cape Town,Mid-Level,Unknown,NaN
55,Data Analyst,linkedin,Fundraising Systems and Data Specialist (m/f/d),FOUR PAWS,False,2026-06-08,City of Cape Town,Cape Town,Mid-Level,Unknown,NaN
56,Data Analyst,linkedin,Data Analyst,DigiOutsource,False,2026-06-07,Cape Town,Cape Town,Mid-Level,Unknown,NaN
57,Data Analyst,linkedin,Junior Data Engineer,ExecutivePlacements.com,False,2026-06-07,Cape Town,Cape Town,Junior,Unknown,NaN
58,Data Analyst,linkedin,Business Data Analyst,ExecutivePlacements.com,False,2026-06-06,Cape Town,Cape Town,Mid-Level,Unknown,NaN
59,Data Analyst,linkedin,Data & Insights Analyst,Vivo Energy,False,2026-06-05,Cape Town,Cape Town,Mid-Level,Unknown,NaN
60,Data Analyst,linkedin,Yield Analyst,Le Boat,False,2026-06-05,Cape Town,Cape Town,Mid-Level,Unknown,NaN
61,Data Analyst,linkedin,Dashboard & Reporting Specialist,Hunterlodge Advertising,False,2026-06-05,City of Cape Town,Cape Town,Mid-Level,Unknown,NaN
62,Data Analyst,linkedin,Director: Provincial Spatial Information (Ref ...,Western Cape Government,False,2026-06-05,Cape Town,Cape Town,Mid-Level,Unknown,NaN
63,Data Analyst,linkedin,Senior Insights Manager,Mr D,False,2026-06-05,City of Cape Town,Cape Town,Senior,Unknown,NaN
64,Data Analyst,linkedin,Data Engineer,Communicate Recruitment,False,2026-06-04,City of Cape Town,Cape Town,Mid-Level,Unknown,NaN
65,Data Analyst,linkedin,Business Intelligence Developer,DigiOutsource,False,2026-06-03,Cape Town,Cape Town,Mid-Level,Unknown,NaN
66,Data Analyst,linkedin,Quantitative Analyst,Capitec,False,2026-06-03,Stellenbosch,Stellenbosch,Mid-Level,Unknown,NaN
67,Data Analyst,linkedin,Senior Data Engineer,KingMakers,False,2026-06-03,Cape Town,Cape Town,Senior,Unknown,NaN
68,Data Analyst,linkedin,Client Reporting Analyst (12-month contract) –...,ExecutivePlacements.com,False,2026-06-03,Cape Town,Cape Town,Mid-Level,Unknown,NaN
69,Data Analyst,linkedin,Remote Data/Image Collector (No Experience Nee...,TransPerfect,True,2026-06-02,City of Cape Town,Cape Town,Mid-Level,Unknown,NaN
70,Data Analyst,linkedin,Revenue Analysis & Performance Leader,Apex Group Ltd,False,2026-06-02,Cape Town,Cape Town,Mid-Level,Unknown,NaN
71,Data Analyst,linkedin,Data Analyst II_Pipeline,Capitec,False,2026-06-01,Stellenbosch,Stellenbosch,Mid-Level,Unknown,NaN
72,Data Analyst,linkedin,SAf Software Developer,SMEC (an SJ Group company),False,Unknown,Cape Town,Cape Town,Mid-Level,Unknown,NaN
73,Data Analyst,linkedin,Senior Collections Specialist (Business Intell...,Network Recruitment International,False,Unknown,City of Cape Town,Cape Town,Senior,Unknown,NaN
74,Data Analyst,linkedin,Senior Onboarding Analyst,BVNK,False,Unknown,Cape Town,Cape Town,Senior,Unknown,NaN
75,Data Scientist,indeed,CapeNature – SANCCOB Marine Field Ranger,SANCCOB,False,2026-06-12,Cape Town,Cape Town,Mid-Level,Full-Time,The Southern African Foundation for the Conser...
76,Data Scientist,indeed,SANCCOB Coastal Field Ranger,SANCCOB,False,2026-06-05,Cape Town,Cape Town,Mid-Level,Full-Time,SANCCOB seeks to employ a full-time Coastal Fi...
77,Data Scientist,indeed,Platform Data Engineer,Confluent,False,2026-06-02,Cape Town,Cape Town,Mid-Level,Unknown,"Platform Data Engineer ( Hybrid Pinelands, Cap..."
78,Data Scientist,indeed,Data Scientist,PBT Group,False,2026-06-01,Stellenbosch,Stellenbosch,Mid-Level,Unknown,Employment Type Contract Experience 5 to 25 ye...
79,Data Scientist,linkedin,Machine Learning Engineer,Duku AI,False,2026-06-12,Cape Town,Cape Town,Mid-Level,Unknown,NaN
80,Data Scientist,linkedin,AI Engineer,GVW Group,False,2026-06-12,Durbanville,Cape Town,Mid-Level,Unknown,NaN
81,Data Scientist,linkedin,Software Engineer (Front-End),DigiOutsource,False,2026-06-12,Cape Town,Cape Town,Mid-Level,Unknown,NaN
82,Data Scientist,linkedin,Software Engineer (Full Stack),DigiOutsource,False,2026-06-12,Cape Town,Cape Town,Mid-Level,Unknown,NaN
83,Data Scientist,linkedin,Junior Planning Analytics (TM1) Developer,DigiOutsource,False,2026-06-12,Cape Town,Cape Town,Junior,Unknown,NaN
84,Data Scientist,linkedin,"Intermediate Data Scientist - Cape Town, Hybrid",Ada Meher,False,2026-06-11,City of Cape Town,Cape Town,Mid-Level,Unknown,NaN
85,Data Scientist,linkedin,Senior Data Engineer,Keyrock,False,2026-06-11,Cape Town,Cape Town,Senior,Unknown,NaN
86,Data Scientist,linkedin,Analytics Engineer,Pargo,False,2026-06-10,Cape Town,Cape Town,Mid-Level,Unknown,NaN
87,Data Scientist,linkedin,Actuarial Specialist,Outsized,False,2026-06-10,City of Cape Town,Cape Town,Mid-Level,Unknown,NaN
88,Data Scientist,linkedin,Data Scientist (Pipeline),Capita,False,2026-06-09,Cape Town,Cape Town,Mid-Level,Unknown,NaN
89,Data Scientist,linkedin,Specialist Data Scientist,Old Mutual South Africa,False,2026-06-09,Pinelands,Cape Town,Mid-Level,Unknown,NaN
90,Data Scientist,linkedin,Senior Credit Risk Data Scientist,Oze,False,2026-06-09,City of Cape Town,Cape Town,Senior,Unknown,NaN
91,Data Scientist,linkedin,Manager: Data and Analytics,Capitec,False,2026-06-09,Cape Town,Cape Town,Mid-Level,Unknown,NaN
92,Data Scientist,linkedin,Senior Test Engineer,Ozow,False,2026-06-09,Cape Town,Cape Town,Senior,Unknown,NaN
93,Data Scientist,linkedin,Xperts: Senior Java Engineer (Data Engineering),Inspired Testing,False,2026-06-08,Cape Town,Cape Town,Senior,Unknown,NaN
94,Data Scientist,linkedin,DevSecOps Engineer - Cape Town,Morae,False,2026-06-08,City of Cape Town,Cape Town,Mid-Level,Unknown,NaN
95,Data Scientist,linkedin,Principal Engineer,takealot.com,False,2026-06-08,Cape Town,Cape Town,Mid-Level,Unknown,NaN
96,Data Scientist,linkedin,Senior Data / ML Engineer,Powerfleet,False,2026-06-07,Cape Town,Cape Town,Senior,Unknown,NaN
97,Data Scientist,linkedin,AI Data Platform Engineer,Storyteq,False,2026-06-07,Cape Town,Cape Town,Mid-Level,Unknown,NaN
98,Data Scientist,linkedin,QA Engineer,ExecutivePlacements.com,False,2026-06-06,Cape Town,Cape Town,Mid-Level,Unknown,NaN
99,Data Scientist,linkedin,BI Engineer: Takealot Group,takealot.com,False,2026-06-04,Cape Town,Cape Town,Mid-Level,Unknown,NaN
100,Data Scientist,linkedin,Software Engineer,ExecutivePlacements.com,False,2026-06-04,Cape Town,Cape Town,Mid-Level,Unknown,NaN
101,Data Scientist,linkedin,Data Scientist,ExecutivePlacements.com,False,2026-06-02,Stellenbosch,Stellenbosch,Mid-Level,Unknown,NaN
102,Data Scientist,linkedin,Research Development Engineer: Innovation (Int...,Clickatell,False,2026-06-02,Cape Town,Cape Town,Mid-Level,Unknown,NaN
103,Data Scientist,linkedin,AI ENGINEER – REMOTE (CAPE TOWN),SASSO CONSULTING,True,2026-06-02,Cape Town,Cape Town,Mid-Level,Unknown,NaN
104,Data Scientist,linkedin,Senior Engineer,Salt,False,2026-06-02,City of Cape Town,Cape Town,Senior,Unknown,NaN
105,Data Scientist,linkedin,Machine Learning Engineer,Sanlam,False,2026-06-01,Cape Town,Cape Town,Mid-Level,Unknown,NaN
106,Data Scientist,linkedin,Quantitative Analyst,Communicate Recruitment,False,2026-06-01,City of Cape Town,Cape Town,Mid-Level,Unknown,NaN
107,Data Scientist,linkedin,Data Engineer - L3,Advania UK,False,Unknown,Cape Town,Cape Town,Mid-Level,Unknown,NaN
108,Data Engineer,indeed,Technical Support Engineer,Root Platform,False,2026-06-12,Cape Town,Cape Town,Mid-Level,Unknown,Mission As a Technical Support Engineer at Roo...
109,Data Engineer,indeed,Senior Software Engineer (Full-Stack),Betway Group,False,2026-06-12,Cape Town,Cape Town,Senior,Full-Time,Kick-start your career in the online gaming wo...
110,Data Engineer,indeed,Software Development Engineer – 2026,Amazon.com,False,2026-06-12,Cape Town,Cape Town,Mid-Level,Full-Time,DESCRIPTION Do you want to solve real customer...
111,Data Engineer,indeed,"Chief Engineer, DCEO",Amazon.com,False,2026-06-12,Cape Town,Cape Town,Mid-Level,Full-Time,DESCRIPTION AWS Data Centers run critical IT i...
112,Data Engineer,indeed,Data Engineer,COLLINSON,False,2026-06-11,Cape Town,Cape Town,Mid-Level,Unknown,"Collinson is the global, privately-owned compa..."
113,Data Engineer,indeed,Handyman - Protea Hotel by Marriott Breakwater...,Marriott International,True,2026-06-11,Cape Town,Cape Town,Mid-Level,Full-Time,Additional Information Job Number 26071467 Job...
114,Data Engineer,indeed,Software Engineering Manager,SkyeBiz,False,2026-06-11,Cape Town,Cape Town,Mid-Level,Full-Time,Location: Cape Town Salary: 80k-135k per month...
115,Data Engineer,indeed,DevOps Engineer,Unknown,True,2026-06-11,Century City,Cape Town,Mid-Level,Full-Time,About GLI At GLI our software development team...
116,Data Engineer,indeed,Systems Operations Engineer,Unknown,True,2026-06-11,Century City,Cape Town,Mid-Level,Full-Time,About GLI At GLI our software development team...
117,Data Engineer,indeed,Junior Sales Manager / Engineer,Exactocraft,False,2026-06-11,Blackheath,Cape Town,Junior,Unknown,"Position Overview We are seeking a dynamic, te..."
118,Data Engineer,indeed,Principal AWS Cloud Architect,NTT DATA,False,2026-06-11,Cape Town,Cape Town,Mid-Level,Full-Time,Make an impact with NTT DATA Join a company th...
119,Data Engineer,indeed,Mechanical Engineer (Public Health/ Wet Services),WSP,False,2026-06-10,Cape Town,Cape Town,Mid-Level,Unknown,WSP is one of Africa’s most diverse consulting...
120,Data Engineer,indeed,Technical Lead,Stowe Holdings (Pty) Ltd.,False,2026-06-10,Cape Town,Cape Town,Mid-Level,Full-Time,Job Profile The purpose of the job is to provi...
121,Data Engineer,indeed,Network Engineer,Hungry Lion Fast Foods,True,2026-06-10,Stellenbosch,Stellenbosch,Mid-Level,Full-Time,Purpose of the Role The Network Engineer is re...
122,Data Engineer,indeed,Project Engineer,Pragma,False,2026-06-10,Cape Town,Cape Town,Mid-Level,Unknown,"Job Advert Summary At Pragma, we don’t just fo..."
123,Data Engineer,indeed,Junior Business Optimisation Engineer,OneNebula,True,2026-06-09,Milnerton,Cape Town,Junior,Unknown,Do you want to be part of a dynamic team const...
124,Data Engineer,indeed,Legal Operations Manager,BVNK,True,2026-06-09,Cape Town,Cape Town,Mid-Level,Unknown,About us: We believe the next generation of fi...
125,Data Engineer,indeed,Principal Professional Officer - Business Impr...,City of Cape Town,False,2026-06-09,Cape Town,Cape Town,Mid-Level,Unknown,ELIGIBILITY All suitable applicants CLOSING DA...
126,Data Engineer,indeed,1.5 Line Engineer (24-hour rotational shift),Scale Shore Consulting,False,2026-06-09,Cape Town,Cape Town,Mid-Level,Full-Time,About the Role: We are seeking a motivated and...
127,Data Engineer,indeed,Product Manager,Rank Group,False,2026-06-08,Cape Town,Cape Town,Mid-Level,Unknown,"Just us at Rank Interactive Rank Interactive, ..."
128,Data Engineer,indeed,Engineering Manager,2U,False,2026-06-08,Cape Town,Cape Town,Mid-Level,Full-Time,"At 2U, we are all in on purpose. We are motiva..."
129,Data Engineer,indeed,Senior Software Engineer,Kurtosys,True,2026-06-08,Claremont,Cape Town,Senior,Full-Time,About the Role Kurtosys builds the platform th...
130,Data Engineer,indeed,Technical Support Engineer,Ozow,True,2026-06-08,Cape Town,Cape Town,Mid-Level,Unknown,Meet Ozow: Ozow is a leading fintech company t...

## Making the titles look neater.

In [22]:
df.rename(columns={"search_role":"Search Word", "site":"Website", "title":"Title", "company":"Company", "is_remote":"Remote", "date_posted":"Date Posted"}, inplace=True)
df

,Search Word,Website,Title,Company,Remote,Date Posted,Location,City,Level,Job Type,Description
0,Data Analyst,indeed,Claims Risk Analyst,Momentum Health,False,2026-06-12,Bellville,Cape Town,Mid-Level,Unknown,Introduction Through our client-facing brands ...
1,Data Analyst,indeed,Senior Application Support Analyst (SQL-focused),MRI Software,False,2026-06-12,Cape Town,Cape Town,Senior,Full-Time,MRI Software is seeking a Senior Application S...
2,Data Analyst,indeed,SOC Analyst,Zappi,False,2026-06-12,Cape Town,Cape Town,Mid-Level,Full-Time,Description We believe in hiring analysts who ...
3,Data Analyst,indeed,Chief Delivery Officer (CDO),NJ Placement Consulting,False,2026-06-12,Rosebank,Cape Town,Mid-Level,Full-Time,Overview Amazing chance to join a Software Dev...
4,Data Analyst,indeed,Business Intelligence Analyst,LekkeSlaap,True,2026-06-12,Cape Town,Cape Town,Mid-Level,Full-Time,Bring 3+ years of proven experience in busines...
5,Data Analyst,indeed,Technical Product Analyst,Sanlam,False,2026-06-12,Bellville,Cape Town,Mid-Level,Unknown,Who are we? Sanlam Life and Savings (SLS) is f...
6,Data Analyst,indeed,Utilities Analyst,FPG Property Management,False,2026-06-12,Cape Town,Cape Town,Mid-Level,Full-Time,PURPOSE OF JOB The Utilities Analyst is respon...
7,Data Analyst,indeed,Data Integrations Specialist - Client Focus,Healix Group of Companies,False,2026-06-12,Cape Town,Cape Town,Mid-Level,Full-Time,About the role We’re looking for a Data Integr...
8,Data Analyst,indeed,Senior BI Analyst - Team Leader,Auto Trader South Africa,True,2026-06-12,Nuweland,Cape Town,Senior,Unknown,Senior BI Analyst - Team Leader Remote We're l...
9,Data Analyst,indeed,Domain / Product owner - HR systems,Unifi,False,2026-06-12,Stellenbosch,Stellenbosch,Mid-Level,Unknown,About Unifi Boldly different. Fiercely human. ...
10,Data Analyst,indeed,Data Analyst,Crisis24,False,2026-06-11,Cape Town,Cape Town,Mid-Level,Full-Time,Who We Are Looking For The Data Analyst resear...
11,Data Analyst,indeed,Customer Success Reporting Analyst,Mama Money,False,2026-06-11,Cape Town,Cape Town,Mid-Level,Full-Time,Who we are: Mama Money is a growth-stage finte...
12,Data Analyst,indeed,Legal Content Analyst,RELX Group,False,2026-06-11,Cape Town,Cape Town,Mid-Level,Full-Time,"Are you passionate about shaping accurate, tim..."
13,Data Analyst,indeed,Legal Content Analyst,LexisNexis Legal & Professional,False,2026-06-11,Cape Town,Cape Town,Mid-Level,Full-Time,"Are you passionate about shaping accurate, tim..."
14,Data Analyst,indeed,Business Intelligence Analyst,Queenspark Pty Ltd,False,2026-06-11,Wynberg,Cape Town,Mid-Level,Full-Time,Title: Business Intelligence Analyst Location:...
15,Data Analyst,indeed,Conflict Analyst,Frontline Managed Services,False,2026-06-10,Cape Town,Cape Town,Mid-Level,Unknown,Welcome to Frontline Managed Services® – where...
16,Data Analyst,indeed,Paid Media Analyst,Clever Profits,True,2026-06-10,Cape Town,Cape Town,Mid-Level,Full-Time,Description CleverProfits is a financial servi...
17,Data Analyst,indeed,Supply Chain Process Analyst,woolworths,False,2026-06-10,Cape Town,Cape Town,Mid-Level,Unknown,Job Advert Summary Join Woolworths as a Supply...
18,Data Analyst,indeed,BUSINESS ANALYST (INDUSTRIAL ENGINEER),Cartrack SA,False,2026-06-10,Cape Town,Cape Town,Mid-Level,Unknown,Listing reference: cartr_000815 Listing status...
19,Data Analyst,indeed,"Manager, Grade 1: Spatial Analyst",South African National Biodiversity Institute,False,2026-06-10,Cape Town,Cape Town,Mid-Level,Unknown,"Manager, Grade 1: Spatial Analyst Salary Level..."
20,Data Analyst,indeed,Integration Engineer/Developer,Cape Union Mart,False,2026-06-10,Cape Town,Cape Town,Mid-Level,Unknown,Why Join Cape Union Mart? Cape Union Mart is S...
21,Data Analyst,indeed,"Insight Analyst (Professional, BI Specialist (...",Concentrix,False,2026-06-09,Cape Town,Cape Town,Mid-Level,Full-Time,JOB PURPOSE To support the development and imp...
22,Data Analyst,indeed,Investment Guidelines Analyst (Contractor),Futuregrowth,False,2026-06-09,Southern Suburbs,Cape Town,Mid-Level,Part-Time,Purpose of the position A vacancy has arisen f...
23,Data Analyst,indeed,FinOps Analyst,Yoco,False,2026-06-09,Cape Town,Cape Town,Mid-Level,Unknown,"Who we are Yoco was founded in 2015, and we’ve..."
24,Data Analyst,indeed,Databricks Data Engineer,Confluent,False,2026-06-09,Cape Town,Cape Town,Mid-Level,Unknown,Position: Data Engineer - Intermediate (Hybrid...
25,Data Analyst,indeed,FinOps Analyst,Yoco Technologies,False,2026-06-09,Cape Town,Cape Town,Mid-Level,Full-Time,"Who we are Yoco was founded in 2015, and we’ve..."
26,Data Analyst,indeed,Commercial Finance Business Analyst,Avery Dennison,False,2026-06-09,Somerset West,Cape Town,Mid-Level,Full-Time,Company Description ABOUT AVERY DENNISON CORPO...
27,Data Analyst,indeed,Quality Analyst,Stowe Holdings (Pty) Ltd.,False,2026-06-09,Goodwood,Cape Town,Mid-Level,Full-Time,"Please note, this is a non-technical role in a..."
28,Data Analyst,indeed,"WIM Investigator II, AmSec Workplace Incident ...",Amazon.com,False,2026-06-08,Cape Town,Cape Town,Mid-Level,Full-Time,DESCRIPTION The Workplace Incident Management ...
29,Data Analyst,indeed,Supply Chain Analyst,The HEINEKEN Company,False,2026-06-08,Stellenbosch,Stellenbosch,Mid-Level,Full-Time,Purpose of the job | Be a first-class business...
30,Data Analyst,indeed,Data Management Analyst,MRI Software,False,2026-06-08,Cape Town,Cape Town,Mid-Level,Full-Time,Position Overview: We are looking for an entry...
31,Data Analyst,indeed,Junior Credit Risk Analyst,Weaver Fintech Ltd,False,2026-06-08,Cape Town,Cape Town,Junior,Unknown,Weaver FinTech Group is a leading digital fina...
32,Data Analyst,indeed,Sales Analyst (6 Month Contract),Kenvue,False,2026-06-08,Cape Town,Cape Town,Mid-Level,Unknown,Kenvue is currently recruiting for a: Sales An...
33,Data Analyst,indeed,CRM & Data Analyst,Networking Mania,False,2026-06-08,Sea Point,Cape Town,Mid-Level,Unknown,Job Title: CRM & Data Analyst Location: Cape T...
34,Data Analyst,indeed,Realtime Analyst,WNS Global Services,False,2026-06-08,Milnerton,Cape Town,Mid-Level,Full-Time,"Company Description WNS, part of Capgemini, is..."
35,Data Analyst,indeed,Yield Analyst,LE BOAT,False,2026-06-05,Cape Town,Cape Town,Mid-Level,Full-Time,"Le Boat, part of the Travelopia group , is the..."
36,Data Analyst,indeed,Quality Analyst - Financial Services - Onsite ...,Concentrix,False,2026-06-04,Cape Town,Cape Town,Mid-Level,Full-Time,"Quality Analyst – On-site, Cape Town At Concen..."
37,Data Analyst,indeed,Senior Retail Media Insights Analyst,ShopriteX,False,2026-06-01,Brackenfell,Cape Town,Senior,Full-Time,Senior Retail Media Insights Analyst Role Purp...
38,Data Analyst,indeed,Digital Data Analyst (Rainmaker Media),ShopriteX,False,2026-06-01,Brackenfell,Cape Town,Mid-Level,Full-Time,Value Proposition Powered by Africa's largest ...
39,Data Analyst,indeed,Business Process Analyst,Lula,False,2026-06-01,Cape Town,Cape Town,Mid-Level,Full-Time,We are looking for a collaborative mid-level B...
40,Data Analyst,linkedin,Data Analyst,ExecutivePlacements.com,False,2026-06-12,Cape Town,Cape Town,Mid-Level,Unknown,NaN
41,Data Analyst,linkedin,Business Intelligence Analyst (Retail) - Corpo...,Trending Talent Solutions,False,2026-06-12,City of Cape Town,Cape Town,Mid-Level,Unknown,NaN
42,Data Analyst,linkedin,Data Engineer (Senior),Parvana,False,2026-06-12,Bellville,Cape Town,Senior,Unknown,NaN
43,Data Analyst,linkedin,Applied Research Engineer,Duku AI,False,2026-06-12,Cape Town,Cape Town,Mid-Level,Unknown,NaN
44,Data Analyst,linkedin,Senior Data Analyst,Capitec,False,2026-06-11,Stellenbosch,Stellenbosch,Senior,Unknown,NaN
45,Data Analyst,linkedin,BI Analyst,ExecutivePlacements.com,False,2026-06-11,Cape Town,Cape Town,Mid-Level,Unknown,NaN
46,Data Analyst,linkedin,Collections and Payments Analytics Specialist ...,Black Pen Recruitment,False,2026-06-11,City of Cape Town,Cape Town,Mid-Level,Unknown,NaN
47,Data Analyst,linkedin,Data Analyst,Network Recruitment,False,2026-06-10,Stellenbosch,Stellenbosch,Mid-Level,Unknown,NaN
48,Data Analyst,linkedin,Business Intelligence Analyst,Communicate Recruitment,False,2026-06-10,City of Cape Town,Cape Town,Mid-Level,Unknown,NaN
49,Data Analyst,linkedin,Business Intelligence Analyst,Network Recruitment,False,2026-06-10,City of Cape Town,Cape Town,Mid-Level,Unknown,NaN
50,Data Analyst,linkedin,Senior Space Analyst,Woolworths,False,2026-06-10,Cape Town,Cape Town,Senior,Unknown,NaN
51,Data Analyst,linkedin,Data Analyst,Network International,False,2026-06-09,Cape Town,Cape Town,Mid-Level,Unknown,NaN
52,Data Analyst,linkedin,Market Research Data Analyst,Potentiam Ltd,False,2026-06-09,City of Cape Town,Cape Town,Mid-Level,Unknown,NaN
53,Data Analyst,linkedin,"Data Analyst (Marketing Analytics, Bangkok Bas...",Agoda,False,2026-06-09,Cape Town,Cape Town,Mid-Level,Unknown,NaN
54,Data Analyst,linkedin,Data Engineer - Databricks - July Start,Embelo,False,2026-06-08,City of Cape Town,Cape Town,Mid-Level,Unknown,NaN
55,Data Analyst,linkedin,Fundraising Systems and Data Specialist (m/f/d),FOUR PAWS,False,2026-06-08,City of Cape Town,Cape Town,Mid-Level,Unknown,NaN
56,Data Analyst,linkedin,Data Analyst,DigiOutsource,False,2026-06-07,Cape Town,Cape Town,Mid-Level,Unknown,NaN
57,Data Analyst,linkedin,Junior Data Engineer,ExecutivePlacements.com,False,2026-06-07,Cape Town,Cape Town,Junior,Unknown,NaN
58,Data Analyst,linkedin,Business Data Analyst,ExecutivePlacements.com,False,2026-06-06,Cape Town,Cape Town,Mid-Level,Unknown,NaN
59,Data Analyst,linkedin,Data & Insights Analyst,Vivo Energy,False,2026-06-05,Cape Town,Cape Town,Mid-Level,Unknown,NaN
60,Data Analyst,linkedin,Yield Analyst,Le Boat,False,2026-06-05,Cape Town,Cape Town,Mid-Level,Unknown,NaN
61,Data Analyst,linkedin,Dashboard & Reporting Specialist,Hunterlodge Advertising,False,2026-06-05,City of Cape Town,Cape Town,Mid-Level,Unknown,NaN
62,Data Analyst,linkedin,Director: Provincial Spatial Information (Ref ...,Western Cape Government,False,2026-06-05,Cape Town,Cape Town,Mid-Level,Unknown,NaN
63,Data Analyst,linkedin,Senior Insights Manager,Mr D,False,2026-06-05,City of Cape Town,Cape Town,Senior,Unknown,NaN
64,Data Analyst,linkedin,Data Engineer,Communicate Recruitment,False,2026-06-04,City of Cape Town,Cape Town,Mid-Level,Unknown,NaN
65,Data Analyst,linkedin,Business Intelligence Developer,DigiOutsource,False,2026-06-03,Cape Town,Cape Town,Mid-Level,Unknown,NaN
66,Data Analyst,linkedin,Quantitative Analyst,Capitec,False,2026-06-03,Stellenbosch,Stellenbosch,Mid-Level,Unknown,NaN
67,Data Analyst,linkedin,Senior Data Engineer,KingMakers,False,2026-06-03,Cape Town,Cape Town,Senior,Unknown,NaN
68,Data Analyst,linkedin,Client Reporting Analyst (12-month contract) –...,ExecutivePlacements.com,False,2026-06-03,Cape Town,Cape Town,Mid-Level,Unknown,NaN
69,Data Analyst,linkedin,Remote Data/Image Collector (No Experience Nee...,TransPerfect,True,2026-06-02,City of Cape Town,Cape Town,Mid-Level,Unknown,NaN
70,Data Analyst,linkedin,Revenue Analysis & Performance Leader,Apex Group Ltd,False,2026-06-02,Cape Town,Cape Town,Mid-Level,Unknown,NaN
71,Data Analyst,linkedin,Data Analyst II_Pipeline,Capitec,False,2026-06-01,Stellenbosch,Stellenbosch,Mid-Level,Unknown,NaN
72,Data Analyst,linkedin,SAf Software Developer,SMEC (an SJ Group company),False,Unknown,Cape Town,Cape Town,Mid-Level,Unknown,NaN
73,Data Analyst,linkedin,Senior Collections Specialist (Business Intell...,Network Recruitment International,False,Unknown,City of Cape Town,Cape Town,Senior,Unknown,NaN
74,Data Analyst,linkedin,Senior Onboarding Analyst,BVNK,False,Unknown,Cape Town,Cape Town,Senior,Unknown,NaN
75,Data Scientist,indeed,CapeNature – SANCCOB Marine Field Ranger,SANCCOB,False,2026-06-12,Cape Town,Cape Town,Mid-Level,Full-Time,The Southern African Foundation for the Conser...
76,Data Scientist,indeed,SANCCOB Coastal Field Ranger,SANCCOB,False,2026-06-05,Cape Town,Cape Town,Mid-Level,Full-Time,SANCCOB seeks to employ a full-time Coastal Fi...
77,Data Scientist,indeed,Platform Data Engineer,Confluent,False,2026-06-02,Cape Town,Cape Town,Mid-Level,Unknown,"Platform Data Engineer ( Hybrid Pinelands, Cap..."
78,Data Scientist,indeed,Data Scientist,PBT Group,False,2026-06-01,Stellenbosch,Stellenbosch,Mid-Level,Unknown,Employment Type Contract Experience 5 to 25 ye...
79,Data Scientist,linkedin,Machine Learning Engineer,Duku AI,False,2026-06-12,Cape Town,Cape Town,Mid-Level,Unknown,NaN
80,Data Scientist,linkedin,AI Engineer,GVW Group,False,2026-06-12,Durbanville,Cape Town,Mid-Level,Unknown,NaN
81,Data Scientist,linkedin,Software Engineer (Front-End),DigiOutsource,False,2026-06-12,Cape Town,Cape Town,Mid-Level,Unknown,NaN
82,Data Scientist,linkedin,Software Engineer (Full Stack),DigiOutsource,False,2026-06-12,Cape Town,Cape Town,Mid-Level,Unknown,NaN
83,Data Scientist,linkedin,Junior Planning Analytics (TM1) Developer,DigiOutsource,False,2026-06-12,Cape Town,Cape Town,Junior,Unknown,NaN
84,Data Scientist,linkedin,"Intermediate Data Scientist - Cape Town, Hybrid",Ada Meher,False,2026-06-11,City of Cape Town,Cape Town,Mid-Level,Unknown,NaN
85,Data Scientist,linkedin,Senior Data Engineer,Keyrock,False,2026-06-11,Cape Town,Cape Town,Senior,Unknown,NaN
86,Data Scientist,linkedin,Analytics Engineer,Pargo,False,2026-06-10,Cape Town,Cape Town,Mid-Level,Unknown,NaN
87,Data Scientist,linkedin,Actuarial Specialist,Outsized,False,2026-06-10,City of Cape Town,Cape Town,Mid-Level,Unknown,NaN
88,Data Scientist,linkedin,Data Scientist (Pipeline),Capita,False,2026-06-09,Cape Town,Cape Town,Mid-Level,Unknown,NaN
89,Data Scientist,linkedin,Specialist Data Scientist,Old Mutual South Africa,False,2026-06-09,Pinelands,Cape Town,Mid-Level,Unknown,NaN
90,Data Scientist,linkedin,Senior Credit Risk Data Scientist,Oze,False,2026-06-09,City of Cape Town,Cape Town,Senior,Unknown,NaN
91,Data Scientist,linkedin,Manager: Data and Analytics,Capitec,False,2026-06-09,Cape Town,Cape Town,Mid-Level,Unknown,NaN
92,Data Scientist,linkedin,Senior Test Engineer,Ozow,False,2026-06-09,Cape Town,Cape Town,Senior,Unknown,NaN
93,Data Scientist,linkedin,Xperts: Senior Java Engineer (Data Engineering),Inspired Testing,False,2026-06-08,Cape Town,Cape Town,Senior,Unknown,NaN
94,Data Scientist,linkedin,DevSecOps Engineer - Cape Town,Morae,False,2026-06-08,City of Cape Town,Cape Town,Mid-Level,Unknown,NaN
95,Data Scientist,linkedin,Principal Engineer,takealot.com,False,2026-06-08,Cape Town,Cape Town,Mid-Level,Unknown,NaN
96,Data Scientist,linkedin,Senior Data / ML Engineer,Powerfleet,False,2026-06-07,Cape Town,Cape Town,Senior,Unknown,NaN
97,Data Scientist,linkedin,AI Data Platform Engineer,Storyteq,False,2026-06-07,Cape Town,Cape Town,Mid-Level,Unknown,NaN
98,Data Scientist,linkedin,QA Engineer,ExecutivePlacements.com,False,2026-06-06,Cape Town,Cape Town,Mid-Level,Unknown,NaN
99,Data Scientist,linkedin,BI Engineer: Takealot Group,takealot.com,False,2026-06-04,Cape Town,Cape Town,Mid-Level,Unknown,NaN
100,Data Scientist,linkedin,Software Engineer,ExecutivePlacements.com,False,2026-06-04,Cape Town,Cape Town,Mid-Level,Unknown,NaN
101,Data Scientist,linkedin,Data Scientist,ExecutivePlacements.com,False,2026-06-02,Stellenbosch,Stellenbosch,Mid-Level,Unknown,NaN
102,Data Scientist,linkedin,Research Development Engineer: Innovation (Int...,Clickatell,False,2026-06-02,Cape Town,Cape Town,Mid-Level,Unknown,NaN
103,Data Scientist,linkedin,AI ENGINEER – REMOTE (CAPE TOWN),SASSO CONSULTING,True,2026-06-02,Cape Town,Cape Town,Mid-Level,Unknown,NaN
104,Data Scientist,linkedin,Senior Engineer,Salt,False,2026-06-02,City of Cape Town,Cape Town,Senior,Unknown,NaN
105,Data Scientist,linkedin,Machine Learning Engineer,Sanlam,False,2026-06-01,Cape Town,Cape Town,Mid-Level,Unknown,NaN
106,Data Scientist,linkedin,Quantitative Analyst,Communicate Recruitment,False,2026-06-01,City of Cape Town,Cape Town,Mid-Level,Unknown,NaN
107,Data Scientist,linkedin,Data Engineer - L3,Advania UK,False,Unknown,Cape Town,Cape Town,Mid-Level,Unknown,NaN
108,Data Engineer,indeed,Technical Support Engineer,Root Platform,False,2026-06-12,Cape Town,Cape Town,Mid-Level,Unknown,Mission As a Technical Support Engineer at Roo...
109,Data Engineer,indeed,Senior Software Engineer (Full-Stack),Betway Group,False,2026-06-12,Cape Town,Cape Town,Senior,Full-Time,Kick-start your career in the online gaming wo...
110,Data Engineer,indeed,Software Development Engineer – 2026,Amazon.com,False,2026-06-12,Cape Town,Cape Town,Mid-Level,Full-Time,DESCRIPTION Do you want to solve real customer...
111,Data Engineer,indeed,"Chief Engineer, DCEO",Amazon.com,False,2026-06-12,Cape Town,Cape Town,Mid-Level,Full-Time,DESCRIPTION AWS Data Centers run critical IT i...
112,Data Engineer,indeed,Data Engineer,COLLINSON,False,2026-06-11,Cape Town,Cape Town,Mid-Level,Unknown,"Collinson is the global, privately-owned compa..."
113,Data Engineer,indeed,Handyman - Protea Hotel by Marriott Breakwater...,Marriott International,True,2026-06-11,Cape Town,Cape Town,Mid-Level,Full-Time,Additional Information Job Number 26071467 Job...
114,Data Engineer,indeed,Software Engineering Manager,SkyeBiz,False,2026-06-11,Cape Town,Cape Town,Mid-Level,Full-Time,Location: Cape Town Salary: 80k-135k per month...
115,Data Engineer,indeed,DevOps Engineer,Unknown,True,2026-06-11,Century City,Cape Town,Mid-Level,Full-Time,About GLI At GLI our software development team...
116,Data Engineer,indeed,Systems Operations Engineer,Unknown,True,2026-06-11,Century City,Cape Town,Mid-Level,Full-Time,About GLI At GLI our software development team...
117,Data Engineer,indeed,Junior Sales Manager / Engineer,Exactocraft,False,2026-06-11,Blackheath,Cape Town,Junior,Unknown,"Position Overview We are seeking a dynamic, te..."
118,Data Engineer,indeed,Principal AWS Cloud Architect,NTT DATA,False,2026-06-11,Cape Town,Cape Town,Mid-Level,Full-Time,Make an impact with NTT DATA Join a company th...
119,Data Engineer,indeed,Mechanical Engineer (Public Health/ Wet Services),WSP,False,2026-06-10,Cape Town,Cape Town,Mid-Level,Unknown,WSP is one of Africa’s most diverse consulting...
120,Data Engineer,indeed,Technical Lead,Stowe Holdings (Pty) Ltd.,False,2026-06-10,Cape Town,Cape Town,Mid-Level,Full-Time,Job Profile The purpose of the job is to provi...
121,Data Engineer,indeed,Network Engineer,Hungry Lion Fast Foods,True,2026-06-10,Stellenbosch,Stellenbosch,Mid-Level,Full-Time,Purpose of the Role The Network Engineer is re...
122,Data Engineer,indeed,Project Engineer,Pragma,False,2026-06-10,Cape Town,Cape Town,Mid-Level,Unknown,"Job Advert Summary At Pragma, we don’t just fo..."
123,Data Engineer,indeed,Junior Business Optimisation Engineer,OneNebula,True,2026-06-09,Milnerton,Cape Town,Junior,Unknown,Do you want to be part of a dynamic team const...
124,Data Engineer,indeed,Legal Operations Manager,BVNK,True,2026-06-09,Cape Town,Cape Town,Mid-Level,Unknown,About us: We believe the next generation of fi...
125,Data Engineer,indeed,Principal Professional Officer - Business Impr...,City of Cape Town,False,2026-06-09,Cape Town,Cape Town,Mid-Level,Unknown,ELIGIBILITY All suitable applicants CLOSING DA...
126,Data Engineer,indeed,1.5 Line Engineer (24-hour rotational shift),Scale Shore Consulting,False,2026-06-09,Cape Town,Cape Town,Mid-Level,Full-Time,About the Role: We are seeking a motivated and...
127,Data Engineer,indeed,Product Manager,Rank Group,False,2026-06-08,Cape Town,Cape Town,Mid-Level,Unknown,"Just us at Rank Interactive Rank Interactive, ..."
128,Data Engineer,indeed,Engineering Manager,2U,False,2026-06-08,Cape Town,Cape Town,Mid-Level,Full-Time,"At 2U, we are all in on purpose. We are motiva..."
129,Data Engineer,indeed,Senior Software Engineer,Kurtosys,True,2026-06-08,Claremont,Cape Town,Senior,Full-Time,About the Role Kurtosys builds the platform th...
130,Data Engineer,indeed,Technical Support Engineer,Ozow,True,2026-06-08,Cape Town,Cape Town,Mid-Level,Unknown,Meet Ozow: Ozow is a leading fintech company t...

## Outputting the file as 'wc_jobs_cleaned.csv'

In [23]:
df.to_csv('wc_jobs_cleaned.csv', index=False)