# Welcome to my cleaning phase of analysing data.

## Collection of the data:

After I collected/scraped real-world data from the web, we completed the first step of Collecting the Data.

The next step/phase is to Clean and Transform the Data so we can actually use it to make some insights.

## As always, Import the libraries.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("wc_data_jobs_20260613_1418.csv")
df

,search_role,site,title,company,location,job_type,is_remote,date_posted,min_amount,max_amount,currency,interval,description,job_url,scraped_at
0,Data Analyst,indeed,Claims Risk Analyst,Momentum Health,"Bellville, WC, ZA",NaN,False,2026-06-12,NaN,NaN,NaN,NaN,**Introduction**\nThrough our client\-facing b...,https://za.indeed.com/viewjob?jk=1c27bef7a3d49dc1,2026-06-13 14:18:21
1,Data Analyst,indeed,Senior Application Support Analyst (SQL-focused),MRI Software,"Cape Town, WC, ZA",fulltime,False,2026-06-12,NaN,NaN,NaN,NaN,MRI Software is seeking a Senior Application S...,https://za.indeed.com/viewjob?jk=8fa3139aef3495e3,2026-06-13 14:18:21
2,Data Analyst,indeed,SOC Analyst,Zappi,"Cape Town, WC, ZA",fulltime,False,2026-06-12,NaN,NaN,NaN,NaN,### **Description**\n\n \n\nWe believe in hir...,https://za.indeed.com/viewjob?jk=80aeb6ac4d43e5d3,2026-06-13 14:18:21
3,Data Analyst,indeed,Chief Delivery Officer (CDO),NJ Placement Consulting,"Rosebank, WC, ZA",fulltime,False,2026-06-12,NaN,NaN,NaN,NaN,##### **Overview**\n\n\nAmazing chance to join...,https://za.indeed.com/viewjob?jk=7077c05a2c616941,2026-06-13 14:18:21
4,Data Analyst,indeed,Business Intelligence Analyst,LekkeSlaap,"Cape Town, WC, ZA",fulltime,True,2026-06-12,NaN,NaN,NaN,NaN,Bring 3\+ years of proven experience in busine...,https://za.indeed.com/viewjob?jk=dd0f358d23d62da8,2026-06-13 14:18:21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284,Data Architect,linkedin,Lead Data Scientist,Network Recruitment,"City of Cape Town, Western Cape, South Africa",NaN,False,2026-06-02,NaN,NaN,NaN,NaN,NaN,https://www.linkedin.com/jobs/view/4419260216,2026-06-13 14:18:21
285,Data Architect,linkedin,Associate SAP Human Capital Solutions Architec...,Sanlam,"Cape Town, Western Cape, South Africa",NaN,False,2026-06-01,NaN,NaN,NaN,NaN,NaN,https://www.linkedin.com/jobs/view/4418761846,2026-06-13 14:18:21
286,Data Architect,linkedin,Modeller - OLAP/Automation,Circana,"Cape Town, Western Cape, South Africa",NaN,False,2026-06-01,NaN,NaN,NaN,NaN,NaN,https://www.linkedin.com/jobs/view/4309510396,2026-06-13 14:18:21
287,Data Architect,linkedin,Senior Data Analyst,impact.com,"Cape Town, Western Cape, South Africa",NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,https://www.linkedin.com/jobs/view/4385026286,2026-06-13 14:18:21
288,Data Architect,linkedin,Product Manager - Group Data Platform,Sanlam,"Cape Town, Western Cape, South Africa",NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,https://www.linkedin.com/jobs/view/4387336441,2026-06-13 14:18:21

# Changing 'date_posted' data type to date-time format.

In [3]:
df['date_posted'] = pd.to_datetime(df['date_posted']).dt.date
df['date_posted']

0      2026-06-12
1      2026-06-12
2      2026-06-12
3      2026-06-12
4      2026-06-12
          ...
284    2026-06-02
285    2026-06-01
286    2026-06-01
287           NaT
288           NaT
Name: date_posted, Length: 289, dtype: object

# Dropping columns with no values.

In [4]:
df = df.drop(columns=['min_amount' ,'max_amount','currency','interval', 'job_url', 'scraped_at'])
df

,search_role,site,title,company,location,job_type,is_remote,date_posted,description
0,Data Analyst,indeed,Claims Risk Analyst,Momentum Health,"Bellville, WC, ZA",NaN,False,2026-06-12,**Introduction**\nThrough our client\-facing b...
1,Data Analyst,indeed,Senior Application Support Analyst (SQL-focused),MRI Software,"Cape Town, WC, ZA",fulltime,False,2026-06-12,MRI Software is seeking a Senior Application S...
2,Data Analyst,indeed,SOC Analyst,Zappi,"Cape Town, WC, ZA",fulltime,False,2026-06-12,### **Description**\n\n \n\nWe believe in hir...
3,Data Analyst,indeed,Chief Delivery Officer (CDO),NJ Placement Consulting,"Rosebank, WC, ZA",fulltime,False,2026-06-12,##### **Overview**\n\n\nAmazing chance to join...
4,Data Analyst,indeed,Business Intelligence Analyst,LekkeSlaap,"Cape Town, WC, ZA",fulltime,True,2026-06-12,Bring 3\+ years of proven experience in busine...
...,...,...,...,...,...,...,...,...,...
284,Data Architect,linkedin,Lead Data Scientist,Network Recruitment,"City of Cape Town, Western Cape, South Africa",NaN,False,2026-06-02,NaN
285,Data Architect,linkedin,Associate SAP Human Capital Solutions Architec...,Sanlam,"Cape Town, Western Cape, South Africa",NaN,False,2026-06-01,NaN
286,Data Architect,linkedin,Modeller - OLAP/Automation,Circana,"Cape Town, Western Cape, South Africa",NaN,False,2026-06-01,NaN
287,Data Architect,linkedin,Senior Data Analyst,impact.com,"Cape Town, Western Cape, South Africa",NaN,False,NaT,NaN
288,Data Architect,linkedin,Product Manager - Group Data Platform,Sanlam,"Cape Town, Western Cape, South Africa",NaN,False,NaT,NaN

# Cleaning Locations.

### I notice there is location inconsistencies. For e.g. 3 different ways of telling it's in 'Cape Town'.

In [5]:
df.location.value_counts()

location
Cape Town, Western Cape, South Africa            115
Cape Town, WC, ZA                                 80
City of Cape Town, Western Cape, South Africa     38
Stellenbosch, Western Cape, South Africa          12
Bellville, WC, ZA                                  4
Stellenbosch, WC, ZA                               4
Somerset West, WC, ZA                              3
Milnerton, WC, ZA                                  3
Brackenfell, WC, ZA                                3
Bellville, Western Cape, South Africa              3
Century City, WC, ZA                               3
Pinelands, Western Cape, South Africa              2
Claremont, WC, ZA                                  2
Rosebank, WC, ZA                                   1
Nuweland, WC, ZA                                   1
Wynberg, WC, ZA                                    1
Southern Suburbs, WC, ZA                           1
Goodwood, WC, ZA                                   1
Sea Point, WC, ZA                                  1
Durbanville, Western Cape, South Africa            1
Blackheath, WC, ZA                                 1
Rondebosch, WC, ZA                                 1
Somerset West, Western Cape, South Africa          1
Paarl, WC, ZA                                      1
Darling, Western Cape, South Africa                1
Brackenfell, Western Cape, South Africa            1
Durbanville, WC, ZA                                1
Kenilworth, WC, ZA                                 1
Northern Suburbs, WC, ZA                           1
Tygervalley, WC, ZA                                1
Name: count, dtype: int64

### First, I'm splitting and selecting the first values as this is the only data we need. (Everything is based already in WC/Western Cape ZA)

In [6]:
df['Location'] = df['location'].apply(lambda x: x.split(',')[0])
df['Location'].value_counts()

Location
Cape Town            195
City of Cape Town     38
Stellenbosch          16
Bellville              7
Somerset West          4
Brackenfell            4
Milnerton              3
Century City           3
Durbanville            2
Pinelands              2
Claremont              2
Rosebank               1
Nuweland               1
Wynberg                1
Southern Suburbs       1
Goodwood               1
Sea Point              1
Blackheath             1
Rondebosch             1
Paarl                  1
Darling                1
Kenilworth             1
Northern Suburbs       1
Tygervalley            1
Name: count, dtype: int64

### Some locations are suburbs of Cape Town.

In [7]:
suburbs_ct = {'Bellville': 'Cape Town', 'Somerset West': 'Cape Town', 'Brackenfell': 'Cape Town',
    'Milnerton': 'Cape Town', 'Century City': 'Cape Town', 'Durbanville': 'Cape Town',
    'Pinelands': 'Cape Town', 'Claremont': 'Cape Town', 'Rosebank': 'Cape Town',
    'Nuweland': 'Cape Town', 'Wynberg': 'Cape Town', 'Southern Suburbs': 'Cape Town',
    'Goodwood': 'Cape Town', 'Sea Point': 'Cape Town', 'Blackheath': 'Cape Town',
    'Rondebosch': 'Cape Town', 'Kenilworth': 'Cape Town', 'Northern Suburbs': 'Cape Town',
    'Tygervalley': 'Cape Town', 'City of Cape Town': 'Cape Town'}
df['City'] = df['Location'].replace(suburbs_ct).sort_index()
df.City.value_counts()

City
Cape Town       271
Stellenbosch     16
Paarl             1
Darling           1
Name: count, dtype: int64

In [8]:
df.iloc[:,9:11][:50]

             Location          City
0           Bellville     Cape Town
1           Cape Town     Cape Town
2           Cape Town     Cape Town
3            Rosebank     Cape Town
4           Cape Town     Cape Town
5           Bellville     Cape Town
6           Cape Town     Cape Town
7           Cape Town     Cape Town
8            Nuweland     Cape Town
9        Stellenbosch  Stellenbosch
10          Cape Town     Cape Town
11          Cape Town     Cape Town
12          Cape Town     Cape Town
13          Cape Town     Cape Town
14            Wynberg     Cape Town
15          Cape Town     Cape Town
16          Cape Town     Cape Town
17          Cape Town     Cape Town
18          Cape Town     Cape Town
19          Cape Town     Cape Town
20          Cape Town     Cape Town
21          Cape Town     Cape Town
22   Southern Suburbs     Cape Town
23          Cape Town     Cape Town
24          Cape Town     Cape Town
25          Cape Town     Cape Town
26      Somerset West     Cape Town
27           Goodwood     Cape Town
28          Cape Town     Cape Town
29       Stellenbosch  Stellenbosch
30          Cape Town     Cape Town
31          Cape Town     Cape Town
32          Cape Town     Cape Town
33          Sea Point     Cape Town
34          Milnerton     Cape Town
35          Cape Town     Cape Town
36          Cape Town     Cape Town
37        Brackenfell     Cape Town
38        Brackenfell     Cape Town
39          Cape Town     Cape Town
40          Cape Town     Cape Town
41  City of Cape Town     Cape Town
42          Bellville     Cape Town
43          Cape Town     Cape Town
44       Stellenbosch  Stellenbosch
45          Cape Town     Cape Town
46  City of Cape Town     Cape Town
47       Stellenbosch  Stellenbosch
48  City of Cape Town     Cape Town
49  City of Cape Town     Cape Town

### After confirming the locations, I drop the unformatted 'location' column.

In [9]:
df = df.drop(columns='location')
df

,search_role,site,title,company,job_type,is_remote,date_posted,description,Location,City
0,Data Analyst,indeed,Claims Risk Analyst,Momentum Health,NaN,False,2026-06-12,**Introduction**\nThrough our client\-facing b...,Bellville,Cape Town
1,Data Analyst,indeed,Senior Application Support Analyst (SQL-focused),MRI Software,fulltime,False,2026-06-12,MRI Software is seeking a Senior Application S...,Cape Town,Cape Town
2,Data Analyst,indeed,SOC Analyst,Zappi,fulltime,False,2026-06-12,### **Description**\n\n \n\nWe believe in hir...,Cape Town,Cape Town
3,Data Analyst,indeed,Chief Delivery Officer (CDO),NJ Placement Consulting,fulltime,False,2026-06-12,##### **Overview**\n\n\nAmazing chance to join...,Rosebank,Cape Town
4,Data Analyst,indeed,Business Intelligence Analyst,LekkeSlaap,fulltime,True,2026-06-12,Bring 3\+ years of proven experience in busine...,Cape Town,Cape Town
...,...,...,...,...,...,...,...,...,...,...
284,Data Architect,linkedin,Lead Data Scientist,Network Recruitment,NaN,False,2026-06-02,NaN,City of Cape Town,Cape Town
285,Data Architect,linkedin,Associate SAP Human Capital Solutions Architec...,Sanlam,NaN,False,2026-06-01,NaN,Cape Town,Cape Town
286,Data Architect,linkedin,Modeller - OLAP/Automation,Circana,NaN,False,2026-06-01,NaN,Cape Town,Cape Town
287,Data Architect,linkedin,Senior Data Analyst,impact.com,NaN,False,NaT,NaN,Cape Town,Cape Town
288,Data Architect,linkedin,Product Manager - Group Data Platform,Sanlam,NaN,False,NaT,NaN,Cape Town,Cape Town

# Assigning Seniority of Job Positions to Level Column.

In [10]:
def get_level(title):
    title = str(title).lower()
    if 'senior' in title or 'snr' in title:
        return 'Senior'
    elif 'junior' in title or 'jnr' in title or 'graduate' in title or 'no experience' in title:
        return 'Junior'
    elif 'associate' in title:
        return 'Associate/Entry'
    else:
        return 'Mid-Level'

df['Level'] = df['title'].apply(get_level)

In [11]:
df['Level'].value_counts()

Level
Mid-Level          212
Senior              65
Junior              10
Associate/Entry      2
Name: count, dtype: int64

# Formatting Job Type Column.

## Seperating job_type by Full-Time, Part-Time & Internship.

In [12]:
df.job_type.value_counts()

job_type
fulltime              63
parttime, fulltime     2
parttime               1
internship             1
Name: count, dtype: int64

### First in removing the confusion 'parttime, fulltime' by converting them to full-time.

In [13]:
df.job_type = df.job_type.replace({"parttime, fulltime":"fulltime"})
df.job_type.value_counts()

job_type
fulltime      65
parttime       1
internship     1
Name: count, dtype: int64

### Then I format the strings/title to make it easier to read.

In [14]:
def get_job_type(job_type):
    job_type = str(job_type).lower().strip()
    if 'fulltime' in job_type:
        return "Full-Time"
    elif 'parttime' in job_type:
        return "Part-Time"
    elif 'internship' in job_type:
        return "Internship"
    elif 'unknown' in job_type:
        return "Unknown"
df['Job Type'] = df['job_type'].apply(get_job_type)
df['Job Type'].value_counts()

Job Type
Full-Time     65
Part-Time      1
Internship     1
Name: count, dtype: int64

In [15]:
df

,search_role,site,title,company,job_type,is_remote,date_posted,description,Location,City,Level,Job Type
0,Data Analyst,indeed,Claims Risk Analyst,Momentum Health,NaN,False,2026-06-12,**Introduction**\nThrough our client\-facing b...,Bellville,Cape Town,Mid-Level,NaN
1,Data Analyst,indeed,Senior Application Support Analyst (SQL-focused),MRI Software,fulltime,False,2026-06-12,MRI Software is seeking a Senior Application S...,Cape Town,Cape Town,Senior,Full-Time
2,Data Analyst,indeed,SOC Analyst,Zappi,fulltime,False,2026-06-12,### **Description**\n\n \n\nWe believe in hir...,Cape Town,Cape Town,Mid-Level,Full-Time
3,Data Analyst,indeed,Chief Delivery Officer (CDO),NJ Placement Consulting,fulltime,False,2026-06-12,##### **Overview**\n\n\nAmazing chance to join...,Rosebank,Cape Town,Mid-Level,Full-Time
4,Data Analyst,indeed,Business Intelligence Analyst,LekkeSlaap,fulltime,True,2026-06-12,Bring 3\+ years of proven experience in busine...,Cape Town,Cape Town,Mid-Level,Full-Time
...,...,...,...,...,...,...,...,...,...,...,...,...
284,Data Architect,linkedin,Lead Data Scientist,Network Recruitment,NaN,False,2026-06-02,NaN,City of Cape Town,Cape Town,Mid-Level,NaN
285,Data Architect,linkedin,Associate SAP Human Capital Solutions Architec...,Sanlam,NaN,False,2026-06-01,NaN,Cape Town,Cape Town,Associate/Entry,NaN
286,Data Architect,linkedin,Modeller - OLAP/Automation,Circana,NaN,False,2026-06-01,NaN,Cape Town,Cape Town,Mid-Level,NaN
287,Data Architect,linkedin,Senior Data Analyst,impact.com,NaN,False,NaT,NaN,Cape Town,Cape Town,Senior,NaN
288,Data Architect,linkedin,Product Manager - Group Data Platform,Sanlam,NaN,False,NaT,NaN,Cape Town,Cape Town,Mid-Level,NaN

### Now I'll drop job_type column as it's no longer needed.

In [16]:
df = df.drop(columns='job_type')
df

,search_role,site,title,company,is_remote,date_posted,description,Location,City,Level,Job Type
0,Data Analyst,indeed,Claims Risk Analyst,Momentum Health,False,2026-06-12,**Introduction**\nThrough our client\-facing b...,Bellville,Cape Town,Mid-Level,NaN
1,Data Analyst,indeed,Senior Application Support Analyst (SQL-focused),MRI Software,False,2026-06-12,MRI Software is seeking a Senior Application S...,Cape Town,Cape Town,Senior,Full-Time
2,Data Analyst,indeed,SOC Analyst,Zappi,False,2026-06-12,### **Description**\n\n \n\nWe believe in hir...,Cape Town,Cape Town,Mid-Level,Full-Time
3,Data Analyst,indeed,Chief Delivery Officer (CDO),NJ Placement Consulting,False,2026-06-12,##### **Overview**\n\n\nAmazing chance to join...,Rosebank,Cape Town,Mid-Level,Full-Time
4,Data Analyst,indeed,Business Intelligence Analyst,LekkeSlaap,True,2026-06-12,Bring 3\+ years of proven experience in busine...,Cape Town,Cape Town,Mid-Level,Full-Time
...,...,...,...,...,...,...,...,...,...,...,...
284,Data Architect,linkedin,Lead Data Scientist,Network Recruitment,False,2026-06-02,NaN,City of Cape Town,Cape Town,Mid-Level,NaN
285,Data Architect,linkedin,Associate SAP Human Capital Solutions Architec...,Sanlam,False,2026-06-01,NaN,Cape Town,Cape Town,Associate/Entry,NaN
286,Data Architect,linkedin,Modeller - OLAP/Automation,Circana,False,2026-06-01,NaN,Cape Town,Cape Town,Mid-Level,NaN
287,Data Architect,linkedin,Senior Data Analyst,impact.com,False,NaT,NaN,Cape Town,Cape Town,Senior,NaN
288,Data Architect,linkedin,Product Manager - Group Data Platform,Sanlam,False,NaT,NaN,Cape Town,Cape Town,Mid-Level,NaN

# Cleaning Description Column.

### Next I want clean the description column by removing characters and strange syntax.

In [17]:
df['description']

0      **Introduction**\nThrough our client\-facing b...
1      MRI Software is seeking a Senior Application S...
2      ### **Description**\n\n  \n\nWe believe in hir...
3      ##### **Overview**\n\n\nAmazing chance to join...
4      Bring 3\+ years of proven experience in busine...
                             ...
284                                                  NaN
285                                                  NaN
286                                                  NaN
287                                                  NaN
288                                                  NaN
Name: description, Length: 289, dtype: str

### Using Python Regex for specifying patterns.

In [18]:
patterns = r'\\n|\n|\*{1,3}|=+|#{1,6}\s*|---+|/'

df['Description'] = (
    df['description']
    .str.replace(patterns, ' ', regex=True)
    .str.replace(r'\\-', '-', regex=True)
    .str.replace(r'\\&', '&', regex=True)    # \& → &
    .str.replace(r'\\|', '', regex=True)     # \| → remove
    .str.replace(r'\s{2,}', ' ', regex=True)
    .str.strip()
    .replace('Unknown', None)
)

### Seems like every weird characters are removed ;)

In [19]:
print(df['Description'].iloc[0])

Introduction Through our client-facing brands Metropolitan and Momentum, with Multiply (wellness and rewards programme), and our other specialist brands, including Guardrisk and Eris Property Group, the group enables business and people from all walks of life to achieve their financial goals and life aspirations. We help people grow their savings, protect what matters to them and invest for the future. We help companies and organisations care for and reward their employees and members. Through our own network of advisers or via independent brokers and utilising new platforms Momentum Metropolitan provides practical financial solutions for people, communities, and businesses. Disclaimer As an applicant, please verify the legitimacy of this job advert on our company career page. Role Purpose To conduct desktop based forensic investigations into potential instances of fraud, waste and or abuse across Momentum Health admisitered schemes and to collect documentory evidence, engage with all relevant parties i.e., service providers, members etc. drafting letters and investigation reports, perform data analytics and assit in the recovery of irregular paid claims. Requirements Qualification Valid Matric certificate. A relevant tertiary qualification such as, Clinical Healthcare related, Law, including Compliance, Business Operations e.g., auditing, accounting & operations. Knowledge Medical Scheme knowledge would be advantages. Years of experience Three years of forensic experience. Duties & Responsibilities Internal Process Conducting desktop forensic investigation in order to identify potential instances of fraud, waste and or abuse across MH administered schemes. Reporting on investigations conducted by submitting an investigation report to management for review and submission to the relevant scheme. Engage with relevant stakeholders (internal & external) to collect documentary evidence on instances of fraud, waste and or abuse identified. Draft letters providers members to raise concerns with regards to irregularities identified Perform data analytics to identify concerning trends on each investigation using the analytical tool available. Client Build and maintain relationships with internal and external stakeholders. Deliver on service level agreements applicable to clients, internal and external stakeholders in order to ensure that client expectations are managed. Make recommendations to improve claims processes controls where deficiencies in these areas are highlighted through investigations. Participate and contribute to a culture which builds rewarding relationships, facilitates feedback and provides exceptional client service. Continuously monitor turnaround times and quality standards and resolve issues speedily to enhance client service delivery. Drive client service delivery goal achievement in line with predefined standards in order to ensure that clients receive appropriate advice and after sales service. Manage the assigned investigation to ensure that fraud waste and abuse risks are mitigated through identification and investigation of potential fraud waste and or abuse. People Build strong relationships with peers and managers to ensure successful investigation outcomes. Continuously develop own expertise in terms of industry and subject matter development and application thereof in an area of specialisation. Contribute to continuous innovation through the development, sharing and or implementation of new ideas and involvement of colleagues and staff. Participate and contribute to a culture of work centric thinking, productivity, service delivery and quality management. Take ownership for driving own career development. Finance Assist in the recovery of irregular paid claims through engagement with providers and obtaining provider agreement on the repayment of irregular claims. Identify solutions to enhance cost effectiveness and increase operational efficiency. Competencies Analytical thinking Healthcare industry knowledge (advantageous) Time management Attention to detail Problem-solving Communication Confidentiality Adherence to regulations Maturity: Display a high level of emotional maturity, professionalism, and soundjudgment in handling sensitive cases and maintaining confi dentiality as well asinterpersonal offi ce relationships. Hardworking: Demonstrate a strong work ethic, dedication, and a commitment tomeeting deadlines and delivering quality results. Professionalism: Uphold the highest standards of professionalism, ethics, andintegrity, with a focus on the job's core responsibilities rather than engaging indisruptive, insubordinate, or disrespectful practices.

### Dropping the old description column.

In [20]:
df = df.drop(columns='description')
df

,search_role,site,title,company,is_remote,date_posted,Location,City,Level,Job Type,Description
0,Data Analyst,indeed,Claims Risk Analyst,Momentum Health,False,2026-06-12,Bellville,Cape Town,Mid-Level,NaN,Introduction Through our client-facing brands ...
1,Data Analyst,indeed,Senior Application Support Analyst (SQL-focused),MRI Software,False,2026-06-12,Cape Town,Cape Town,Senior,Full-Time,MRI Software is seeking a Senior Application S...
2,Data Analyst,indeed,SOC Analyst,Zappi,False,2026-06-12,Cape Town,Cape Town,Mid-Level,Full-Time,Description We believe in hiring analysts who ...
3,Data Analyst,indeed,Chief Delivery Officer (CDO),NJ Placement Consulting,False,2026-06-12,Rosebank,Cape Town,Mid-Level,Full-Time,Overview Amazing chance to join a Software Dev...
4,Data Analyst,indeed,Business Intelligence Analyst,LekkeSlaap,True,2026-06-12,Cape Town,Cape Town,Mid-Level,Full-Time,Bring 3+ years of proven experience in busines...
...,...,...,...,...,...,...,...,...,...,...,...
284,Data Architect,linkedin,Lead Data Scientist,Network Recruitment,False,2026-06-02,City of Cape Town,Cape Town,Mid-Level,NaN,NaN
285,Data Architect,linkedin,Associate SAP Human Capital Solutions Architec...,Sanlam,False,2026-06-01,Cape Town,Cape Town,Associate/Entry,NaN,NaN
286,Data Architect,linkedin,Modeller - OLAP/Automation,Circana,False,2026-06-01,Cape Town,Cape Town,Mid-Level,NaN,NaN
287,Data Architect,linkedin,Senior Data Analyst,impact.com,False,NaT,Cape Town,Cape Town,Senior,NaN,NaN
288,Data Architect,linkedin,Product Manager - Group Data Platform,Sanlam,False,NaT,Cape Town,Cape Town,Mid-Level,NaN,NaN

# Clearing Titles as there is non-data role titles. (E.g Soc Analyst etc)

In [21]:
df.title.value_counts()

title
Software Engineer                                                                    6
Data Analyst                                                                         5
Senior Data Engineer                                                                 5
Business Intelligence Analyst                                                        4
DevOps Engineer                                                                      4
                                                                                    ..
Performance Marketing Lead (Meta)                                                    1
Integration Developer (Azure & Business Central)                                     1
Associate SAP Human Capital Solutions Architect (Sanlam Head Office in Bellville)    1
Modeller - OLAP/Automation                                                           1
Product Manager - Group Data Platform                                                1
Name: count, Length: 249, dtype: int64

In [22]:
# Creating a filter that contains these keywords. (inclusion filter)
inc_keywords = 'data|analyst|machine|learning|scientist|engineer|ai|architect'
# 'df=' replaces values, 'df[df...]' creates boolean index where the values should be passed as True or False.
df = df[df['title'].str.contains(inc_keywords, case=False, na=False)] # 'case=False' searches case insensitive, 'na=False' prevents errors if a row has missing values.
df.title.value_counts()[:60]

title
Software Engineer                                                         6
Data Analyst                                                              5
Senior Data Engineer                                                      5
Business Intelligence Analyst                                             4
DevOps Engineer                                                           4
Technical Support Engineer                                                3
Legal Content Analyst                                                     2
FinOps Analyst                                                            2
Yield Analyst                                                             2
Business Process Analyst                                                  2
Senior Data Analyst                                                       2
Data Engineer                                                             2
Quantitative Analyst                                                      2
Data Scientist                                                            2
Machine Learning Engineer                                                 2
Project Engineer                                                          2
Senior Software Engineer                                                  2
Software Development Engineer, AWS Kumo Health Experience                 2
Lead Machine Learning Engineer                                            2
Lead Data Scientist                                                       2
Analyst                                                                   2
Technical Business Analyst                                                2
Business Analyst                                                          2
Senior Analytics Engineer                                                 2
Claims Risk Analyst                                                       1
Senior Application Support Analyst (SQL-focused)                          1
SOC Analyst                                                               1
Technical Product Analyst                                                 1
Utilities Analyst                                                         1
Data Integrations Specialist - Client Focus                               1
Senior BI Analyst - Team Leader                                           1
Domain / Product owner - HR systems                                       1
Customer Success Reporting Analyst                                        1
Conflict Analyst                                                          1
Paid Media Analyst                                                        1
Supply Chain Process Analyst                                              1
BUSINESS ANALYST (INDUSTRIAL ENGINEER)                                    1
Manager, Grade 1: Spatial Analyst                                         1
Integration Engineer/Developer                                            1
Insight Analyst (Professional, BI Specialist (TCF))                       1
Investment Guidelines Analyst (Contractor)                                1
Databricks Data Engineer                                                  1
Commercial Finance Business Analyst                                       1
Quality Analyst                                                           1
Supply Chain Analyst                                                      1
Data Management Analyst                                                   1
Junior Credit Risk Analyst                                                1
Sales Analyst (6 Month Contract)                                          1
CRM & Data Analyst                                                        1
Realtime Analyst                                                          1
Quality Analyst - Financial Services - Onsite - Cape Town                 1
Senior Retail Media Insights Analyst                                      1
Digital Data Analyst (Rainmaker Media)                                    1
Business Intelligence Analyst (Retail) - Corporate Placements             1
Data Engineer (Senior)                                                    1
Applied Research Engineer                                                 1
BI Analyst                                                                1
Senior Space Analyst                                                      1
Market Research Data Analyst                                              1
Data Analyst (Marketing Analytics, Bangkok Based, Relocation provided)    1
Name: count, dtype: int64

In [23]:
df.title.shape

(242,)

### Still seeing 'SOC Analyst', I guess it passed because of the 'Analyst' keyword.
### So this means I have to create a exclude filter aswell.

In [24]:
# Keywords to exclude.
exc_keywords = 'soc|devops|software engineer|software development|technical support|legal|forensic|security|project engineer'
df = df[~df['title'].str.contains(exc_keywords, case=False, na=False)]  # '~df['title'] means keep rows where the title does NOT contain these keywords.
df.title.value_counts()[:60]

title
Data Analyst                                                              5
Senior Data Engineer                                                      5
Business Intelligence Analyst                                             4
FinOps Analyst                                                            2
Yield Analyst                                                             2
Business Process Analyst                                                  2
Senior Data Analyst                                                       2
Data Engineer                                                             2
Quantitative Analyst                                                      2
Data Scientist                                                            2
Machine Learning Engineer                                                 2
Lead Machine Learning Engineer                                            2
Lead Data Scientist                                                       2
Analyst                                                                   2
Technical Business Analyst                                                2
Business Analyst                                                          2
Senior Analytics Engineer                                                 2
Claims Risk Analyst                                                       1
Senior Application Support Analyst (SQL-focused)                          1
Technical Product Analyst                                                 1
Utilities Analyst                                                         1
Data Integrations Specialist - Client Focus                               1
Senior BI Analyst - Team Leader                                           1
Domain / Product owner - HR systems                                       1
Customer Success Reporting Analyst                                        1
Conflict Analyst                                                          1
Paid Media Analyst                                                        1
Supply Chain Process Analyst                                              1
BUSINESS ANALYST (INDUSTRIAL ENGINEER)                                    1
Manager, Grade 1: Spatial Analyst                                         1
Integration Engineer/Developer                                            1
Insight Analyst (Professional, BI Specialist (TCF))                       1
Investment Guidelines Analyst (Contractor)                                1
Databricks Data Engineer                                                  1
Commercial Finance Business Analyst                                       1
Quality Analyst                                                           1
Supply Chain Analyst                                                      1
Data Management Analyst                                                   1
Junior Credit Risk Analyst                                                1
Sales Analyst (6 Month Contract)                                          1
CRM & Data Analyst                                                        1
Realtime Analyst                                                          1
Quality Analyst - Financial Services - Onsite - Cape Town                 1
Senior Retail Media Insights Analyst                                      1
Digital Data Analyst (Rainmaker Media)                                    1
Business Intelligence Analyst (Retail) - Corporate Placements             1
Data Engineer (Senior)                                                    1
Applied Research Engineer                                                 1
BI Analyst                                                                1
Senior Space Analyst                                                      1
Market Research Data Analyst                                              1
Data Analyst (Marketing Analytics, Bangkok Based, Relocation provided)    1
Data Engineer - Databricks - July Start                                   1
Fundraising Systems and Data Specialist (m/f/d)                           1
Junior Data Engineer                                                      1
Business Data Analyst                                                     1
Data & Insights Analyst                                                   1
Client Reporting Analyst (12-month contract) – Investment Management      1
Remote Data/Image Collector (No Experience Needed)                        1
Data Analyst II_Pipeline                                                  1
Name: count, dtype: int64

In [29]:
df.shape

(190, 11)

## Making the titles look neater.

In [25]:
df.rename(columns={"search_role":"Search Word", "site":"Website", "title":"Title", "company":"Company", "is_remote":"Remote", "date_posted":"Date Posted"}, inplace=True)
df

,Search Word,Website,Title,Company,Remote,Date Posted,Location,City,Level,Job Type,Description
0,Data Analyst,indeed,Claims Risk Analyst,Momentum Health,False,2026-06-12,Bellville,Cape Town,Mid-Level,NaN,Introduction Through our client-facing brands ...
1,Data Analyst,indeed,Senior Application Support Analyst (SQL-focused),MRI Software,False,2026-06-12,Cape Town,Cape Town,Senior,Full-Time,MRI Software is seeking a Senior Application S...
4,Data Analyst,indeed,Business Intelligence Analyst,LekkeSlaap,True,2026-06-12,Cape Town,Cape Town,Mid-Level,Full-Time,Bring 3+ years of proven experience in busines...
5,Data Analyst,indeed,Technical Product Analyst,Sanlam,False,2026-06-12,Bellville,Cape Town,Mid-Level,NaN,Who are we? Sanlam Life and Savings (SLS) is f...
6,Data Analyst,indeed,Utilities Analyst,FPG Property Management,False,2026-06-12,Cape Town,Cape Town,Mid-Level,Full-Time,PURPOSE OF JOB The Utilities Analyst is respon...
...,...,...,...,...,...,...,...,...,...,...,...
280,Data Architect,linkedin,Data Strategy Consultant,Tiko,False,2026-06-08,City of Cape Town,Cape Town,Mid-Level,NaN,NaN
283,Data Architect,linkedin,Senior Data Engineer,DigiOutsource,False,2026-06-06,Cape Town,Cape Town,Senior,NaN,NaN
284,Data Architect,linkedin,Lead Data Scientist,Network Recruitment,False,2026-06-02,City of Cape Town,Cape Town,Mid-Level,NaN,NaN
287,Data Architect,linkedin,Senior Data Analyst,impact.com,False,NaT,Cape Town,Cape Town,Senior,NaN,NaN
288,Data Architect,linkedin,Product Manager - Group Data Platform,Sanlam,False,NaT,Cape Town,Cape Town,Mid-Level,NaN,NaN

# Replacing NaN values with 'Unknown'.

In [26]:
df = df.fillna('Unknown')
df

,Search Word,Website,Title,Company,Remote,Date Posted,Location,City,Level,Job Type,Description
0,Data Analyst,indeed,Claims Risk Analyst,Momentum Health,False,2026-06-12,Bellville,Cape Town,Mid-Level,Unknown,Introduction Through our client-facing brands ...
1,Data Analyst,indeed,Senior Application Support Analyst (SQL-focused),MRI Software,False,2026-06-12,Cape Town,Cape Town,Senior,Full-Time,MRI Software is seeking a Senior Application S...
4,Data Analyst,indeed,Business Intelligence Analyst,LekkeSlaap,True,2026-06-12,Cape Town,Cape Town,Mid-Level,Full-Time,Bring 3+ years of proven experience in busines...
5,Data Analyst,indeed,Technical Product Analyst,Sanlam,False,2026-06-12,Bellville,Cape Town,Mid-Level,Unknown,Who are we? Sanlam Life and Savings (SLS) is f...
6,Data Analyst,indeed,Utilities Analyst,FPG Property Management,False,2026-06-12,Cape Town,Cape Town,Mid-Level,Full-Time,PURPOSE OF JOB The Utilities Analyst is respon...
...,...,...,...,...,...,...,...,...,...,...,...
280,Data Architect,linkedin,Data Strategy Consultant,Tiko,False,2026-06-08,City of Cape Town,Cape Town,Mid-Level,Unknown,Unknown
283,Data Architect,linkedin,Senior Data Engineer,DigiOutsource,False,2026-06-06,Cape Town,Cape Town,Senior,Unknown,Unknown
284,Data Architect,linkedin,Lead Data Scientist,Network Recruitment,False,2026-06-02,City of Cape Town,Cape Town,Mid-Level,Unknown,Unknown
287,Data Architect,linkedin,Senior Data Analyst,impact.com,False,Unknown,Cape Town,Cape Town,Senior,Unknown,Unknown
288,Data Architect,linkedin,Product Manager - Group Data Platform,Sanlam,False,Unknown,Cape Town,Cape Town,Mid-Level,Unknown,Unknown

# Outputting the file as 'wc_jobs_cleaned.csv'

In [27]:
df.to_csv('wc_jobs_cleaned.csv', index=False)